# SQL Data Analysis Workshop

 This workshop is designed to help you build practical SQL skills by analyzing real-world business data. 
     
The tasks are divided into 4 levels to gradually progress from basic data retrieval to advanced analysis. Each level focuses on specific SQL concepts and challenges, allowing you to practice query writing, data filtering, aggregations, joins, and subqueries.
- Level 1: Basic SQL queries (SELECT, WHERE, ORDER BY, COUNT).
- Level 2: Aggregations (SUM, AVG, GROUP BY) and basic joins.
- Level 3: Complex joins, subqueries, and multi-table analysis.
- Level 4: Advanced analytical tasks focused on complex queries, subqueries, and aggregations..

This structured approach ensures you build confidence and expertise in SQL, preparing you for real-world data analysis challenges. ðŸš€

---
## Setup the work environment

#### 1. Library's import

In [6]:
import pandas as pd
import mysql.connector

#### 2. Connecting to the Database

In [8]:
connection = mysql.connector.connect(
    host="localhost",
    user="root",
    password="",
    database="bike_zeyad"
)

cursor = connection.cursor()
print("Connection established successfully.")

Connection established successfully.

#### 3. Setup for SQL Magic

In [10]:
pip install ipython-sql

Requirement already satisfied: ipython-sql in c:\users\afaqe\anaconda3\lib\site-packages (0.5.0)
Requirement already satisfied: prettytable in c:\users\afaqe\anaconda3\lib\site-packages (from ipython-sql) (3.12.0)
Requirement already satisfied: ipython in c:\users\afaqe\anaconda3\lib\site-packages (from ipython-sql) (8.27.0)
Requirement already satisfied: sqlalchemy>=2.0 in c:\users\afaqe\anaconda3\lib\site-packages (from ipython-sql) (2.0.34)
Requirement already satisfied: sqlparse in c:\users\afaqe\anaconda3\lib\site-packages (from ipython-sql) (0.5.3)
Requirement already satisfied: six in c:\users\afaqe\anaconda3\lib\site-packages (from ipython-sql) (1.16.0)
Requirement already satisfied: ipython-genutils in c:\users\afaqe\anaconda3\lib\site-packages (from ipython-sql) (0.2.0)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\afaqe\anaconda3\lib\site-packages (from sqlalchemy>=2.0->ipython-sql) (4.11.0)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\afaqe\anaconda3\lib\site-packages (from sqlalchemy>=2.0->ipython-sql) (3.0.1)
Requirement already satisfied: decorator in c:\users\afaqe\anaconda3\lib\site-packages (from ipython->ipython-sql) (5.1.1)
Requirement already satisfied: jedi>=0.16 in c:\users\afaqe\anaconda3\lib\site-packages (from ipython->ipython-sql) (0.19.1)
Requirement already satisfied: matplotlib-inline in c:\users\afaqe\anaconda3\lib\site-packages (from ipython->ipython-sql) (0.1.6)
Requirement already satisfied: prompt-toolkit<3.1.0,>=3.0.41 in c:\users\afaqe\anaconda3\lib\site-packages (from ipython->ipython-sql) (3.0.43)
Requirement already satisfied: pygments>=2.4.0 in c:\users\afaqe\anaconda3\lib\site-packages (from ipython->ipython-sql) (2.15.1)
Requirement already satisfied: stack-data in c:\users\afaqe\anaconda3\lib\site-packages (from ipython->ipython-sql) (0.2.0)
Requirement already satisfied: traitlets>=5.13.0 in c:\users\afaqe\anaconda3\lib\site-packages (from ipython->ipython-sql) (5.14.3)
Requirement already satisfied: colorama in c:\users\afaqe\anaconda3\lib\site-packages (from ipython->ipython-sql) (0.4.6)
Requirement already satisfied: wcwidth in c:\users\afaqe\anaconda3\lib\site-packages (from prettytable->ipython-sql) (0.2.5)
Requirement already satisfied: parso<0.9.0,>=0.8.3 in c:\users\afaqe\anaconda3\lib\site-packages (from jedi>=0.16->ipython->ipython-sql) (0.8.3)
Requirement already satisfied: executing in c:\users\afaqe\anaconda3\lib\site-packages (from stack-data->ipython->ipython-sql) (0.8.3)
Requirement already satisfied: asttokens in c:\users\afaqe\anaconda3\lib\site-packages (from stack-data->ipython->ipython-sql) (2.0.5)
Requirement already satisfied: pure-eval in c:\users\afaqe\anaconda3\lib\site-packages (from stack-data->ipython->ipython-sql) (0.2.2)
Note: you may need to restart the kernel to use updated packages.

In [11]:
%load_ext sql

In [12]:
%sql mysql+pymysql://root:@localhost/bike_zeyad

Connecting to 'mysql+pymysql://root:***@localhost/bike_zeyad'

In [34]:
%config SqlMagic.displaylimit = None
%sql SELECT * FROM languages

displaylimit: Value None will be treated as 0 (no limit)

Running query in 'mysql+pymysql://root:***@localhost/bike_zeyad'

RuntimeError: If using snippets, you may pass the --with argument explicitly.
For more details please refer: https://jupysql.ploomber.io/en/latest/compose.html#with-argument


Original error message from DB driver:
(pymysql.err.ProgrammingError) (1146, "Table 'bike_zeyad.languages' doesn't exist")
[SQL: SELECT * FROM languages]
(Background on this error at: https://sqlalche.me/e/20/f405)

If you need help solving this issue, send us a message: https://ploomber.io/community


---
## Level 1: Beginner â€“ Basic Queries (using SQL Magic)

### Task 1: Retrieve all rows and columns from the customers table.

In [36]:
%sql SELECT * FROM customers;

Running query in 'mysql+pymysql://root:***@localhost/bike_zeyad'

1445 rows affected.

+-------------+-------------+-------------+----------------+------------------------------------+--------------------------------+------------------------+-------+----------+
| customer_id |  first_name |  last_name  |     phone      |               email                |             street             |          city          | state | zip_code |
+-------------+-------------+-------------+----------------+------------------------------------+--------------------------------+------------------------+-------+----------+
|      1      |    Debra    |    Burks    |      None      |       debra.burks@yahoo.com        |       9273 Thorne Ave.         |      Orchard Park      |   NY  |  14127   |
|      2      |    Kasha    |     Todd    |      None      |        kasha.todd@yahoo.com        |        910 Vine Street         |        Campbell        |   CA  |  95008   |
|      3      |    Tameka   |    Fisher   |      None      |       tameka.fisher@aol.com        |     769C Honey Creek St.       |     Redondo Beach      |   CA  |  90278   |
|      4      |    Daryl    |    Spence   |      None      |        daryl.spence@aol.com        |        988 Pearl Lane          |       Uniondale        |   NY  |  11553   |
|      5      |  Charolette |     Rice    | (916) 381-6003 |      charolette.rice@msn.com       |         107 River Dr.          |       Sacramento       |   CA  |  95820   |
|      6      |   Lyndsey   |     Bean    |      None      |      lyndsey.bean@hotmail.com      |         769 West Road          |        Fairport        |   NY  |  14450   |
|      7      |   Latasha   |     Hays    | (716) 986-3359 |      latasha.hays@hotmail.com      |    7014 Manor Station Rd.      |        Buffalo         |   NY  |  14215   |
|      8      |  Jacquline  |    Duncan   |      None      |     jacquline.duncan@yahoo.com     |         15 Brown St.           |    Jackson Heights     |   NY  |  11372   |
|      9      |   Genoveva  |   Baldwin   |      None      |      genoveva.baldwin@msn.com      |       8550 Spruce Drive        |    Port Washington     |   NY  |  11050   |
|      10     |   Pamelia   |    Newman   |      None      |      pamelia.newman@gmail.com      |       476 Chestnut Ave.        |         Monroe         |   NY  |  10950   |
|      11     |   Deshawn   |   Mendoza   |      None      |     deshawn.mendoza@yahoo.com      |    8790 Cobblestone Street     |         Monsey         |   NY  |  10952   |
|      12     |    Robby    |    Sykes    | (516) 583-7761 |      robby.sykes@hotmail.com       |     486 Rock Maple Street      |       Hempstead        |   NY  |  11550   |
|      13     |   Lashawn   |    Ortiz    |      None      |       lashawn.ortiz@msn.com        |       27 Washington Rd.        |        Longview        |   TX  |  75604   |
|      14     |    Garry    |   Espinoza  |      None      |     garry.espinoza@hotmail.com     |      7858 Rockaway Court       |         Forney         |   TX  |  75126   |
|      15     |    Linnie   |    Branch   |      None      |      linnie.branch@gmail.com       |    314 South Columbia Ave.     |      Plattsburgh       |   NY  |  12901   |
|      16     |    Emmitt   |   Sanchez   | (212) 945-8823 |     emmitt.sanchez@hotmail.com     |     461 Squaw Creek Road       |        New York        |   NY  |  10002   |
|      17     |    Caren    |   Stephens  |      None      |       caren.stephens@msn.com       |         914 Brook St.          |       Scarsdale        |   NY  |  10583   |
|      18     |  Georgetta  |    Hardin   |      None      |      georgetta.hardin@aol.com      |        474 Chapel Dr.          |      Canandaigua       |   NY  |  14424   |
|      19     |   Lizzette  |    Stein    |      None      |      lizzette.stein@yahoo.com      |      19 Green Hill Lane        |      Orchard Park      |   NY  |  14127   |
|      20     |    Aleta    |   Shepard   |      None      |       aleta.shepard@aol.com        |        684 Howard St.          |       Sugar Land       |   TX  |  77478   |
|      21     |    Tobie    |    Little   |      None      |       tobie.little@gmail.com       |      10 Silver Spear Dr.       |        Victoria        |   TX  |  77904   |
|      22     |    Adelle   |    Larsen   |      None      |      adelle.larsen@gmail.com       |     683 West Kirkland Dr.      |     East Northport     |   NY  |  11731   |
|      23     |    Kaylee   |   English   |      None      |       kaylee.english@msn.com       |        8786 Fulton Rd.         |         Hollis         |   NY  |  11423   |
|      24     |    Corene   |     Wall    |      None      |        corene.wall@msn.com         |        9601 Ocean Rd.          |        Atwater         |   CA  |  95301   |
|      25     |   Regenia   |   Vaughan   |      None      |     regenia.vaughan@gmail.com      |     44 Stonybrook Street       |        Mahopac         |   NY  |  10541   |
|      26     |     Theo    |    Reese    | (562) 215-2907 |        theo.reese@gmail.com        |    8755 W. Wild Horse St.      |       Long Beach       |   NY  |  11561   |
|      27     |    Santos   |   Valencia  |      None      |     santos.valencia@yahoo.com      |     7479 Carpenter Street      |       Sunnyside        |   NY  |  11104   |
|      28     |   Jeanice   |    Frost    |      None      |     jeanice.frost@hotmail.com      |         76 Devon Lane          |        Ossining        |   NY  |  10562   |
|      29     |   Syreeta   |  Hendricks  |      None      |     syreeta.hendricks@msn.com      |        193 Spruce Road         |        Mahopac         |   NY  |  10541   |
|      30     |    Jamaal   |    Albert   |      None      |      jamaal.albert@gmail.com       |     853 Stonybrook Street      |        Torrance        |   CA  |  90505   |
|      31     |  Williemae  |   Holloway  | (510) 246-8375 |     williemae.holloway@msn.com     |        69 Cypress St.          |        Oakland         |   CA  |  94603   |
|      32     |   Araceli   |    Golden   |      None      |       araceli.golden@msn.com       |       12 Ridgeview Ave.        |       Fullerton        |   CA  |  92831   |
|      33     |   Deloris   |    Burke    |      None      |     deloris.burke@hotmail.com      |      895 Edgemont Drive        | Palos Verdes Peninsula |   CA  |  90274   |
|      34     |   Brittney  |   Woodward  |      None      |     brittney.woodward@aol.com      |         960 River St.          |     East Northport     |   NY  |  11731   |
|      35     | Guillermina |    Noble    |      None      |     guillermina.noble@msn.com      |       6 Del Monte Lane         |     Baldwinsville      |   NY  |  13027   |
|      36     |   Bernita   |   Mcdaniel  |      None      |    bernita.mcdaniel@hotmail.com    |        2 Peg Shop Ave.         |       Liverpool        |   NY  |  13090   |
|      37     |    Melia    |    Brady    |      None      |       melia.brady@gmail.com        |        907 Shirley Rd.         |        Maspeth         |   NY  |  11378   |
|      38     |    Zelma    |   Browning  |      None      |       zelma.browning@aol.com       |       296 Second Street        |        Astoria         |   NY  |  11102   |
|      39     |   Janetta   |   Aguirre   | (717) 670-2634 |      janetta.aguirre@aol.com       |       214 Second Court         |       Lancaster        |   NY  |  14086   |
|      40     |    Ronna    |    Butler   |      None      |       ronna.butler@gmail.com       |      9438 Plymouth Court       |         Encino         |   CA  |  91316   |
|      41     |    Kathie   |   Freeman   |      None      |       kathie.freeman@msn.com       |        667 Temple Dr.          |       Queensbury       |   NY  |  12804   |
|      42     |   Tangela   |    Quinn    |      None      |       tangela.quinn@aol.com        |    4 S. Purple Finch Road      |     Richmond Hill      |   NY  |  11418   |
|      43     |   Mozelle   |    Carter   | (281) 489-9656 |       mozelle.carter@aol.com       |       895 Chestnut Ave.        |        Houston         |   TX  |  77016   |
|      44     |    Onita    |    Johns    |      None      |        onita.johns@msn.com         |      32 Glen Creek Lane        |         Elmont         |   NY  |  11003   |
|      45     |   Bennett   |  Armstrong  |      None      |     bennett.armstrong@aol.com      |       688 Walnut Street        |        Bethpage        |   NY  |  11714   |
|      46     |    Monika   |     Berg    |      None      |       monika.berg@gmail.com        |        369 Vernon Dr.          |         Encino         |   CA  |  91316   |
|      47     |  Bridgette  |    Guerra   |      None      |    bridgette.guerra@hotmail.com    |       9982 Manor Drive         |      San Lorenzo       |   CA  |  94580   |
|      48     |    Cesar    |   Jackson   |      None      |      cesar.jackson@gmail.com       |     8068 N. Griffin Ave.       |       Liverpool        |   NY  |  13090   |
|      49     |    Caroll   |     Hays    |      None      |       caroll.hays@yahoo.com        |       9381 Wrangler St.        |        Fairport        |   NY  |  14450   |
|      50     |  Cleotilde  |    Booth    |      None      |     cleotilde.booth@gmail.com      |         17 Corona St.          |       Sugar Land       |   TX  |  77478   |
|      51     |   Gertrud   |    Rhodes   |      None      |       gertrud.rhodes@aol.com       |    9961 Meadowbrook Street     |        Merrick         |   NY  |  11566   |
|      52     |      Tu     |   Ramirez   |      None      |       tu.ramirez@hotmail.com       |    24 W. Courtland Street      |     East Elmhurst      |   NY  |  11369   |
|      53     |  Saturnina  |    Garner   |      None      |     saturnina.garner@gmail.com     |      8538 Fairground St.       |        Glendora        |   CA  |  91740   |
|      54     |     Fran    |     Yang    |      None      |       fran.yang@hotmail.com        |         440 Pearl St.          |         Utica          |   NY  |  13501   |
|      55     |    Diana    |    Guerra   |      None      |      diana.guerra@hotmail.com      |        45 Chapel Ave.          |        Merrick         |   NY  |  11566   |
|      56     |    Lolita   |    Mosley   | (281) 363-3309 |     lolita.mosley@hotmail.com      |     376 S. High Ridge St.      |        Houston         |   TX  |  77016   |
|      57     |    Pamala   |    Henry    |      None      |        pamala.henry@aol.com        |      197 Bridgeton Ave.        |         Bronx          |   NY  |  10451   |
|      58     |    Damien   |    Dorsey   |      None      |      damien.dorsey@yahoo.com       |      161 Old York Street       |     Central Islip      |   NY  |  11722   |
|      59     |   Latasha   |   Stanley   |      None      |     latasha.stanley@gmail.com      |      8068 Fordham Drive        |    Rockville Centre    |   NY  |  11570   |
|      60     |     Neil    |    Mccall   |      None      |       neil.mccall@gmail.com        |       7476 Oakland Dr.         |       San Carlos       |   CA  |  94070   |
|      61     |   Elinore   |   Aguilar   |      None      |      elinore.aguilar@msn.com       |      9766 Rockcrest Ave.       |       San Angelo       |   TX  |  76901   |
|      62     |    Alica    |    Hunter   |      None      |      alica.hunter@hotmail.com      |       8 San Juan Drive         |     East Elmhurst      |   NY  |  11369   |
|      63     |   Tenisha   |    Lyons    |      None      |       tenisha.lyons@aol.com        |    78 E. Rock Creek Street     |       Amityville       |   NY  |  11701   |
|      64     |    Bobbie   |    Foster   |      None      |      bobbie.foster@yahoo.com       |      988 Pineknoll Ave.        |         Desoto         |   TX  |  75115   |
|      65     |   Kanesha   |     Vega    |      None      |       kanesha.vega@gmail.com       |      771 E. Oxford Drive       |          Rome          |   NY  |  13440   |
|      66     |    Lorrie   |    Becker   |      None      |      lorrie.becker@yahoo.com       |        19 North Court          |        Garland         |   TX  |  75043   |
|      67     |    Tommie   |    Melton   | (916) 802-2952 |      tommie.melton@gmail.com       |      8 West Old York St.       |       Sacramento       |   CA  |  95820   |
|      68     |    Jayne    |   Kirkland  |      None      |     jayne.kirkland@hotmail.com     |       7800 Second Lane         |        Rowlett         |   TX  |  75088   |
|      69     |   Katelin   |   Kennedy   |      None      |     katelin.kennedy@gmail.com      |        286 Myrtle Lane         |        Rocklin         |   CA  |  95677   |
|      70     |    Tomasa   |    Carson   |      None      |       tomasa.carson@aol.com        |        10 Clark Avenue         |     East Elmhurst      |   NY  |  11369   |
|      71     |    Takako   |    Casey    |      None      |        takako.casey@aol.com        |        7548 Court Lane         |         Bronx          |   NY  |  10451   |
|      72     |  Petronila  |    Norris   |      None      |      petronila.norris@aol.com      |    72 South Marshall Lane      |     South El Monte     |   CA  |  91733   |
|      73     |   Melanie   |    Hayes    |      None      |       melanie.hayes@msn.com        |         5 N. Hall Dr.          |       Liverpool        |   NY  |  13090   |
|      74     |  Georgeann  |    Waller   |      None      |     georgeann.waller@yahoo.com     |      9797 Bald Hill Ave.       |    North Tonawanda     |   NY  |  14120   |
|      75     |     Abby    |    Gamble   |      None      |        abby.gamble@aol.com         |         60 Myers Dr.           |       Amityville       |   NY  |  11701   |
|      76     |    Parker   |    Prince   |      None      |     parker.prince@hotmail.com      |   21 Sulphur Springs Drive     | Port Jefferson Station |   NY  |  11776   |
|      77     |     Keri    |   Bridges   |      None      |       keri.bridges@gmail.com       |      8504 Brickell Ave.        |       Richardson       |   TX  |  75080   |
|      78     |     Chi     |     Goff    |      None      |          chi.goff@aol.com          |    3 W. Glen Ridge Avenue      | Palos Verdes Peninsula |   CA  |  90274   |
|      79     |   Ashanti   |    Parks    |      None      |     ashanti.parks@hotmail.com      |       846 N. Helen St.         |        Baldwin         |   NY  |  11510   |
|      80     |    Sarai    |    Mckee    | (716) 912-8110 |        sarai.mckee@msn.com         |      641 Glenwood Avenue       |        Buffalo         |   NY  |  14215   |
|      81     |     Zina    |    Bonner   |      None      |      zina.bonner@hotmail.com       |        9312 8th Street         |      San Lorenzo       |   CA  |  94580   |
|      82     |    Lizzie   |    Joyner   |      None      |       lizzie.joyner@msn.com        |       8541 Roberts St.         |       Coachella        |   CA  |  92236   |
|      83     |    Tiesha   |    Daniel   |      None      |      tiesha.daniel@yahoo.com       |      6 West Bohemia Lane       |       Scarsdale        |   NY  |  10583   |
|      84     |    Armand   |  Whitehead  |      None      |    armand.whitehead@hotmail.com    |        639 Harvey St.          |      Lindenhurst       |   NY  |  11757   |
|      85     |   Teofila   |   Fischer   |      None      |      teofila.fischer@aol.com       |     1 West Brickyard St.       |   Huntington Station   |   NY  |  11746   |
|      86     |    Lissa    |    Vargas   |      None      |       lissa.vargas@yahoo.com       |       517 Victoria Ave.        |         Oswego         |   NY  |  13126   |
|      87     |     Yan     |   Mcgowan   |      None      |        yan.mcgowan@msn.com         |       8960 Newport Ave.        |         Duarte         |   CA  |  91010   |
|      88     |    Titus    |   Bullock   |      None      |      titus.bullock@gmail.com       |       29 Oxford Avenue         |         Hollis         |   NY  |  11423   |
|      89     |   Arvilla   |    Osborn   |      None      |      arvilla.osborn@gmail.com      |        60 Acacia Lane          |         Upland         |   CA  |  91784   |
|      90     |   Marjorie  |    Logan    |      None      |       marjorie.logan@msn.com       |       95 Grandrose St.         |    Franklin Square     |   NY  |  11010   |
|      91     |    Marvin   |   Mullins   | (619) 635-2027 |       marvin.mullins@aol.com       |      7489 Redwood Drive        |       San Diego        |   CA  |  92111   |
|      92     |     Tena    |     Cruz    |      None      |        tena.cruz@yahoo.com         |          1 South St.           |      Farmingdale       |   NY  |  11735   |
|      93     |   Corrina   |    Sawyer   | (248) 370-1364 |      corrina.sawyer@yahoo.com      |       95 Briarwood Lane        |          Troy          |   NY  |  12180   |
|      94     |    Sharyn   |   Hopkins   |      None      |     sharyn.hopkins@hotmail.com     |      4 South Temple Ave.       |     Baldwinsville      |   NY  |  13027   |
|      95     |   Letitia   |    Franco   |      None      |       letitia.franco@aol.com       |      607 Lakeview Drive        |    Saratoga Springs    |   NY  |  12866   |
|      96     |   Floretta  |   Higgins   |      None      |    floretta.higgins@hotmail.com    |         870 Lilac Dr.          |        Bayside         |   NY  |  11361   |
|      97     |   Louanne   |    Martin   |      None      |     louanne.martin@hotmail.com     |        1 Campfire Ave.         |       Yuba City        |   CA  |  95993   |
|      98     |    Violet   |  Valenzuela |      None      |     violet.valenzuela@msn.com      |       8668 Piper Street        |      Plattsburgh       |   NY  |  12901   |
|      99     |    Carie    |     Kidd    |      None      |        carie.kidd@yahoo.com        |     6 East Clinton Street      |         Monroe         |   NY  |  10950   |
|     100     |    Kellie   |    Franco   |      None      |      kellie.franco@yahoo.com       |     444 South Walnut Rd.       |        Commack         |   NY  |  11725   |
|     101     |   Nichelle  |    Howell   |      None      |      nichelle.howell@aol.com       |        7670 Forest St.         |       Scarsdale        |   NY  |  10583   |
|     102     |   Marisol   |   Goodman   |      None      |     marisol.goodman@gmail.com      |      864 East Cherry St.       |      Canandaigua       |   NY  |  14424   |
|     103     |    Sylvie   |  Wilkerson  |      None      |     sylvie.wilkerson@yahoo.com     |       750 Central Ave.         |        Syosset         |   NY  |  11791   |
|     104     |  Katharina  |    Bates    |      None      |     katharina.bates@gmail.com      |   54 South Greenview Drive     |        Campbell        |   CA  |  95008   |
|     105     |    Marget   |    Hodge    |      None      |        marget.hodge@msn.com        |        7199 Selby Lane         |       Woodhaven        |   NY  |  11421   |
|     106     |     Raul    |   Melendez  |      None      |     raul.melendez@hotmail.com      |      9772 Manhattan St.        |        Elmhurst        |   NY  |  11373   |
|     107     |    Cecil    |    Hopper   |      None      |       cecil.hopper@yahoo.com       |       471 Glenlake Ave.        |     Central Islip      |   NY  |  11722   |
|     108     |     Shae    |   Hickman   |      None      |      shae.hickman@hotmail.com      |      740 Pin Oak Street        |      Floral Park       |   NY  |  11001   |
|     109     |    Monica   |    Sears    | (408) 704-8863 |        monica.sears@aol.com        |       57 Glenholme St.         |        San Jose        |   CA  |  95127   |
|     110     |    Ollie    |  Zimmerman  | (657) 648-2863 |     ollie.zimmerman@yahoo.com      |          69 Wood Rd.           |        Anaheim         |   CA  |  92806   |
|     111     |    Shila    |    White    |      None      |        shila.white@msn.com         |      94 Lakeshore Street       |      Orchard Park      |   NY  |  14127   |

### Task 2: Retrieve customers who live in the city "New York".

In [38]:
%%sql SELECT * FROM customers
WHERE city = 'New York';

Running query in 'mysql+pymysql://root:***@localhost/bike_zeyad'

7 rows affected.

+-------------+------------+-----------+----------------+----------------------------+---------------------------+----------+-------+----------+
| customer_id | first_name | last_name |     phone      |           email            |           street          |   city   | state | zip_code |
+-------------+------------+-----------+----------------+----------------------------+---------------------------+----------+-------+----------+
|      16     |   Emmitt   |  Sanchez  | (212) 945-8823 | emmitt.sanchez@hotmail.com |   461 Squaw Creek Road    | New York |   NY  |  10002   |
|     178     |  Genoveva  |   Tyler   | (212) 152-6381 |  genoveva.tyler@gmail.com  |    8121 Windfall Ave.     | New York |   NY  |  10002   |
|     327     |   Sharie   |  Alvarez  | (212) 211-7621 |   sharie.alvarez@msn.com   | 987 West Leatherwood Dr.  | New York |   NY  |  10002   |
|     411     |  Octavia   |    Case   | (212) 171-1335 |    octavia.case@aol.com    |      40 Charles Road      | New York |   NY  |  10002   |
|     854     |   Phylis   |   Adkins  | (212) 325-9145 |   phylis.adkins@msn.com    |      7781 James Ave.      | New York |   NY  |  10002   |
|     927     | Guillermo  |    Hart   | (212) 652-7198 | guillermo.hart@hotmail.com |  81 Indian Summer Drive   | New York |   NY  |  10002   |
|     1016    |   Shenna   |   Benton  | (212) 578-2912 |   shenna.benton@msn.com    |   57 Shadow Brook Road    | New York |   NY  |  10002   |
+-------------+------------+-----------+----------------+----------------------------+---------------------------+----------+-------+----------+

### Task 3: Retrieve all products sorted by their price in descending order.

In [40]:
%%sql SELECT * FROM products
ORDER BY list_price DESC;

Running query in 'mysql+pymysql://root:***@localhost/bike_zeyad'

321 rows affected.

+------------+-------------------------------------------------------+----------+-------------+------------+------------+
| product_id |                      product_name                     | brand_id | category_id | model_year | list_price |
+------------+-------------------------------------------------------+----------+-------------+------------+------------+
|    155     |             Trek Domane SLR 9 Disc - 2018             |    9     |      7      |    2018    |  11999.99  |
|    149     |             Trek Domane SLR 8 Disc - 2018             |    9     |      7      |    2018    |  7499.99   |
|     51     |            Trek Silque SLR 8 Women's - 2017           |    9     |      7      |    2017    |  6499.99   |
|    169     |                Trek Emonda SLR 8 - 2018               |    9     |      7      |    2018    |  6499.99   |
|    157     |         Trek Domane SL Frameset Women's - 2018        |    9     |      7      |    2018    |  6499.99   |
|    156     |             Trek Domane SL Frameset - 2018            |    9     |      7      |    2018    |  6499.99   |
|     50     |            Trek Silque SLR 7 Women's - 2017           |    9     |      7      |    2017    |  5999.99   |
|    177     |             Trek Domane SLR 6 Disc - 2018             |    9     |      7      |    2018    |  5499.99   |
|    154     |         Trek Domane SLR 6 Disc Women's - 2018         |    9     |      7      |    2018    |  5499.99   |
|    148     |              Trek Domane SL 8 Disc - 2018             |    9     |      7      |    2018    |  5499.99   |
|     56     |             Trek Domane SLR 6 Disc - 2017             |    9     |      7      |    2017    |  5499.99   |
|     43     |           Trek Fuel EX 9.8 27.5 Plus - 2017           |    9     |      6      |    2017    |  5299.99   |
|     47     |                 Trek Remedy 9.8 - 2017                |    9     |      6      |    2017    |  5299.99   |
|    205     |             Trek Super Commuter+ 8S - 2018            |    9     |      5      |    2018    |  4999.99   |
|    203     |               Trek Powerfly 7 FS - 2018               |    9     |      5      |    2018    |  4999.99   |
|    140     |              Trek Remedy 9.8 27.5 - 2018              |    9     |      6      |    2018    |  4999.99   |
|     58     |                 Trek Madone 9.2 - 2017                |    9     |      7      |    2017    |  4999.99   |
|     40     |               Trek Fuel EX 9.8 29 - 2017              |    9     |      6      |    2017    |  4999.99   |
|    146     |                Trek Domane SLR 6 - 2018               |    9     |      7      |    2018    |  4999.99   |
|     61     |             Trek Powerfly 8 FS Plus - 2017            |    9     |      5      |    2017    |  4999.99   |
|    153     |            Trek Domane SL 7 Women's - 2018            |    9     |      7      |    2018    |  4999.99   |
|    186     |                 Trek CrossRip+ - 2018                 |    9     |      5      |    2018    |  4499.99   |
|    201     |               Trek Powerfly 5 FS - 2018               |    9     |      5      |    2018    |  4499.99   |
|    150     |                Trek Emonda SL 7 - 2018                |    9     |      7      |    2018    |  4499.99   |
|    160     |                Trek Emonda SLR 6 - 2018               |    9     |      7      |    2018    |  4499.99   |
|     7      |                Trek Slash 8 27.5 - 2016               |    9     |      6      |    2016    |  3999.99   |
|    207     |                Trek Boone 7 Disc - 2018               |    9     |      4      |    2018    |  3999.99   |
|    320     |              Trek Checkpoint SL 6 - 2019              |    9     |      7      |    2019    |  3799.99   |
|    204     |             Trek Super Commuter+ 7 - 2018             |    9     |      5      |    2018    |  3599.99   |
|     62     |                  Trek Boone 7 - 2017                  |    9     |      4      |    2017    |  3499.99   |
|    188     |               Trek XM700+ Lowstep - 2018              |    9     |      5      |    2018    |  3499.99   |
|    200     |                 Trek Powerfly 5 - 2018                |    9     |      5      |    2018    |  3499.99   |
|    202     |             Trek Powerfly 5 Women's - 2018            |    9     |      5      |    2018    |  3499.99   |
|    184     |              Trek Domane SL 6 Disc - 2018             |    9     |      7      |    2018    |  3499.99   |
|    194     |                   Trek XM700+ - 2018                  |    9     |      5      |    2018    |  3499.99   |
|     49     |                Trek Domane SL 6 - 2017                |    9     |      7      |    2017    |  3499.99   |
|     63     |          Trek Boone Race Shop Limited - 2017          |    9     |      4      |    2017    |  3499.99   |
|    206     |                Trek Boone 5 Disc - 2018               |    9     |      4      |    2018    |  3299.99   |
|     54     |          Trek Domane SL Disc Frameset - 2017          |    9     |      7      |    2017    |  3199.99   |
|    142     |              Trek Fuel EX 8 29 XT - 2018              |    9     |      6      |    2018    |  3199.99   |
|    115     |                Trek Fuel EX 8 29 - 2018               |    9     |      6      |    2018    |  3199.99   |
|    174     |          Trek Domane SLR Disc Frameset - 2018         |    9     |      7      |    2018    |  3199.99   |
|    175     |            Trek Domane SLR Frameset - 2018            |    9     |      7      |    2018    |  3199.99   |
|    171     |                Trek Domane SL 6 - 2018                |    9     |      7      |    2018    |  3199.99   |
|    321     |          Trek Checkpoint ALR Frameset - 2019          |    9     |      7      |    2019    |  3199.99   |
|    172     |          Trek Domane ALR Disc Frameset - 2018         |    9     |      7      |    2018    |  3199.99   |
|    173     |            Trek Domane ALR Frameset - 2018            |    9     |      7      |    2018    |  3199.99   |
|    176     |             Trek Madone 9 Frameset - 2018             |    9     |      7      |    2018    |  3199.99   |
|    162     |              Trek Emonda SL 6 Disc - 2018             |    9     |      7      |    2018    |  2999.99   |
|    139     |               Trek Remedy 7 27.5 - 2018               |    9     |      6      |    2018    |  2999.99   |
|    198     |           Electra Townie Commute Go! - 2018           |    1     |      5      |    2018    |  2999.99   |
|    199     |       Electra Townie Commute Go! Ladies' - 2018       |    1     |      5      |    2018    |  2999.99   |
|     9      |                  Trek Conduit+ - 2016                 |    9     |      5      |    2016    |  2999.99   |
|    251     |           Electra Townie Commute Go! - 2018           |    1     |      3      |    2018    |  2999.99   |
|    209     |              Trek Crockett 7 Disc - 2018              |    9     |      4      |    2018    |  2999.99   |
|    252     |       Electra Townie Commute Go! Ladies' - 2018       |    1     |      3      |    2018    |  2999.99   |
|     4      |                Trek Fuel EX 8 29 - 2016               |    9     |      6      |    2016    |  2899.99   |
|    185     |                  Trek Conduit+ - 2018                 |    9     |      5      |    2018    |  2799.99   |
|    189     |               Trek Lift+ Lowstep - 2018               |    9     |      5      |    2018    |  2799.99   |
|    190     |                Trek Dual Sport+ - 2018                |    9     |      5      |    2018    |  2799.99   |
|    191     |               Electra Loft Go! 8i - 2018              |    1     |      5      |    2018    |  2799.99   |
|    187     |                   Trek Neko+ - 2018                   |    9     |      5      |    2018    |  2799.99   |
|    319     |          Trek Checkpoint SL 5 Women's - 2019          |    9     |      7      |    2019    |  2799.99   |
|    193     |                   Trek Lift+ - 2018                   |    9     |      5      |    2018    |  2799.99   |
|     55     |                 Trek Domane S 6 - 2017                |    9     |      7      |    2017    |  2699.99   |
|    192     |           Electra Townie Go! 8i - 2017/2018           |    1     |      5      |    2018    |  2599.99   |
|    195     |          Electra Townie Go! 8i Ladies' - 2018         |    1     |      5      |    2018    |  2599.99   |
|    253     |          Electra Townie Go! 8i Ladies' - 2018         |    1     |      3      |    2018    |  2599.99   |
|    303     |           Electra Townie Go! 8i - 2017/2018           |    1     |      2      |    2018    |  2599.99   |
|    250     |           Electra Townie Go! 8i - 2017/2018           |    1     |      3      |    2018    |  2599.99   |
|     59     |              Trek Domane S 5 Disc - 2017              |    9     |      7      |    2017    |  2599.99   |
|    137     |               Heller Shagamaw GX1 - 2018              |    3     |      6      |    2018    |  2599.00   |
|    131     |             Heller Bloodhound Trail - 2018            |    3     |      6      |    2018    |  2599.00   |
|    122     |              Surly Troll Frameset - 2018              |    8     |      6      |    2018    |  2499.99   |
|    121     |             Surly Krampus Frameset - 2018             |    8     |      6      |    2018    |  2499.99   |
|    152     |          Trek Domane SL 5 Disc Women's - 2018         |    9     |      7      |    2018    |  2499.99   |
|     28     |       Surly Karate Monkey 27.5+ Frameset - 2017       |    8     |      6      |    2017    |  2499.99   |
|    165     |                    Trek 1120 - 2018                   |    9     |      7      |    2018    |  2499.99   |
|    182     |              Trek Domane SL 5 Disc - 2018             |    9     |      7      |    2018    |  2499.99   |
|    120     |                Trek Fuel EX 7 29 - 2018               |    9     |      6      |    2018    |  2499.99   |
|    159     |                Trek Emonda ALR 6 - 2018               |    9     |      7      |    2018    |  2299.99   |
|     42     |            Trek Fuel EX 5 27.5 Plus - 2017            |    9     |      6      |    2017    |  2299.99   |
|    196     |                   Trek Verve+ - 2018                  |    9     |      5      |    2018    |  2299.99   |
|    197     |               Trek Verve+ Lowstep - 2018              |    9     |      5      |    2018    |  2299.99   |
|    138     |               Trek Fuel EX 5 Plus - 2018              |    9     |      6      |    2018    |  2249.99   |
|    181     |                Trek Domane SL 5 - 2018                |    9     |      7      |    2018    |  2199.99   |
|    183     |            Trek Domane SL 5 Women's - 2018            |    9     |      7      |    2018    |  2199.99   |
|    317     |              Trek Checkpoint ALR 5 - 2019             |    9     |      7      |    2019    |  1999.99   |
|    318     |          Trek Checkpoint ALR 5 Women's - 2019         |    9     |      7      |    2019    |  1999.99   |
|     57     |                 Trek Emonda S 5 - 2017                |    9     |      7      |    2017    |  1999.99   |
|    161     |                    Surly ECR - 2018                   |    8     |      7      |    2018    |  1899.00   |
|    128     |                 Surly ECR 27.5 - 2018                 |    8     |      6      |    2018    |  1899.00   |
|    145     |             Trek Domane ALR 5 Disc - 2018             |    9     |      7      |    2018    |  1799.99   |
|     8      |         Trek Remedy 29 Carbon Frameset - 2016         |    9     |      6      |    2016    |  1799.99   |
|    208     |              Trek Crockett 5 Disc - 2018              |    9     |      4      |    2018    |  1799.99   |
|    147     |            Trek Domane ALR 5 Gravel - 2018            |    9     |      7      |    2018    |  1799.99   |
|    136     |                Trek Procaliber 6 - 2018               |    9     |      6      |    2018    |  1799.99   |
|    316     |          Trek Checkpoint ALR 4 Women's - 2019         |    9     |      7      |    2019    |  1699.99   |
|     11     |              Surly Straggler 650b - 2016              |    8     |      4      |    2016    |  1680.99   |
|     31     |                 Surly Wednesday - 2017                |    8     |      6      |    2017    |  1632.99   |
|    141     |                  Trek Stache 5 - 2018                 |    9     |      6      |    2018    |  1599.99   |
|     60     |            Sun Bicycles ElectroLite - 2017            |    7     |      5      |    2017    |  1559.99   |
|    151     |         Trek Domane ALR 4 Disc Women's - 2018         |    9     |      7      |    2018    |  1549.99   |
|    144     |             Trek Domane ALR 4 Disc - 2018             |    9     |      7      |    2018    |  1549.99   |
|     10     |                 Surly Straggler - 2016                |    8     |      4      |    2016    |  1549.00   |
|    164     |              Surly Straggler 650b - 2018              |    8     |      7      |    2018    |  1549.00   |
|    211     |              Surly Straggler 650b - 2018              |    8     |      4      |    2018    |  1549.00   |
|    168     |                 Surly Straggler - 2018                |    8     |      7      |    2018    |  1549.00   |
|    210     |                 Surly Straggler - 2018                |    8     |      4      |    2018    |  1549.00   |
|    134     |           Trek Remedy 27.5 C Frameset - 2018          |    9     |      6      |    2018    |  1499.99   |
|    133     |            Trek Procaliber Frameset - 2018            |    9     |      6      |    2018    |  1499.99   |
|     39     |                  Trek Stache 5 - 2017                 |    9     |      6      |    2017    |  1499.99   |
|    135     |             Trek X-Caliber Frameset - 2018            |    9     |      6      |    2018    |  1499.99   |
|     48     |                 Trek Emonda S 4 - 2017                |    9     |      7      |    2017    |  1499.99   |
|    132     |             Trek Procal AL Frameset - 2018            |    9     |      6      |    2018    |  1499.99   |
|    124     |                  Surly Krampus - 2018                 |    8     |      6      |    2018    |  1499.00   |
|    117     |               Trek Ticket S Frame - 2018              |    9     |      6      |    2018    |  1469.99   |
|     41     |                  Haro Shift R3 - 2017                 |    2     |      6      |    2017    |  1469.99   |
|     46     |                   Haro SR 1.3 - 2017                  |    2     |      6      |    2017    |  1409.99   |
|    163     |                 Surly Pack Rat - 2018                 |    8     |      7      |    2018    |  1349.00   |
|     5      |              Heller Shagamaw Frame - 2016             |    3     |      6      |    2016    |  1320.99   |
|    170     |                 Trek CrossRip 2 - 2018                |    9     |      7      |    2018    |  1299.99   |
|    258     |         Electra Amsterdam Royal 8i - 2017/2018        |    1     |      3      |    2018    |  1259.90   |
|    259     |        Electra Amsterdam Royal 8i Ladies - 2018       |    1     |      3      |    2018    |  1199.99   |
|     81     |      Electra Amsterdam Fashion 7i Ladies' - 2017      |    1     |      3      |    2017    |  1099.99   |
|    143     |                Trek Domane ALR 3 - 2018               |    9     |      7      |    2018    |  1099.99   |
|    123     |           Trek Farley Carbon Frameset - 2018          |    9     |      6      |    2018    |   999.99   |
|     27     |            Surly Big Dummy Frameset - 2017            |    8     |      6      |    2017    |   999.99   |
|     29     |                Trek X-Caliber 8 - 2017                |    9     |      6      |    2017    |   999.99   |
|     30     |         Surly Ice Cream Truck Frameset - 2017         |    8     |      6      |    2017    |   999.99   |
|    118     |                Trek X-Caliber 8 - 2018                |    9     |      6      |    2018    |   999.99   |
|     3      |            Surly Wednesday Frameset - 2016            |    8     |      6      |    2016    |   999.99   |
|    225     |          Electra Delivery 3i - 2016/2017/2018         |    1     |      3      |    2018    |   959.99   |
|    158     |                 Trek CrossRip 1 - 2018                |    9     |      7      |    2018    |   959.99   |
|    179     |                Trek Domane AL 3 - 2018                |    9     |      7      |    2018    |   919.99   |
|    129     |                Trek X-Caliber 7 - 2018                |    9     |      6      |    2018    |   919.99   |
|    130     |           Trek Stache Carbon Frameset - 2018          |    9     |      6      |    2018    |   919.99   |
|    180     |            Trek Domane AL 3 Women's - 2018            |    9     |      7      |    2018    |   919.99   |
|    217     |              Electra Straight 8 3i - 2018             |    1     |      3      |    2018    |   909.99   |
|    309     |           Electra Townie Commute 27D - 2018           |    1     |      2      |    2018    |   899.99   |
|    306     |    Electra Townie Balloon 7i EQ Ladies' - 2017/2018   |    1     |      2      |    2018    |   899.99   |
|    301     |          Electra Townie Balloon 7i EQ - 2018          |    1     |      2      |    2018    |   899.99   |
|    261     |          Electra Townie Balloon 7i EQ - 2018          |    1     |      3      |    2018    |   899.99   |
|    255     |    Electra Townie Balloon 7i EQ Ladies' - 2017/2018   |    1     |      3      |    2018    |   899.99   |
|    256     |           Electra Townie Commute 27D - 2018           |    1     |      3      |    2018    |   899.99   |
|    257     |    Electra Amsterdam Fashion 3i Ladies' - 2017/2018   |    1     |      3      |    2018    |   899.99   |
|    310     |        Electra Townie Commute 27D Ladies - 2018       |    1     |      2      |    2018    |   899.99   |
|    234     |          Electra Daydreamer 3i Ladies' - 2018         |    1     |      3      |    2018    |   899.99   |
|    235     |             Electra Koa 3i Ladies' - 2018             |    1     |      3      |    2018    |   899.99   |
|    216     |              Electra Super Moto 8i - 2018             |    1     |      3      |    2018    |   899.99   |
|    214     |             Electra Tiger Shark 3i - 2018             |    1     |      3      |    2018    |   899.99   |
|    240     |        Electra Townie Commute 27D Ladies - 2018       |    1     |      3      |    2018    |   899.99   |
|     52     |                Surly Steamroller - 2017               |    8     |      7      |    2017    |   875.99   |
|     45     |                   Haro SR 1.2 - 2017                  |    2     |      6      |    2017    |   869.99   |
|    237     |                Electra Relic 3i - 2018                |    1     |      3      |    2018    |   849.99   |
|     36     |              Surly Troll Frameset - 2017              |    8     |      6      |    2017    |   832.99   |
|     35     |             Sun Bicycles Spider 3i - 2017             |    7     |      6      |    2017    |   832.99   |
|    260     |      Electra Townie Balloon 3i EQ Ladies' - 2018      |    1     |      3      |    2018    |   799.99   |
|    300     |      Electra Townie Balloon 3i EQ Ladies' - 2018      |    1     |      2      |    2018    |   799.99   |
|     77     |          Electra Glam Punk 3i Ladies' - 2017          |    1     |      3      |    2017    |   799.99   |

### Task 4: Find Orders by Status

#### Task 4.1: Retrieve all orders with status "Completed".

In [42]:
%%sql SELECT * FROM orders
WHERE order_status = 4;

Running query in 'mysql+pymysql://root:***@localhost/bike_zeyad'

1445 rows affected.

+----------+-------------+--------------+------------+---------------+--------------+----------+----------+
| order_id | customer_id | order_status | order_date | required_date | shipped_date | store_id | staff_id |
+----------+-------------+--------------+------------+---------------+--------------+----------+----------+
|    1     |     259     |      4       | 2016-01-01 |   2016-01-03  |  2016-01-03  |    1     |    2     |
|    2     |     1212    |      4       | 2016-01-01 |   2016-01-04  |  2016-01-03  |    2     |    6     |
|    3     |     523     |      4       | 2016-01-02 |   2016-01-05  |  2016-01-03  |    2     |    7     |
|    4     |     175     |      4       | 2016-01-03 |   2016-01-04  |  2016-01-05  |    1     |    3     |
|    5     |     1324    |      4       | 2016-01-03 |   2016-01-06  |  2016-01-06  |    2     |    6     |
|    6     |      94     |      4       | 2016-01-04 |   2016-01-07  |  2016-01-05  |    2     |    6     |
|    7     |     324     |      4       | 2016-01-04 |   2016-01-07  |  2016-01-05  |    2     |    6     |
|    8     |     1204    |      4       | 2016-01-04 |   2016-01-05  |  2016-01-05  |    2     |    7     |
|    9     |      60     |      4       | 2016-01-05 |   2016-01-08  |  2016-01-08  |    1     |    2     |
|    10    |     442     |      4       | 2016-01-05 |   2016-01-06  |  2016-01-06  |    2     |    6     |
|    11    |     1326    |      4       | 2016-01-05 |   2016-01-08  |  2016-01-07  |    2     |    7     |
|    12    |      91     |      4       | 2016-01-06 |   2016-01-08  |  2016-01-09  |    1     |    2     |
|    13    |     873     |      4       | 2016-01-08 |   2016-01-11  |  2016-01-11  |    2     |    6     |
|    14    |     258     |      4       | 2016-01-09 |   2016-01-11  |  2016-01-12  |    1     |    3     |
|    15    |     450     |      4       | 2016-01-09 |   2016-01-10  |  2016-01-12  |    2     |    7     |
|    16    |     552     |      4       | 2016-01-12 |   2016-01-15  |  2016-01-15  |    1     |    3     |
|    17    |     1175    |      4       | 2016-01-12 |   2016-01-14  |  2016-01-14  |    1     |    3     |
|    18    |     541     |      4       | 2016-01-14 |   2016-01-17  |  2016-01-15  |    1     |    3     |
|    19    |     696     |      4       | 2016-01-14 |   2016-01-17  |  2016-01-16  |    1     |    2     |
|    20    |     923     |      4       | 2016-01-14 |   2016-01-16  |  2016-01-17  |    1     |    2     |
|    21    |     1250    |      4       | 2016-01-15 |   2016-01-16  |  2016-01-18  |    2     |    6     |
|    22    |     1035    |      4       | 2016-01-16 |   2016-01-18  |  2016-01-17  |    1     |    2     |
|    23    |     1149    |      4       | 2016-01-16 |   2016-01-19  |  2016-01-19  |    1     |    2     |
|    24    |     636     |      4       | 2016-01-18 |   2016-01-20  |  2016-01-19  |    2     |    7     |
|    25    |     657     |      4       | 2016-01-18 |   2016-01-21  |  2016-01-21  |    2     |    6     |
|    26    |     1280    |      4       | 2016-01-18 |   2016-01-21  |  2016-01-19  |    2     |    7     |
|    27    |      57     |      4       | 2016-01-19 |   2016-01-21  |  2016-01-20  |    2     |    7     |
|    28    |     252     |      4       | 2016-01-19 |   2016-01-20  |  2016-01-21  |    2     |    6     |
|    29    |     437     |      4       | 2016-01-20 |   2016-01-22  |  2016-01-21  |    2     |    6     |
|    30    |     1348    |      4       | 2016-01-20 |   2016-01-21  |  2016-01-21  |    2     |    6     |
|    31    |     1238    |      4       | 2016-01-20 |   2016-01-22  |  2016-01-22  |    3     |    8     |
|    32    |     1259    |      4       | 2016-01-21 |   2016-01-24  |  2016-01-22  |    1     |    3     |
|    33    |     236     |      4       | 2016-01-21 |   2016-01-22  |  2016-01-22  |    2     |    6     |
|    34    |      80     |      4       | 2016-01-22 |   2016-01-25  |  2016-01-23  |    2     |    6     |
|    35    |     813     |      4       | 2016-01-22 |   2016-01-25  |  2016-01-24  |    2     |    7     |
|    36    |     1321    |      4       | 2016-01-23 |   2016-01-24  |  2016-01-24  |    2     |    6     |
|    37    |     164     |      4       | 2016-01-25 |   2016-01-28  |  2016-01-26  |    2     |    6     |
|    38    |     583     |      4       | 2016-01-25 |   2016-01-27  |  2016-01-26  |    2     |    7     |
|    39    |     1296    |      4       | 2016-01-25 |   2016-01-26  |  2016-01-26  |    2     |    7     |
|    40    |     348     |      4       | 2016-01-27 |   2016-01-28  |  2016-01-29  |    1     |    3     |
|    41    |     979     |      4       | 2016-01-27 |   2016-01-30  |  2016-01-29  |    2     |    6     |
|    42    |     1095    |      4       | 2016-01-27 |   2016-01-28  |  2016-01-30  |    2     |    7     |
|    43    |     1434    |      4       | 2016-01-27 |   2016-01-28  |  2016-01-30  |    2     |    7     |
|    44    |     861     |      4       | 2016-01-28 |   2016-01-31  |  2016-01-30  |    2     |    7     |
|    45    |     1220    |      4       | 2016-01-28 |   2016-01-31  |  2016-01-31  |    2     |    7     |
|    46    |     746     |      4       | 2016-01-29 |   2016-01-31  |  2016-01-31  |    2     |    7     |
|    47    |     1234    |      4       | 2016-01-29 |   2016-01-30  |  2016-01-31  |    2     |    7     |
|    48    |     1012    |      4       | 2016-01-30 |   2016-02-01  |  2016-02-02  |    2     |    7     |
|    49    |     608     |      4       | 2016-01-31 |   2016-02-01  |  2016-02-02  |    2     |    6     |
|    50    |     872     |      4       | 2016-01-31 |   2016-02-03  |  2016-02-02  |    3     |    8     |
|    51    |     1047    |      4       | 2016-02-01 |   2016-02-02  |  2016-02-03  |    2     |    7     |
|    52    |     767     |      4       | 2016-02-03 |   2016-02-04  |  2016-02-05  |    1     |    2     |
|    53    |     965     |      4       | 2016-02-03 |   2016-02-04  |  2016-02-05  |    2     |    6     |
|    54    |     535     |      4       | 2016-02-04 |   2016-02-07  |  2016-02-07  |    2     |    7     |
|    55    |     1173    |      4       | 2016-02-04 |   2016-02-07  |  2016-02-06  |    2     |    6     |
|    56    |     1241    |      4       | 2016-02-04 |   2016-02-06  |  2016-02-07  |    2     |    6     |
|    57    |     1305    |      4       | 2016-02-04 |   2016-02-06  |  2016-02-06  |    2     |    7     |
|    58    |     504     |      4       | 2016-02-05 |   2016-02-07  |  2016-02-07  |    2     |    6     |
|    59    |     563     |      4       | 2016-02-05 |   2016-02-07  |  2016-02-06  |    2     |    7     |
|    60    |     151     |      4       | 2016-02-06 |   2016-02-08  |  2016-02-07  |    1     |    3     |
|    61    |     277     |      4       | 2016-02-06 |   2016-02-09  |  2016-02-09  |    2     |    7     |
|    62    |     208     |      4       | 2016-02-07 |   2016-02-10  |  2016-02-10  |    1     |    2     |
|    63    |     1075    |      4       | 2016-02-07 |   2016-02-09  |  2016-02-09  |    2     |    7     |
|    64    |     1185    |      4       | 2016-02-07 |   2016-02-08  |  2016-02-09  |    2     |    6     |
|    65    |     996     |      4       | 2016-02-08 |   2016-02-09  |  2016-02-11  |    2     |    6     |
|    66    |     1253    |      4       | 2016-02-09 |   2016-02-12  |  2016-02-12  |    2     |    7     |
|    67    |     526     |      4       | 2016-02-09 |   2016-02-11  |  2016-02-10  |    3     |    8     |
|    68    |     381     |      4       | 2016-02-10 |   2016-02-11  |  2016-02-13  |    2     |    6     |
|    69    |     1413    |      4       | 2016-02-10 |   2016-02-12  |  2016-02-11  |    2     |    7     |
|    71    |     797     |      4       | 2016-02-11 |   2016-02-14  |  2016-02-12  |    2     |    7     |
|    72    |     1386    |      4       | 2016-02-12 |   2016-02-15  |  2016-02-13  |    1     |    2     |
|    73    |     612     |      4       | 2016-02-12 |   2016-02-15  |  2016-02-14  |    2     |    7     |
|    74    |     264     |      4       | 2016-02-13 |   2016-02-15  |  2016-02-15  |    2     |    7     |
|    75    |     587     |      4       | 2016-02-14 |   2016-02-15  |  2016-02-17  |    2     |    6     |
|    77    |     385     |      4       | 2016-02-16 |   2016-02-19  |  2016-02-19  |    1     |    2     |
|    78    |     1182    |      4       | 2016-02-16 |   2016-02-18  |  2016-02-19  |    2     |    7     |
|    79    |     529     |      4       | 2016-02-17 |   2016-02-20  |  2016-02-20  |    1     |    3     |
|    80    |     397     |      4       | 2016-02-17 |   2016-02-20  |  2016-02-19  |    2     |    6     |
|    81    |     521     |      4       | 2016-02-17 |   2016-02-19  |  2016-02-18  |    2     |    6     |
|    82    |     1223    |      4       | 2016-02-18 |   2016-02-21  |  2016-02-20  |    2     |    6     |
|    83    |     393     |      4       | 2016-02-19 |   2016-02-20  |  2016-02-20  |    1     |    3     |
|    84    |     317     |      4       | 2016-02-20 |   2016-02-22  |  2016-02-21  |    2     |    7     |
|    85    |     1174    |      4       | 2016-02-20 |   2016-02-23  |  2016-02-21  |    2     |    7     |
|    86    |     276     |      4       | 2016-02-21 |   2016-02-22  |  2016-02-23  |    2     |    7     |
|    87    |     516     |      4       | 2016-02-21 |   2016-02-22  |  2016-02-23  |    2     |    6     |
|    88    |     1069    |      4       | 2016-02-21 |   2016-02-22  |  2016-02-23  |    2     |    6     |
|    89    |     668     |      4       | 2016-02-21 |   2016-02-24  |  2016-02-24  |    3     |    8     |
|    90    |     414     |      4       | 2016-02-23 |   2016-02-25  |  2016-02-24  |    2     |    7     |
|    91    |     648     |      4       | 2016-02-25 |   2016-02-27  |  2016-02-28  |    1     |    2     |
|    92    |     1309    |      4       | 2016-02-25 |   2016-02-28  |  2016-02-28  |    2     |    7     |
|    93    |     1328    |      4       | 2016-02-26 |   2016-02-28  |  2016-02-27  |    1     |    3     |
|    94    |     929     |      4       | 2016-02-27 |   2016-02-28  |  2016-02-29  |    1     |    2     |
|    95    |     218     |      4       | 2016-02-27 |   2016-02-29  |  2016-02-28  |    2     |    7     |
|    96    |     1094    |      4       | 2016-02-27 |   2016-02-29  |  2016-02-28  |    2     |    7     |
|    97    |     204     |      4       | 2016-02-28 |   2016-02-29  |  2016-03-01  |    2     |    7     |
|    98    |     1194    |      4       | 2016-02-28 |   2016-02-29  |  2016-02-29  |    2     |    6     |
|    99    |     1165    |      4       | 2016-02-29 |   2016-03-01  |  2016-03-03  |    3     |    9     |
|   100    |     1237    |      4       | 2016-03-01 |   2016-03-04  |  2016-03-03  |    2     |    7     |
|   101    |     271     |      4       | 2016-03-01 |   2016-03-04  |  2016-03-04  |    3     |    8     |
|   102    |     336     |      4       | 2016-03-02 |   2016-03-05  |  2016-03-03  |    2     |    7     |
|   103    |     991     |      4       | 2016-03-03 |   2016-03-06  |  2016-03-05  |    1     |    2     |
|   104    |      7      |      4       | 2016-03-03 |   2016-03-05  |  2016-03-05  |    2     |    7     |
|   105    |     306     |      4       | 2016-03-03 |   2016-03-05  |  2016-03-04  |    2     |    7     |
|   106    |     422     |      4       | 2016-03-04 |   2016-03-05  |  2016-03-05  |    3     |    9     |
|   107    |     633     |      4       | 2016-03-06 |   2016-03-09  |  2016-03-09  |    1     |    2     |
|   108    |      12     |      4       | 2016-03-06 |   2016-03-09  |  2016-03-07  |    2     |    6     |
|   109    |     1255    |      4       | 2016-03-06 |   2016-03-09  |  2016-03-09  |    2     |    6     |
|   110    |     677     |      4       | 2016-03-06 |   2016-03-08  |  2016-03-09  |    3     |    9     |
|   111    |     630     |      4       | 2016-03-07 |   2016-03-10  |  2016-03-10  |    2     |    6     |
|   112    |     469     |      4       | 2016-03-08 |   2016-03-11  |  2016-03-10  |    2     |    6     |
|   113    |     1078    |      4       | 2016-03-08 |   2016-03-11  |  2016-03-11  |    2     |    6     |
|   114    |     1431    |      4       | 2016-03-08 |   2016-03-10  |  2016-03-11  |    2     |    7     |
|   115    |     1369    |      4       | 2016-03-09 |   2016-03-11  |  2016-03-11  |    2     |    7     |
|   116    |     471     |      4       | 2016-03-10 |   2016-03-11  |  2016-03-11  |    2     |    7     |
|   117    |     740     |      4       | 2016-03-10 |   2016-03-13  |  2016-03-11  |    2     |    6     |
|   118    |     577     |      4       | 2016-03-12 |   2016-03-14  |  2016-03-13  |    1     |    2     |
|   119    |     925     |      4       | 2016-03-12 |   2016-03-14  |  2016-03-14  |    2     |    7     |
|   120    |     327     |      4       | 2016-03-14 |   2016-03-15  |  2016-03-17  |    2     |    7     |
|   121    |     755     |      4       | 2016-03-14 |   2016-03-15  |  2016-03-16  |    2     |    6     |
|   122    |     786     |      4       | 2016-03-14 |   2016-03-16  |  2016-03-15  |    2     |    6     |
|   123    |     766     |      4       | 2016-03-15 |   2016-03-18  |  2016-03-17  |    2     |    6     |
|   124    |     403     |      4       | 2016-03-16 |   2016-03-18  |  2016-03-17  |    1     |    3     |
|   125    |     685     |      4       | 2016-03-16 |   2016-03-19  |  2016-03-17  |    2     |    6     |
|   126    |     1365    |      4       | 2016-03-16 |   2016-03-18  |  2016-03-18  |    2     |    7     |
|   127    |     484     |      4       | 2016-03-17 |   2016-03-18  |  2016-03-19  |    3     |    8     |
|   128    |      86     |      4       | 2016-03-18 |   2016-03-20  |  2016-03-21  |    2     |    6     |
|   129    |      84     |      4       | 2016-03-19 |   2016-03-21  |  2016-03-21  |    2     |    7     |
|   130    |     1049    |      4       | 2016-03-19 |   2016-03-22  |  2016-03-20  |    2     |    6     |
|   131    |     316     |      4       | 2016-03-19 |   2016-03-22  |  2016-03-20  |    3     |    8     |
|   132    |      46     |      4       | 2016-03-20 |   2016-03-22  |  2016-03-23  |    1     |    3     |
|   133    |     409     |      4       | 2016-03-20 |   2016-03-22  |  2016-03-21  |    2     |    7     |
|   134    |     679     |      4       | 2016-03-20 |   2016-03-21  |  2016-03-21  |    2     |    7     |
|   135    |     1354    |      4       | 2016-03-21 |   2016-03-23  |  2016-03-23  |    2     |    7     |
|   136    |     1192    |      4       | 2016-03-21 |   2016-03-24  |  2016-03-23  |    3     |    8     |
|   137    |     370     |      4       | 2016-03-23 |   2016-03-26  |  2016-03-25  |    2     |    7     |
|   138    |     438     |      4       | 2016-03-23 |   2016-03-24  |  2016-03-25  |    2     |    7     |
|   139    |     710     |      4       | 2016-03-23 |   2016-03-24  |  2016-03-26  |    2     |    7     |
|   140    |     1264    |      4       | 2016-03-23 |   2016-03-26  |  2016-03-26  |    2     |    7     |
|   141    |     557     |      4       | 2016-03-25 |   2016-03-27  |  2016-03-26  |    2     |    7     |
|   142    |     170     |      4       | 2016-03-26 |   2016-03-27  |  2016-03-27  |    1     |    3     |
|   143    |     693     |      4       | 2016-03-26 |   2016-03-28  |  2016-03-28  |    2     |    7     |
|   144    |     1124    |      4       | 2016-03-26 |   2016-03-29  |  2016-03-29  |    2     |    7     |
|   145    |     366     |      4       | 2016-03-27 |   2016-03-29  |  2016-03-30  |    2     |    6     |
|   146    |     288     |      4       | 2016-03-28 |   2016-03-30  |  2016-03-30  |    1     |    3     |
|   147    |      55     |      4       | 2016-03-28 |   2016-03-31  |  2016-03-31  |    2     |    7     |
|   148    |     714     |      4       | 2016-03-28 |   2016-03-30  |  2016-03-30  |    2     |    6     |
|   149    |     763     |      4       | 2016-03-28 |   2016-03-30  |  2016-03-29  |    2     |    6     |
|   150    |     332     |      4       | 2016-03-29 |   2016-03-31  |  2016-04-01  |    1     |    2     |
|   151    |     926     |      4       | 2016-03-29 |   2016-04-01  |  2016-03-31  |    1     |    2     |
|   152    |      76     |      4       | 2016-03-29 |   2016-03-30  |  2016-03-30  |    2     |    6     |
|   153    |     498     |      4       | 2016-03-30 |   2016-04-02  |  2016-04-01  |    2     |    6     |
|   154    |     1286    |      4       | 2016-03-31 |   2016-04-01  |  2016-04-01  |    1     |    2     |
|   155    |     371     |      4       | 2016-04-02 |   2016-04-03  |  2016-04-04  |    2     |    6     |
|   156    |     357     |      4       | 2016-04-03 |   2016-04-06  |  2016-04-05  |    1     |    3     |
|   157    |      43     |      4       | 2016-04-03 |   2016-04-06  |  2016-04-06  |    3     |    8     |
|   159    |      32     |      4       | 2016-04-04 |   2016-04-06  |  2016-04-06  |    1     |    2     |
|   160    |     205     |      4       | 2016-04-04 |   2016-04-06  |  2016-04-06  |    2     |    7     |
|   161    |     251     |      4       | 2016-04-04 |   2016-04-07  |  2016-04-05  |    2     |    7     |
|   162    |      31     |      4       | 2016-04-06 |   2016-04-08  |  2016-04-07  |    1     |    3     |
|   163    |     1325    |      4       | 2016-04-06 |   2016-04-07  |  2016-04-07  |    2     |    7     |
|   164    |     610     |      4       | 2016-04-07 |   2016-04-08  |  2016-04-09  |    2     |    7     |
|   165    |     574     |      4       | 2016-04-08 |   2016-04-10  |  2016-04-10  |    1     |    3     |
|   166    |     338     |      4       | 2016-04-08 |   2016-04-11  |  2016-04-11  |    2     |    6     |
|   167    |     1034    |      4       | 2016-04-08 |   2016-04-09  |  2016-04-11  |    2     |    7     |
|   168    |     1147    |      4       | 2016-04-09 |   2016-04-12  |  2016-04-11  |    1     |    3     |
|   169    |      99     |      4       | 2016-04-10 |   2016-04-11  |  2016-04-11  |    2     |    7     |
|   170    |     1200    |      4       | 2016-04-10 |   2016-04-11  |  2016-04-13  |    2     |    7     |
|   171    |     237     |      4       | 2016-04-11 |   2016-04-14  |  2016-04-14  |    1     |    3     |
|   172    |     1079    |      4       | 2016-04-11 |   2016-04-12  |  2016-04-14  |    2     |    7     |
|   173    |     117     |      4       | 2016-04-11 |   2016-04-14  |  2016-04-13  |    3     |    8     |
|   174    |     1361    |      4       | 2016-04-12 |   2016-04-13  |  2016-04-15  |    2     |    7     |
|   175    |     951     |      4       | 2016-04-13 |   2016-04-14  |  2016-04-14  |    2     |    6     |
|   176    |     643     |      4       | 2016-04-15 |   2016-04-16  |  2016-04-17  |    2     |    7     |
|   177    |     121     |      4       | 2016-04-16 |   2016-04-19  |  2016-04-19  |    1     |    2     |
|   178    |     756     |      4       | 2016-04-16 |   2016-04-17  |  2016-04-18  |    2     |    6     |
|   179    |     616     |      4       | 2016-04-17 |   2016-04-19  |  2016-04-19  |    2     |    6     |
|   180    |     918     |      4       | 2016-04-17 |   2016-04-20  |  2016-04-19  |    2     |    7     |
|   181    |     459     |      4       | 2016-04-18 |   2016-04-20  |  2016-04-20  |    1     |    3     |
|   182    |     854     |      4       | 2016-04-18 |   2016-04-19  |  2016-04-20  |    2     |    6     |
|   183    |      22     |      4       | 2016-04-19 |   2016-04-20  |  2016-04-20  |    2     |    7     |
|   184    |     134     |      4       | 2016-04-19 |   2016-04-21  |  2016-04-22  |    2     |    7     |
|   186    |     1127    |      4       | 2016-04-21 |   2016-04-22  |  2016-04-24  |    2     |    6     |

#### Task 4.1: Retrieve count of orders with status "Rejected".

In [44]:
%%sql SELECT * FROM orders
WHERE order_status = 3;

Running query in 'mysql+pymysql://root:***@localhost/bike_zeyad'

45 rows affected.

+----------+-------------+--------------+------------+---------------+--------------+----------+----------+
| order_id | customer_id | order_status | order_date | required_date | shipped_date | store_id | staff_id |
+----------+-------------+--------------+------------+---------------+--------------+----------+----------+
|    70    |      50     |      3       | 2016-02-11 |   2016-02-11  |     None     |    3     |    9     |
|    76    |      9      |      3       | 2016-02-16 |   2016-02-16  |     None     |    2     |    6     |
|   158    |     117     |      3       | 2016-04-04 |   2016-04-04  |     None     |    3     |    9     |
|   185    |      24     |      3       | 2016-04-20 |   2016-04-20  |     None     |    1     |    2     |
|   239    |      13     |      3       | 2016-05-27 |   2016-05-27  |     None     |    3     |    9     |
|   246    |      17     |      3       | 2016-05-30 |   2016-05-30  |     None     |    2     |    6     |
|   264    |      5      |      3       | 2016-06-10 |   2016-06-10  |     None     |    1     |    3     |
|   349    |      30     |      3       | 2016-08-03 |   2016-08-03  |     None     |    1     |    3     |
|   350    |      31     |      3       | 2016-08-03 |   2016-08-03  |     None     |    1     |    3     |
|   357    |      14     |      3       | 2016-08-05 |   2016-08-05  |     None     |    3     |    8     |
|   391    |      61     |      3       | 2016-08-23 |   2016-08-23  |     None     |    3     |    9     |
|   407    |      77     |      3       | 2016-09-01 |   2016-09-01  |     None     |    3     |    8     |
|   549    |      64     |      3       | 2016-11-12 |   2016-11-12  |     None     |    3     |    9     |
|   582    |      32     |      3       | 2016-12-04 |   2016-12-04  |     None     |    1     |    2     |
|   598    |      40     |      3       | 2016-12-09 |   2016-12-09  |     None     |    1     |    3     |
|   692    |      2      |      3       | 2017-02-05 |   2017-02-05  |     None     |    1     |    3     |
|   715    |      12     |      3       | 2017-02-15 |   2017-02-15  |     None     |    2     |    6     |
|   735    |      20     |      3       | 2017-02-27 |   2017-02-27  |     None     |    3     |    9     |
|   778    |      56     |      3       | 2017-03-15 |   2017-03-15  |     None     |    3     |    9     |
|   810    |     153     |      3       | 2017-04-01 |   2017-04-01  |     None     |    3     |    8     |
|   885    |      66     |      3       | 2017-05-13 |   2017-05-13  |     None     |    3     |    8     |
|   924    |      68     |      3       | 2017-06-02 |   2017-06-02  |     None     |    3     |    8     |
|   935    |      43     |      3       | 2017-06-10 |   2017-06-10  |     None     |    3     |    8     |
|   1010   |      8      |      3       | 2017-07-18 |   2017-07-18  |     None     |    2     |    7     |
|   1020   |      16     |      3       | 2017-07-23 |   2017-07-23  |     None     |    2     |    6     |
|   1047   |     116     |      3       | 2017-08-08 |   2017-08-08  |     None     |    3     |    8     |
|   1072   |      47     |      3       | 2017-08-18 |   2017-08-18  |     None     |    1     |    3     |
|   1074   |      11     |      3       | 2017-08-19 |   2017-08-19  |     None     |    2     |    6     |
|   1089   |      46     |      3       | 2017-08-23 |   2017-08-23  |     None     |    1     |    2     |
|   1177   |      21     |      3       | 2017-10-12 |   2017-10-12  |     None     |    3     |    9     |
|   1234   |      19     |      3       | 2017-11-07 |   2017-11-07  |     None     |    2     |    6     |
|   1259   |      4      |      3       | 2017-11-21 |   2017-11-21  |     None     |    2     |    7     |
|   1407   |      18     |      3       | 2018-02-26 |   2018-02-26  |     None     |    2     |    6     |
|   1604   |      7      |      3       | 2018-06-17 |   2018-06-17  |     None     |    2     |    7     |
|   1605   |     123     |      3       | 2018-07-01 |   2018-07-01  |     None     |    3     |    8     |
|   1606   |     119     |      3       | 2018-07-10 |   2018-07-10  |     None     |    3     |    8     |
|   1607   |      33     |      3       | 2018-07-11 |   2018-07-11  |     None     |    1     |    2     |
|   1608   |      53     |      3       | 2018-07-12 |   2018-07-12  |     None     |    1     |    2     |
|   1609   |      10     |      3       | 2018-08-23 |   2018-08-23  |     None     |    2     |    7     |
|   1610   |      15     |      3       | 2018-08-25 |   2018-08-25  |     None     |    2     |    7     |
|   1611   |      6      |      3       | 2018-09-06 |   2018-09-06  |     None     |    2     |    7     |
|   1612   |      3      |      3       | 2018-10-21 |   2018-10-21  |     None     |    1     |    3     |
|   1613   |      1      |      3       | 2018-11-18 |   2018-11-18  |     None     |    2     |    6     |
|   1614   |     135     |      3       | 2018-11-28 |   2018-11-28  |     None     |    3     |    8     |
|   1615   |     136     |      3       | 2018-12-28 |   2018-12-28  |     None     |    3     |    8     |
+----------+-------------+--------------+------------+---------------+--------------+----------+----------+

### Task 5: Count how many customers exist in the customers table.

In [46]:
%%sql 
SELECT COUNT(*) 
AS TotalCustomers FROM customers;

Running query in 'mysql+pymysql://root:***@localhost/bike_zeyad'

1 rows affected.

+----------------+
| TotalCustomers |
+----------------+
|      1445      |
+----------------+

---
## Level 2: Intermediate â€“ Aggregations and Basic Joins
##### (Task 1,2,3 using Pandas read_sql and Task 4,5 using execute and fetchall() in mysql.connector)

### Task 1: Calculate the total revenue (sum of list_price * quantity) from the order_items table.

In [48]:
%%sql 
SELECT SUM(list_price * quantity)
AS TotalRevenue FROM order_items;

Running query in 'mysql+pymysql://root:***@localhost/bike_zeyad'

1 rows affected.

+--------------+
| TotalRevenue |
+--------------+
|  8578988.88  |
+--------------+

### Task 2: Calculate the average price of products in the products table.

In [50]:
%%sql
SELECT AVG(list_price) AS AveragePrice
FROM products;

Running query in 'mysql+pymysql://root:***@localhost/bike_zeyad'

1 rows affected.

+--------------+
| AveragePrice |
+--------------+
| 1520.591402  |
+--------------+

### Task 3: Retrieve the number of orders placed by each customer.

In [52]:
%%sql
SELECT customer_id, COUNT(*) AS nnumber_of_orders
FROM orders
GROUP BY customer_id;

Running query in 'mysql+pymysql://root:***@localhost/bike_zeyad'

1445 rows affected.

+-------------+-------------------+
| customer_id | nnumber_of_orders |
+-------------+-------------------+
|      1      |         3         |
|      2      |         3         |
|      3      |         3         |
|      4      |         3         |
|      5      |         3         |
|      6      |         3         |
|      7      |         3         |
|      8      |         3         |
|      9      |         3         |
|      10     |         3         |
|      11     |         3         |
|      12     |         3         |
|      13     |         3         |
|      14     |         3         |
|      15     |         3         |
|      16     |         3         |
|      17     |         3         |
|      18     |         3         |
|      19     |         3         |
|      20     |         3         |
|      21     |         3         |
|      22     |         2         |
|      23     |         2         |
|      24     |         3         |
|      25     |         2         |
|      26     |         2         |
|      27     |         2         |
|      28     |         2         |
|      29     |         2         |
|      30     |         3         |
|      31     |         3         |
|      32     |         3         |
|      33     |         3         |
|      34     |         2         |
|      35     |         2         |
|      36     |         2         |
|      37     |         2         |
|      38     |         2         |
|      39     |         2         |
|      40     |         3         |
|      41     |         2         |
|      42     |         2         |
|      43     |         3         |
|      44     |         2         |
|      45     |         2         |
|      46     |         3         |
|      47     |         3         |
|      48     |         2         |
|      49     |         2         |
|      50     |         3         |
|      51     |         2         |
|      52     |         2         |
|      53     |         3         |
|      54     |         2         |
|      55     |         2         |
|      56     |         3         |
|      57     |         2         |
|      58     |         2         |
|      59     |         2         |
|      60     |         2         |
|      61     |         3         |
|      62     |         2         |
|      63     |         2         |
|      64     |         3         |
|      65     |         2         |
|      66     |         3         |
|      67     |         2         |
|      68     |         3         |
|      69     |         2         |
|      70     |         2         |
|      71     |         2         |
|      72     |         2         |
|      73     |         2         |
|      74     |         2         |
|      75     |         2         |
|      76     |         2         |
|      77     |         3         |
|      78     |         2         |
|      79     |         2         |
|      80     |         2         |
|      81     |         2         |
|      82     |         2         |
|      83     |         2         |
|      84     |         2         |
|      85     |         2         |
|      86     |         2         |
|      87     |         2         |
|      88     |         2         |
|      89     |         2         |
|      90     |         2         |
|      91     |         2         |
|      92     |         2         |
|      93     |         2         |
|      94     |         2         |
|      95     |         1         |
|      96     |         1         |
|      97     |         2         |
|      98     |         1         |
|      99     |         1         |
|     100     |         1         |
|     101     |         1         |
|     102     |         1         |
|     103     |         1         |
|     104     |         2         |
|     105     |         1         |
|     106     |         1         |
|     107     |         1         |
|     108     |         1         |
|     109     |         2         |
|     110     |         2         |
|     111     |         1         |
|     112     |         1         |
|     113     |         1         |
|     114     |         1         |
|     115     |         1         |
|     116     |         3         |
|     117     |         2         |
|     118     |         1         |
|     119     |         2         |
|     120     |         2         |
|     121     |         2         |
|     122     |         1         |
|     123     |         2         |
|     124     |         2         |
|     125     |         1         |
|     126     |         1         |
|     127     |         1         |
|     128     |         1         |
|     129     |         1         |
|     130     |         1         |
|     131     |         1         |
|     132     |         1         |
|     133     |         1         |
|     134     |         1         |
|     135     |         2         |
|     136     |         2         |
|     137     |         1         |
|     138     |         2         |
|     139     |         1         |
|     140     |         1         |
|     141     |         1         |
|     142     |         1         |
|     143     |         1         |
|     144     |         1         |
|     145     |         1         |
|     146     |         1         |
|     147     |         1         |
|     148     |         1         |
|     149     |         1         |
|     150     |         1         |
|     151     |         2         |
|     152     |         1         |
|     153     |         2         |
|     154     |         1         |
|     155     |         1         |
|     156     |         1         |
|     157     |         2         |
|     158     |         1         |
|     159     |         1         |
|     160     |         1         |
|     161     |         1         |
|     162     |         1         |
|     163     |         1         |
|     164     |         1         |
|     165     |         2         |
|     166     |         1         |
|     167     |         1         |
|     168     |         1         |
|     169     |         2         |
|     170     |         2         |
|     171     |         1         |
|     172     |         2         |
|     173     |         1         |
|     174     |         1         |
|     175     |         2         |
|     176     |         2         |
|     177     |         1         |
|     178     |         1         |
|     179     |         1         |
|     180     |         1         |
|     181     |         2         |
|     182     |         1         |
|     183     |         1         |
|     184     |         1         |
|     185     |         1         |
|     186     |         1         |
|     187     |         2         |
|     188     |         2         |
|     189     |         1         |
|     190     |         1         |
|     191     |         2         |
|     192     |         2         |
|     193     |         1         |
|     194     |         2         |
|     195     |         1         |
|     196     |         1         |
|     197     |         1         |
|     198     |         1         |
|     199     |         1         |
|     200     |         1         |
|     201     |         1         |
|     202     |         1         |
|     203     |         1         |
|     204     |         1         |
|     205     |         1         |
|     206     |         1         |
|     207     |         1         |
|     208     |         2         |
|     209     |         1         |
|     210     |         1         |
|     211     |         1         |
|     212     |         1         |
|     213     |         1         |
|     214     |         1         |
|     215     |         1         |
|     216     |         1         |
|     217     |         2         |
|     218     |         1         |
|     219     |         1         |
|     220     |         1         |
|     221     |         1         |
|     222     |         1         |
|     223     |         1         |
|     224     |         2         |
|     225     |         1         |
|     226     |         1         |
|     227     |         1         |
|     228     |         1         |
|     229     |         1         |
|     230     |         1         |
|     231     |         2         |
|     232     |         1         |
|     233     |         2         |
|     234     |         1         |
|     235     |         1         |
|     236     |         1         |
|     237     |         2         |
|     238     |         1         |
|     239     |         2         |
|     240     |         2         |
|     241     |         1         |
|     242     |         1         |
|     243     |         1         |
|     244     |         1         |
|     245     |         1         |
|     246     |         1         |
|     247     |         1         |
|     248     |         1         |
|     249     |         1         |
|     250     |         1         |
|     251     |         1         |
|     252     |         1         |
|     253     |         1         |
|     254     |         1         |
|     255     |         1         |
|     256     |         1         |
|     257     |         1         |
|     258     |         1         |
|     259     |         1         |
|     260     |         1         |
|     261     |         1         |
|     262     |         1         |
|     263     |         1         |
|     264     |         1         |
|     265     |         1         |
|     266     |         1         |
|     267     |         1         |
|     268     |         1         |
|     269     |         1         |
|     270     |         1         |
|     271     |         1         |
|     272     |         1         |
|     273     |         1         |
|     274     |         1         |
|     275     |         1         |
|     276     |         1         |
|     277     |         1         |
|     278     |         1         |
|     279     |         1         |
|     280     |         1         |
|     281     |         1         |
|     282     |         1         |
|     283     |         1         |
|     284     |         1         |
|     285     |         1         |
|     286     |         1         |
|     287     |         1         |
|     288     |         1         |
|     289     |         1         |
|     290     |         1         |
|     291     |         1         |
|     292     |         1         |
|     293     |         1         |
|     294     |         1         |
|     295     |         1         |
|     296     |         1         |
|     297     |         1         |
|     298     |         1         |
|     299     |         1         |
|     300     |         1         |
|     301     |         1         |
|     302     |         1         |
|     303     |         1         |
|     304     |         1         |
|     305     |         1         |
|     306     |         1         |
|     307     |         1         |
|     308     |         1         |
|     309     |         1         |
|     310     |         1         |
|     311     |         1         |
|     312     |         1         |
|     313     |         1         |
|     314     |         1         |
|     315     |         1         |
|     316     |         1         |
|     317     |         1         |
|     318     |         1         |
|     319     |         1         |
|     320     |         1         |
|     321     |         1         |
|     322     |         1         |
|     323     |         1         |
|     324     |         1         |
|     325     |         1         |
|     326     |         1         |
|     327     |         1         |
|     328     |         1         |
|     329     |         1         |
|     330     |         1         |
|     331     |         1         |
|     332     |         1         |
|     333     |         1         |
|     334     |         1         |
|     335     |         1         |
|     336     |         1         |
|     337     |         1         |
|     338     |         1         |
|     339     |         1         |
|     340     |         1         |
|     341     |         1         |
|     342     |         1         |
|     343     |         1         |
|     344     |         1         |
|     345     |         1         |
|     346     |         1         |
|     347     |         1         |
|     348     |         1         |
|     349     |         1         |
|     350     |         1         |
|     351     |         1         |
|     352     |         1         |
|     353     |         1         |
|     354     |         1         |
|     355     |         1         |
|     356     |         1         |
|     357     |         1         |
|     358     |         1         |
|     359     |         1         |
|     360     |         1         |
|     361     |         1         |
|     362     |         1         |
|     363     |         1         |
|     364     |         1         |
|     365     |         1         |
|     366     |         1         |
|     367     |         1         |
|     368     |         1         |
|     369     |         1         |
|     370     |         1         |
|     371     |         1         |
|     372     |         1         |
|     373     |         1         |
|     374     |         1         |
|     375     |         1         |
|     376     |         1         |
|     377     |         1         |
|     378     |         1         |
|     379     |         1         |
|     380     |         1         |
|     381     |         1         |
|     382     |         1         |
|     383     |         1         |
|     384     |         1         |
|     385     |         1         |
|     386     |         1         |
|     387     |         1         |
|     388     |         1         |
|     389     |         1         |
|     390     |         1         |
|     391     |         1         |
|     392     |         1         |
|     393     |         1         |
|     394     |         1         |
|     395     |         1         |
|     396     |         1         |
|     397     |         1         |
|     398     |         1         |
|     399     |         1         |
|     400     |         1         |
|     401     |         1         |
|     402     |         1         |
|     403     |         1         |
|     404     |         1         |
|     405     |         1         |
|     406     |         1         |
|     407     |         1         |
|     408     |         1         |
|     409     |         1         |
|     410     |         1         |
|     411     |         1         |
|     412     |         1         |
|     413     |         1         |
|     414     |         1         |
|     415     |         1         |
|     416     |         1         |
|     417     |         1         |
|     418     |         1         |
|     419     |         1         |
|     420     |         1         |
|     421     |         1         |
|     422     |         1         |
|     423     |         1         |
|     424     |         1         |
|     425     |         1         |
|     426     |         1         |
|     427     |         1         |
|     428     |         1         |
|     429     |         1         |
|     430     |         1         |
|     431     |         1         |
|     432     |         1         |
|     433     |         1         |
|     434     |         1         |
|     435     |         1         |
|     436     |         1         |
|     437     |         1         |
|     438     |         1         |
|     439     |         1         |
|     440     |         1         |
|     441     |         1         |
|     442     |         1         |
|     443     |         1         |
|     444     |         1         |
|     445     |         1         |
|     446     |         1         |
|     447     |         1         |
|     448     |         1         |
|     449     |         1         |
|     450     |         1         |
|     451     |         1         |
|     452     |         1         |
|     453     |         1         |
|     454     |         1         |
|     455     |         1         |
|     456     |         1         |
|     457     |         1         |
|     458     |         1         |
|     459     |         1         |
|     460     |         1         |
|     461     |         1         |
|     462     |         1         |
|     463     |         1         |
|     464     |         1         |
|     465     |         1         |
|     466     |         1         |
|     467     |         1         |
|     468     |         1         |
|     469     |         1         |
|     470     |         1         |
|     471     |         1         |
|     472     |         1         |
|     473     |         1         |
|     474     |         1         |
|     475     |         1         |
|     476     |         1         |
|     477     |         1         |
|     478     |         1         |
|     479     |         1         |
|     480     |         1         |
|     481     |         1         |
|     482     |         1         |
|     483     |         1         |
|     484     |         1         |
|     485     |         1         |
|     486     |         1         |
|     487     |         1         |
|     488     |         1         |
|     489     |         1         |
|     490     |         1         |
|     491     |         1         |
|     492     |         1         |
|     493     |         1         |
|     494     |         1         |
|     495     |         1         |
|     496     |         1         |
|     497     |         1         |
|     498     |         1         |
|     499     |         1         |
|     500     |         1         |
|     501     |         1         |
|     502     |         1         |
|     503     |         1         |
|     504     |         1         |
|     505     |         1         |
|     506     |         1         |
|     507     |         1         |
|     508     |         1         |
|     509     |         1         |
|     510     |         1         |
|     511     |         1         |
|     512     |         1         |
|     513     |         1         |
|     514     |         1         |
|     515     |         1         |
|     516     |         1         |
|     517     |         1         |
|     518     |         1         |
|     519     |         1         |
|     520     |         1         |
|     521     |         1         |
|     522     |         1         |
|     523     |         1         |
|     524     |         1         |
|     525     |         1         |
|     526     |         1         |
|     527     |         1         |
|     528     |         1         |
|     529     |         1         |
|     530     |         1         |
|     531     |         1         |
|     532     |         1         |
|     533     |         1         |
|     534     |         1         |
|     535     |         1         |
|     536     |         1         |
|     537     |         1         |
|     538     |         1         |
|     539     |         1         |
|     540     |         1         |
|     541     |         1         |
|     542     |         1         |
|     543     |         1         |
|     544     |         1         |
|     545     |         1         |
|     546     |         1         |
|     547     |         1         |
|     548     |         1         |
|     549     |         1         |
|     550     |         1         |
|     551     |         1         |
|     552     |         1         |

### Task 4: Join Orders with Customers

#### Task 4.1: Retrieve customer names along with their order IDs.

In [54]:
%%sql
SELECT CONCAT(c.first_name, ' ', c.last_name) AS customer_name, o.order_id
FROM customers c
JOIN orders o ON c.customer_id = o.customer_id;

Running query in 'mysql+pymysql://root:***@localhost/bike_zeyad'

1615 rows affected.

+------------------------+----------+
|     customer_name      | order_id |
+------------------------+----------+
|      Debra Burks       |   599    |
|      Debra Burks       |   1555   |
|      Debra Burks       |   1613   |
|       Kasha Todd       |   692    |
|       Kasha Todd       |   1084   |
|       Kasha Todd       |   1509   |
|     Tameka Fisher      |   1468   |
|     Tameka Fisher      |   1496   |
|     Tameka Fisher      |   1612   |
|      Daryl Spence      |   700    |
|      Daryl Spence      |   1259   |
|      Daryl Spence      |   1556   |
|    Charolette Rice     |   264    |
|    Charolette Rice     |   571    |
|    Charolette Rice     |   1544   |
|      Lyndsey Bean      |   1059   |
|      Lyndsey Bean      |   1592   |
|      Lyndsey Bean      |   1611   |
|      Latasha Hays      |   104    |
|      Latasha Hays      |   1532   |
|      Latasha Hays      |   1604   |
|    Jacquline Duncan    |   512    |
|    Jacquline Duncan    |   1010   |
|    Jacquline Duncan    |   1523   |
|    Genoveva Baldwin    |    76    |
|    Genoveva Baldwin    |   1459   |
|    Genoveva Baldwin    |   1593   |
|     Pamelia Newman     |   825    |
|     Pamelia Newman     |   1541   |
|     Pamelia Newman     |   1609   |
|    Deshawn Mendoza     |   1074   |
|    Deshawn Mendoza     |   1387   |
|    Deshawn Mendoza     |   1588   |
|      Robby Sykes       |   108    |
|      Robby Sykes       |   715    |
|      Robby Sykes       |   1576   |
|     Lashawn Ortiz      |   239    |
|     Lashawn Ortiz      |   852    |
|     Lashawn Ortiz      |   1527   |
|     Garry Espinoza     |   357    |
|     Garry Espinoza     |   419    |
|     Garry Espinoza     |   1572   |
|     Linnie Branch      |   1401   |
|     Linnie Branch      |   1483   |
|     Linnie Branch      |   1610   |
|     Emmitt Sanchez     |   352    |
|     Emmitt Sanchez     |   1020   |
|     Emmitt Sanchez     |   1510   |
|     Caren Stephens     |   246    |
|     Caren Stephens     |   301    |
|     Caren Stephens     |   1549   |
|    Georgetta Hardin    |   606    |
|    Georgetta Hardin    |   1407   |
|    Georgetta Hardin    |   1534   |
|     Lizzette Stein     |   1211   |
|     Lizzette Stein     |   1234   |
|     Lizzette Stein     |   1535   |
|     Aleta Shepard      |   547    |
|     Aleta Shepard      |   735    |
|     Aleta Shepard      |   1528   |
|      Tobie Little      |   1177   |
|      Tobie Little      |   1409   |
|      Tobie Little      |   1596   |
|     Adelle Larsen      |   183    |
|     Adelle Larsen      |   1505   |
|     Kaylee English     |   1109   |
|     Kaylee English     |   1479   |
|      Corene Wall       |   185    |
|      Corene Wall       |   1157   |
|      Corene Wall       |   1573   |
|    Regenia Vaughan     |   1065   |
|    Regenia Vaughan     |   1511   |
|       Theo Reese       |   256    |
|       Theo Reese       |   1519   |
|    Santos Valencia     |   634    |
|    Santos Valencia     |   1480   |
|     Jeanice Frost      |   1306   |
|     Jeanice Frost      |   1533   |
|   Syreeta Hendricks    |   665    |
|   Syreeta Hendricks    |   1569   |
|     Jamaal Albert      |   349    |
|     Jamaal Albert      |   444    |
|     Jamaal Albert      |   1553   |
|   Williemae Holloway   |   162    |
|   Williemae Holloway   |   350    |
|   Williemae Holloway   |   1497   |
|     Araceli Golden     |   159    |
|     Araceli Golden     |   582    |
|     Araceli Golden     |   1513   |
|     Deloris Burke      |   575    |
|     Deloris Burke      |   1487   |
|     Deloris Burke      |   1607   |
|   Brittney Woodward    |   1190   |
|   Brittney Woodward    |   1536   |
|   Guillermina Noble    |   1476   |
|   Guillermina Noble    |   1484   |
|    Bernita Mcdaniel    |   303    |
|    Bernita Mcdaniel    |   1537   |
|      Melia Brady       |   1295   |
|      Melia Brady       |   1524   |
|     Zelma Browning     |   718    |
|     Zelma Browning     |   1525   |
|    Janetta Aguirre     |   1322   |
|    Janetta Aguirre     |   1550   |
|      Ronna Butler      |   598    |
|      Ronna Butler      |   1092   |
|      Ronna Butler      |   1589   |
|     Kathie Freeman     |   1161   |
|     Kathie Freeman     |   1492   |
|     Tangela Quinn      |   1076   |
|     Tangela Quinn      |   1559   |
|     Mozelle Carter     |   157    |
|     Mozelle Carter     |   935    |
|     Mozelle Carter     |   1601   |
|      Onita Johns       |   1253   |
|      Onita Johns       |   1583   |
|   Bennett Armstrong    |   826    |
|   Bennett Armstrong    |   1594   |
|      Monika Berg       |   132    |
|      Monika Berg       |   1089   |
|      Monika Berg       |   1564   |
|    Bridgette Guerra    |   897    |
|    Bridgette Guerra    |   1072   |
|    Bridgette Guerra    |   1516   |
|     Cesar Jackson      |   1200   |
|     Cesar Jackson      |   1577   |
|      Caroll Hays       |   739    |
|      Caroll Hays       |   1599   |
|    Cleotilde Booth     |    70    |
|    Cleotilde Booth     |   593    |
|    Cleotilde Booth     |   1529   |
|     Gertrud Rhodes     |   222    |
|     Gertrud Rhodes     |   1485   |
|       Tu Ramirez       |   1116   |
|       Tu Ramirez       |   1501   |
|    Saturnina Garner    |   389    |
|    Saturnina Garner    |   1521   |
|    Saturnina Garner    |   1608   |
|       Fran Yang        |   519    |
|       Fran Yang        |   1570   |
|      Diana Guerra      |   147    |
|      Diana Guerra      |   1602   |
|     Lolita Mosley      |   778    |
|     Lolita Mosley      |   1413   |
|     Lolita Mosley      |   1597   |
|      Pamala Henry      |    27    |
|      Pamala Henry      |   1560   |
|     Damien Dorsey      |   694    |
|     Damien Dorsey      |   1542   |
|    Latasha Stanley     |   286    |
|    Latasha Stanley     |   1526   |
|      Neil Mccall       |    9     |
|      Neil Mccall       |   1565   |
|    Elinore Aguilar     |   391    |
|    Elinore Aguilar     |   556    |
|    Elinore Aguilar     |   1515   |
|      Alica Hunter      |   543    |
|      Alica Hunter      |   1481   |
|     Tenisha Lyons      |   1390   |
|     Tenisha Lyons      |   1558   |
|     Bobbie Foster      |   549    |
|     Bobbie Foster      |   673    |
|     Bobbie Foster      |   1493   |
|      Kanesha Vega      |   240    |
|      Kanesha Vega      |   1561   |
|     Lorrie Becker      |   252    |
|     Lorrie Becker      |   885    |
|     Lorrie Becker      |   1520   |
|     Tommie Melton      |   424    |
|     Tommie Melton      |   1545   |
|     Jayne Kirkland     |   924    |
|     Jayne Kirkland     |   1325   |
|     Jayne Kirkland     |   1512   |
|    Katelin Kennedy     |   1130   |
|    Katelin Kennedy     |   1494   |
|     Tomasa Carson      |   1041   |
|     Tomasa Carson      |   1551   |
|      Takako Casey      |   1360   |
|      Takako Casey      |   1595   |
|    Petronila Norris    |   420    |
|    Petronila Norris    |   1566   |
|     Melanie Hayes      |   937    |
|     Melanie Hayes      |   1552   |
|    Georgeann Waller    |   464    |
|    Georgeann Waller    |   1603   |
|      Abby Gamble       |   1318   |
|      Abby Gamble       |   1506   |
|     Parker Prince      |   152    |
|     Parker Prince      |   1543   |
|      Keri Bridges      |   407    |
|      Keri Bridges      |   435    |
|      Keri Bridges      |   1563   |
|        Chi Goff        |   801    |
|        Chi Goff        |   1522   |
|     Ashanti Parks      |   707    |
|     Ashanti Parks      |   1538   |
|      Sarai Mckee       |    34    |
|      Sarai Mckee       |   1571   |
|      Zina Bonner       |   679    |
|      Zina Bonner       |   1498   |
|     Lizzie Joyner      |   961    |
|     Lizzie Joyner      |   1491   |
|     Tiesha Daniel      |   327    |
|     Tiesha Daniel      |   1502   |
|    Armand Whitehead    |   129    |
|    Armand Whitehead    |   1486   |
|    Teofila Fischer     |   1283   |
|    Teofila Fischer     |   1507   |
|      Lissa Vargas      |   128    |
|      Lissa Vargas      |   1495   |
|      Yan Mcgowan       |   747    |
|      Yan Mcgowan       |   1514   |
|     Titus Bullock      |   418    |
|     Titus Bullock      |   1562   |
|     Arvilla Osborn     |   1229   |
|     Arvilla Osborn     |   1567   |
|     Marjorie Logan     |   561    |
|     Marjorie Logan     |   1600   |
|     Marvin Mullins     |    12    |
|     Marvin Mullins     |   1546   |
|       Tena Cruz        |   1369   |
|       Tena Cruz        |   1508   |
|     Corrina Sawyer     |   934    |
|     Corrina Sawyer     |   1578   |
|     Sharyn Hopkins     |    6     |
|     Sharyn Hopkins     |   1482   |
|     Letitia Franco     |   804    |
|    Floretta Higgins    |   604    |
|     Louanne Martin     |   867    |
|     Louanne Martin     |   1517   |
|   Violet Valenzuela    |   190    |
|       Carie Kidd       |   169    |
|     Kellie Franco      |   1405   |
|    Nichelle Howell     |   448    |
|    Marisol Goodman     |   588    |
|    Sylvie Wilkerson    |   401    |
|    Katharina Bates     |   554    |
|    Katharina Bates     |   1579   |
|      Marget Hodge      |   207    |
|     Raul Melendez      |   1066   |
|      Cecil Hopper      |   258    |
|      Shae Hickman      |   1297   |
|      Monica Sears      |   1411   |
|      Monica Sears      |   1584   |
|    Ollie Zimmerman     |   1252   |
|    Ollie Zimmerman     |   1530   |
|      Shila White       |   516    |
|        Yuk Vega        |   1475   |
|      Eliana Silva      |   1264   |
|      Thalia Horne      |   1472   |
|      Rey Lindsay       |   1370   |
|     Merlene Vinson     |   531    |
|     Merlene Vinson     |   1047   |
|     Merlene Vinson     |   1539   |
|     Dacia William      |   158    |
|     Dacia William      |   173    |
|        Le Wood         |   617    |
|     Thalia Dillard     |   741    |
|     Thalia Dillard     |   1606   |
|       Luz House        |   907    |
|       Luz House        |   1499   |
|       Lucy Woods       |   177    |
|       Lucy Woods       |   1557   |
|      Shena Carter      |   1364   |
|      Robena Hill       |   1280   |
|      Robena Hill       |   1605   |
|      Jeni Booker       |   738    |
|      Jeni Booker       |   1574   |
|     Herlinda Stone     |   1021   |
|     Lavina Dejesus     |   1425   |
|    Erlinda Nielsen     |   197    |
|     Terrance Lynn      |   1284   |
|     Walton Dejesus     |   938    |
|      Wes Stanton       |   626    |
|    Tanesha Hampton     |   618    |
|       Boyd Irwin       |   372    |
|    Delbert Wilkins     |   287    |
|      Brianna Moss      |   184    |
|    Dorthey Jackson     |   770    |
|    Dorthey Jackson     |   1614   |
|      Sarita Parks      |   1346   |
|      Sarita Parks      |   1615   |
|     Shonta Mercer      |   743    |
|      Jone Bernard      |   944    |
|      Jone Bernard      |   1590   |
|    Wanita Davenport    |   1461   |
|     Cleopatra Tate     |   1055   |
|      Ramiro Byers      |   766    |
|    Nicholas Vazquez    |   950    |
|      Janae Doyle       |   1121   |
|       Hans Price       |   395    |
|      Miquel Neal       |   249    |
|     Stefany Potter     |   1399   |
|    Bernetta Marquez    |   732    |
|     Julee Woodard      |   500    |
|     Meredith Bryan     |   439    |
|     Weldon Michael     |   250    |
|    Joesph Delacruz     |    60    |
|    Joesph Delacruz     |   1500   |
|     Katherina Odom     |   1467   |
|    Laraine Robbins     |   429    |
|    Laraine Robbins     |   810    |
|     Jenise Preston     |   796    |
|       Lory Page        |   513    |
|    Charlyn Cantrell    |   308    |
|    Carola Rodriquez    |   224    |
|    Carola Rodriquez    |   1585   |
|     Alane Kennedy      |   291    |
|      Regina Burns      |   282    |
|      Omer Estrada      |   579    |
|    Crystle Gilliam     |   1030   |
|       Kam Wilder       |   858    |
|    Margert Stevens     |   632    |
|     Tomika Larson      |    37    |
|      Jeromy Burch      |   1275   |
|      Jeromy Burch      |   1591   |
|       Lena Mills       |   744    |
|    Loreta Johnston     |   945    |
|    Nettie Mcdaniel     |   1017   |
|       Karla Kirk       |   432    |
|       Karla Kirk       |   1547   |
|    Regine Gonzales     |   142    |
|    Regine Gonzales     |   1548   |
|      Miriam Baker      |   890    |
|    Jeanie Kirkland     |   987    |
|    Jeanie Kirkland     |   1554   |
|   Marquerite Dawson    |   712    |
|      Babara Ochoa      |   1013   |
|       Nova Hess        |    4     |
|       Nova Hess        |   1518   |
|    Carley Reynolds     |   392    |
|    Carley Reynolds     |   1586   |
|    Carissa Foreman     |   854    |
|     Genoveva Tyler     |   572    |
|      Deane Sears       |   903    |
|      Karey Steele      |   1477   |
|      Olevia Pitts      |   283    |
|      Olevia Pitts      |   1488   |
|   Jenniffer Bullock    |   1060   |
|    Jeniffer Ratliff    |   187    |
|     Klara Stanley      |   736    |
|       Morton Lee       |   1045   |
|      Ken Charles       |   1191   |
|      Hedwig Paul       |   362    |
|      Hedwig Paul       |   1540   |
|      Sharla Flynn      |   909    |
|      Sharla Flynn      |   1581   |
|     Damian Dawson      |   1054   |
|       Toya Pratt       |   651    |
|    Graciela Barber     |   492    |
|    Graciela Barber     |   1580   |
|      Bong Hebert       |   1194   |
|      Bong Hebert       |   1568   |
|     Ayanna Rhodes      |   496    |
|    Dorine Roberson     |   1049   |
|    Dorine Roberson     |   1489   |
|       Addie Hahn       |   1428   |
|    Edythe Valencia     |   882    |
|      Andy O'neill      |   458    |
|       Luis Tyler       |   1063   |
|     Clelia Workman     |   382    |
|     Ashely Holmes      |   719    |
|     Candis Harding     |   1201   |
|      Marni Bolton      |   290    |
|     Minerva Decker     |   1333   |
|       Alpha King       |    97    |
|     Harris Pittman     |   160    |
|    Stephaine Riddle    |   236    |
|   Michel Blankenship   |   713    |
|      Denis Logan       |    62    |
|      Denis Logan       |   1503   |
|     Jutta Everett      |   1051   |
|   Priscilla Wilkins    |   1235   |
|     Gilma Dejesus      |   309    |
|     Buford Bridges     |   555    |
|    Elenore Hensley     |   1212   |
|       Ross Pugh        |   879    |
|     Judith Finley      |   915    |
|        Wai Soto        |   1183   |
|    Carline Collier     |   1321   |
|    Carline Collier     |   1490   |
|       Casey Gill       |    95    |
|     Darcie Morgan      |   998    |
|     Lucio Sherman      |   1086   |
|   Clementine Mooney    |   819    |
|     Anya Contreras     |   1206   |
|     Scarlet Yates      |   245    |
|       Moses Pope       |   878    |
|       Moses Pope       |   1575   |
|     Barbera Riggs      |   1067   |
|      Kiana Rivera      |   1226   |
|     Danielle Bond      |   1277   |
|     Whitney Estes      |   1448   |
|     Molly Langley      |   1195   |
|     Chelsey Hardin     |   304    |
|    Jenee Rasmussen     |   1296   |
|    Jenee Rasmussen     |   1587   |
|     Freddie Mathis     |   750    |
|     Mariana Strong     |   926    |
|     Mariana Strong     |   1531   |
|     Winfred Harris     |   806    |
|     Jeromy Elliott     |   509    |
|     Verona O'neill     |    33    |
|      Elvera Peck       |   171    |
|      Elvera Peck       |   1504   |
|      Cindi Larson      |   973    |
|     Felice Guzman      |   1050   |
|     Felice Guzman      |   1598   |
|       Le Deleon        |   421    |
|       Le Deleon        |   1582   |
|     Manie Sanchez      |   475    |
|      Rutha Howell      |   918    |
|    Natosha Rowland     |   1236   |
|      Jessika Bray      |   1320   |
|    Delila Hamilton     |   680    |
|     Dionne Norris      |   828    |
|     Muriel Juarez      |   1347   |
|      Cecelia Gill      |   969    |
|      Magda Eaton       |   786    |
|      Ivonne Yang       |   678    |
|    Kasie Rodriquez     |   161    |
|      Eleni Gordon      |    28    |
|     Maurice Norton     |   1358   |
|  Cristobal Hutchinson  |   1138   |
|     Flossie Holder     |   749    |
|      Erma Salinas      |   1332   |
|      Earl Stanley      |   1305   |
|    Maribel William     |    14    |
|  Johnathan Velazquez   |    1     |
|    Rodrick Shelton     |   499    |
|      Ferne Kline       |   411    |
|      Rubin Decker      |   1285   |
|     Dortha Jarvis      |   1438   |
|    Mariela Huffman     |    74    |
|     Mellisa Farley     |   936    |
|      Myung Hooper      |   1005   |
|     Angelina Lloyd     |   216    |
|     Trinity Riddle     |   1104   |
|     Barton Crosby      |   1197   |
|      Claudio Wise      |   972    |
|    Katheleen Marks     |   101    |
|      Deja Chaney       |   430    |
|     Queenie Vance      |   1323   |
|       Josh Shaw        |   329    |
|    Pinkie Kirkland     |   1124   |
|     Lavette Wright     |    86    |
|      Mark Garrett      |    61    |
|     Myesha Burgess     |   947    |
|      Justina Long      |   1287   |
|      Brenda Tate       |   201    |
|      Rayna Perry       |   299    |
|     Randolph Chase     |   267    |
|       Jaimee Day       |   647    |
|      Susann Bass       |   759    |
|      Leola Gould       |   1292   |
|      Virgil Frost      |   1166   |
|    Mireille Puckett    |   1452   |
|     Keturah Massey     |   146    |
|    Charmain Webster    |   1251   |
|     Barry Buckner      |   1018   |
|      Boyce Burks       |   675    |
|      Monty Frost       |   1175   |
|      Tiny French       |   1414   |
|   Clementina Sargent   |   822    |
|       Danny Kim        |   710    |
|    Sophia Mcmillan     |   1450   |
|    Christia Carson     |   668    |
|    Jennie Middleton    |   566    |
|       Jame Riggs       |   312    |
|     Rayford Simon      |   1417   |
|     Annett Garrett     |   817    |
|      Hayden Cross      |   1473   |
|     Rolanda Larsen     |   1242   |
|      Jayme Zamora      |   478    |
|      Hope Cotton       |   1085   |
|     Vikki Erickson     |   105    |
|  Fransisca Nicholson   |   225    |
|    Mazie Fernandez     |   1431   |
|    Anderson Martin     |   607    |
|    Gilberto Parsons    |   1362   |
|      Charise Burt      |   1312   |
|    Cameron Carroll     |   1375   |
|     Melani Jarvis      |   542    |
|     Javier Nichols     |   438    |
|    Justina Jenkins     |   808    |
|    Hortencia Graham    |   131    |
|    Christia Wilkins    |    84    |
|      Eliz Whitney      |   1199   |
|     Justin Newton      |   285    |
|      Aron Wiggins      |   1282   |
|      Chere Hardin      |   544    |
|    Merideth Preston    |   1302   |
|    Jeniffer Slater     |   1388   |
|      Laureen Paul      |    7     |
|      Berna Moore       |   1056   |
|    Shiela Calderon     |   1093   |
|     Sharie Alvarez     |   120    |
|     Bettie Glover      |   980    |
|     Marilyn Frank      |   847    |
|      Sheba Knapp       |   1449   |
|       Aleta Mack       |   383    |
|     Reena Higgins      |   150    |
|      Ami Mcmahon       |   1244   |
|      Somer Jordan      |   1117   |
|      Scarlet Reed      |   752    |
|     Trisha Johnson     |   102    |
|     Majorie Wyatt      |   373    |
|       Abbey Pugh       |   166    |
|     Tamela Harrell     |   951    |
|    Yanira Bradshaw     |   802    |
|      Delana Scott      |   538    |
|    Cassondra Pruitt    |   910    |
|     Jesica Fields      |   688    |
|     Herta Rollins      |   663    |
|        Mi Gray         |   901    |
|    Jacalyn Barnett     |   1243   |
|     Kanesha Hudson     |   655    |
|      Darren Witt       |    40    |
|      Mable Pratt       |   657    |
|   Christoper Mccall    |   271    |
|     Margorie Wynn      |   1132   |
|      Josef Greer       |   898    |
|      Tisa Whitney      |   1022   |

#### Task 4.2: Retrieve Customer Names with Order IDs and Total Orders

In [56]:
%%sql 
SELECT CONCAT(c.first_name, ' ', c.last_name) AS customer_name, 
       o.order_id, 
       COUNT(o.order_id) OVER (PARTITION BY c.customer_id) AS total_orders
FROM customers c
JOIN orders o ON c.customer_id = o.customer_id;

Running query in 'mysql+pymysql://root:***@localhost/bike_zeyad'

1615 rows affected.

+------------------------+----------+--------------+
|     customer_name      | order_id | total_orders |
+------------------------+----------+--------------+
|      Debra Burks       |   599    |      3       |
|      Debra Burks       |   1613   |      3       |
|      Debra Burks       |   1555   |      3       |
|       Kasha Todd       |   692    |      3       |
|       Kasha Todd       |   1509   |      3       |
|       Kasha Todd       |   1084   |      3       |
|     Tameka Fisher      |   1468   |      3       |
|     Tameka Fisher      |   1612   |      3       |
|     Tameka Fisher      |   1496   |      3       |
|      Daryl Spence      |   700    |      3       |
|      Daryl Spence      |   1556   |      3       |
|      Daryl Spence      |   1259   |      3       |
|    Charolette Rice     |   571    |      3       |
|    Charolette Rice     |   264    |      3       |
|    Charolette Rice     |   1544   |      3       |
|      Lyndsey Bean      |   1592   |      3       |
|      Lyndsey Bean      |   1059   |      3       |
|      Lyndsey Bean      |   1611   |      3       |
|      Latasha Hays      |   1532   |      3       |
|      Latasha Hays      |   104    |      3       |
|      Latasha Hays      |   1604   |      3       |
|    Jacquline Duncan    |   1010   |      3       |
|    Jacquline Duncan    |   512    |      3       |
|    Jacquline Duncan    |   1523   |      3       |
|    Genoveva Baldwin    |   1459   |      3       |
|    Genoveva Baldwin    |    76    |      3       |
|    Genoveva Baldwin    |   1593   |      3       |
|     Pamelia Newman     |   1609   |      3       |
|     Pamelia Newman     |   1541   |      3       |
|     Pamelia Newman     |   825    |      3       |
|    Deshawn Mendoza     |   1588   |      3       |
|    Deshawn Mendoza     |   1387   |      3       |
|    Deshawn Mendoza     |   1074   |      3       |
|      Robby Sykes       |   1576   |      3       |
|      Robby Sykes       |   715    |      3       |
|      Robby Sykes       |   108    |      3       |
|     Lashawn Ortiz      |   1527   |      3       |
|     Lashawn Ortiz      |   852    |      3       |
|     Lashawn Ortiz      |   239    |      3       |
|     Garry Espinoza     |   1572   |      3       |
|     Garry Espinoza     |   419    |      3       |
|     Garry Espinoza     |   357    |      3       |
|     Linnie Branch      |   1610   |      3       |
|     Linnie Branch      |   1483   |      3       |
|     Linnie Branch      |   1401   |      3       |
|     Emmitt Sanchez     |   352    |      3       |
|     Emmitt Sanchez     |   1510   |      3       |
|     Emmitt Sanchez     |   1020   |      3       |
|     Caren Stephens     |   246    |      3       |
|     Caren Stephens     |   1549   |      3       |
|     Caren Stephens     |   301    |      3       |
|    Georgetta Hardin    |   606    |      3       |
|    Georgetta Hardin    |   1534   |      3       |
|    Georgetta Hardin    |   1407   |      3       |
|     Lizzette Stein     |   1211   |      3       |
|     Lizzette Stein     |   1535   |      3       |
|     Lizzette Stein     |   1234   |      3       |
|     Aleta Shepard      |   547    |      3       |
|     Aleta Shepard      |   1528   |      3       |
|     Aleta Shepard      |   735    |      3       |
|      Tobie Little      |   1409   |      3       |
|      Tobie Little      |   1177   |      3       |
|      Tobie Little      |   1596   |      3       |
|     Adelle Larsen      |   1505   |      2       |
|     Adelle Larsen      |   183    |      2       |
|     Kaylee English     |   1479   |      2       |
|     Kaylee English     |   1109   |      2       |
|      Corene Wall       |   185    |      3       |
|      Corene Wall       |   1573   |      3       |
|      Corene Wall       |   1157   |      3       |
|    Regenia Vaughan     |   1065   |      2       |
|    Regenia Vaughan     |   1511   |      2       |
|       Theo Reese       |   1519   |      2       |
|       Theo Reese       |   256    |      2       |
|    Santos Valencia     |   1480   |      2       |
|    Santos Valencia     |   634    |      2       |
|     Jeanice Frost      |   1533   |      2       |
|     Jeanice Frost      |   1306   |      2       |
|   Syreeta Hendricks    |   1569   |      2       |
|   Syreeta Hendricks    |   665    |      2       |
|     Jamaal Albert      |   349    |      3       |
|     Jamaal Albert      |   1553   |      3       |
|     Jamaal Albert      |   444    |      3       |
|   Williemae Holloway   |   162    |      3       |
|   Williemae Holloway   |   1497   |      3       |
|   Williemae Holloway   |   350    |      3       |
|     Araceli Golden     |   159    |      3       |
|     Araceli Golden     |   1513   |      3       |
|     Araceli Golden     |   582    |      3       |
|     Deloris Burke      |   575    |      3       |
|     Deloris Burke      |   1607   |      3       |
|     Deloris Burke      |   1487   |      3       |
|   Brittney Woodward    |   1536   |      2       |
|   Brittney Woodward    |   1190   |      2       |
|   Guillermina Noble    |   1484   |      2       |
|   Guillermina Noble    |   1476   |      2       |
|    Bernita Mcdaniel    |   303    |      2       |
|    Bernita Mcdaniel    |   1537   |      2       |
|      Melia Brady       |   1524   |      2       |
|      Melia Brady       |   1295   |      2       |
|     Zelma Browning     |   1525   |      2       |
|     Zelma Browning     |   718    |      2       |
|    Janetta Aguirre     |   1322   |      2       |
|    Janetta Aguirre     |   1550   |      2       |
|      Ronna Butler      |   1092   |      3       |
|      Ronna Butler      |   598    |      3       |
|      Ronna Butler      |   1589   |      3       |
|     Kathie Freeman     |   1492   |      2       |
|     Kathie Freeman     |   1161   |      2       |
|     Tangela Quinn      |   1076   |      2       |
|     Tangela Quinn      |   1559   |      2       |
|     Mozelle Carter     |   935    |      3       |
|     Mozelle Carter     |   157    |      3       |
|     Mozelle Carter     |   1601   |      3       |
|      Onita Johns       |   1583   |      2       |
|      Onita Johns       |   1253   |      2       |
|   Bennett Armstrong    |   1594   |      2       |
|   Bennett Armstrong    |   826    |      2       |
|      Monika Berg       |   132    |      3       |
|      Monika Berg       |   1564   |      3       |
|      Monika Berg       |   1089   |      3       |
|    Bridgette Guerra    |   897    |      3       |
|    Bridgette Guerra    |   1516   |      3       |
|    Bridgette Guerra    |   1072   |      3       |
|     Cesar Jackson      |   1577   |      2       |
|     Cesar Jackson      |   1200   |      2       |
|      Caroll Hays       |   1599   |      2       |
|      Caroll Hays       |   739    |      2       |
|    Cleotilde Booth     |    70    |      3       |
|    Cleotilde Booth     |   1529   |      3       |
|    Cleotilde Booth     |   593    |      3       |
|     Gertrud Rhodes     |   222    |      2       |
|     Gertrud Rhodes     |   1485   |      2       |
|       Tu Ramirez       |   1501   |      2       |
|       Tu Ramirez       |   1116   |      2       |
|    Saturnina Garner    |   1608   |      3       |
|    Saturnina Garner    |   1521   |      3       |
|    Saturnina Garner    |   389    |      3       |
|       Fran Yang        |   1570   |      2       |
|       Fran Yang        |   519    |      2       |
|      Diana Guerra      |   1602   |      2       |
|      Diana Guerra      |   147    |      2       |
|     Lolita Mosley      |   1597   |      3       |
|     Lolita Mosley      |   1413   |      3       |
|     Lolita Mosley      |   778    |      3       |
|      Pamala Henry      |   1560   |      2       |
|      Pamala Henry      |    27    |      2       |
|     Damien Dorsey      |   694    |      2       |
|     Damien Dorsey      |   1542   |      2       |
|    Latasha Stanley     |   1526   |      2       |
|    Latasha Stanley     |   286    |      2       |
|      Neil Mccall       |   1565   |      2       |
|      Neil Mccall       |    9     |      2       |
|    Elinore Aguilar     |   391    |      3       |
|    Elinore Aguilar     |   1515   |      3       |
|    Elinore Aguilar     |   556    |      3       |
|      Alica Hunter      |   1481   |      2       |
|      Alica Hunter      |   543    |      2       |
|     Tenisha Lyons      |   1558   |      2       |
|     Tenisha Lyons      |   1390   |      2       |
|     Bobbie Foster      |   549    |      3       |
|     Bobbie Foster      |   1493   |      3       |
|     Bobbie Foster      |   673    |      3       |
|      Kanesha Vega      |   240    |      2       |
|      Kanesha Vega      |   1561   |      2       |
|     Lorrie Becker      |   885    |      3       |
|     Lorrie Becker      |   252    |      3       |
|     Lorrie Becker      |   1520   |      3       |
|     Tommie Melton      |   1545   |      2       |
|     Tommie Melton      |   424    |      2       |
|     Jayne Kirkland     |   1512   |      3       |
|     Jayne Kirkland     |   1325   |      3       |
|     Jayne Kirkland     |   924    |      3       |
|    Katelin Kennedy     |   1130   |      2       |
|    Katelin Kennedy     |   1494   |      2       |
|     Tomasa Carson      |   1551   |      2       |
|     Tomasa Carson      |   1041   |      2       |
|      Takako Casey      |   1595   |      2       |
|      Takako Casey      |   1360   |      2       |
|    Petronila Norris    |   420    |      2       |
|    Petronila Norris    |   1566   |      2       |
|     Melanie Hayes      |   1552   |      2       |
|     Melanie Hayes      |   937    |      2       |
|    Georgeann Waller    |   1603   |      2       |
|    Georgeann Waller    |   464    |      2       |
|      Abby Gamble       |   1318   |      2       |
|      Abby Gamble       |   1506   |      2       |
|     Parker Prince      |   1543   |      2       |
|     Parker Prince      |   152    |      2       |
|      Keri Bridges      |   407    |      3       |
|      Keri Bridges      |   1563   |      3       |
|      Keri Bridges      |   435    |      3       |
|        Chi Goff        |   801    |      2       |
|        Chi Goff        |   1522   |      2       |
|     Ashanti Parks      |   1538   |      2       |
|     Ashanti Parks      |   707    |      2       |
|      Sarai Mckee       |   1571   |      2       |
|      Sarai Mckee       |    34    |      2       |
|      Zina Bonner       |   679    |      2       |
|      Zina Bonner       |   1498   |      2       |
|     Lizzie Joyner      |   1491   |      2       |
|     Lizzie Joyner      |   961    |      2       |
|     Tiesha Daniel      |   1502   |      2       |
|     Tiesha Daniel      |   327    |      2       |
|    Armand Whitehead    |   1486   |      2       |
|    Armand Whitehead    |   129    |      2       |
|    Teofila Fischer     |   1507   |      2       |
|    Teofila Fischer     |   1283   |      2       |
|      Lissa Vargas      |   128    |      2       |
|      Lissa Vargas      |   1495   |      2       |
|      Yan Mcgowan       |   1514   |      2       |
|      Yan Mcgowan       |   747    |      2       |
|     Titus Bullock      |   1562   |      2       |
|     Titus Bullock      |   418    |      2       |
|     Arvilla Osborn     |   1229   |      2       |
|     Arvilla Osborn     |   1567   |      2       |
|     Marjorie Logan     |   1600   |      2       |
|     Marjorie Logan     |   561    |      2       |
|     Marvin Mullins     |   1546   |      2       |
|     Marvin Mullins     |    12    |      2       |
|       Tena Cruz        |   1508   |      2       |
|       Tena Cruz        |   1369   |      2       |
|     Corrina Sawyer     |   1578   |      2       |
|     Corrina Sawyer     |   934    |      2       |
|     Sharyn Hopkins     |    6     |      2       |
|     Sharyn Hopkins     |   1482   |      2       |
|     Letitia Franco     |   804    |      1       |
|    Floretta Higgins    |   604    |      1       |
|     Louanne Martin     |   1517   |      2       |
|     Louanne Martin     |   867    |      2       |
|   Violet Valenzuela    |   190    |      1       |
|       Carie Kidd       |   169    |      1       |
|     Kellie Franco      |   1405   |      1       |
|    Nichelle Howell     |   448    |      1       |
|    Marisol Goodman     |   588    |      1       |
|    Sylvie Wilkerson    |   401    |      1       |
|    Katharina Bates     |   1579   |      2       |
|    Katharina Bates     |   554    |      2       |
|      Marget Hodge      |   207    |      1       |
|     Raul Melendez      |   1066   |      1       |
|      Cecil Hopper      |   258    |      1       |
|      Shae Hickman      |   1297   |      1       |
|      Monica Sears      |   1584   |      2       |
|      Monica Sears      |   1411   |      2       |
|    Ollie Zimmerman     |   1530   |      2       |
|    Ollie Zimmerman     |   1252   |      2       |
|      Shila White       |   516    |      1       |
|        Yuk Vega        |   1475   |      1       |
|      Eliana Silva      |   1264   |      1       |
|      Thalia Horne      |   1472   |      1       |
|      Rey Lindsay       |   1370   |      1       |
|     Merlene Vinson     |   1539   |      3       |
|     Merlene Vinson     |   1047   |      3       |
|     Merlene Vinson     |   531    |      3       |
|     Dacia William      |   173    |      2       |
|     Dacia William      |   158    |      2       |
|        Le Wood         |   617    |      1       |
|     Thalia Dillard     |   1606   |      2       |
|     Thalia Dillard     |   741    |      2       |
|       Luz House        |   907    |      2       |
|       Luz House        |   1499   |      2       |
|       Lucy Woods       |   1557   |      2       |
|       Lucy Woods       |   177    |      2       |
|      Shena Carter      |   1364   |      1       |
|      Robena Hill       |   1605   |      2       |
|      Robena Hill       |   1280   |      2       |
|      Jeni Booker       |   1574   |      2       |
|      Jeni Booker       |   738    |      2       |
|     Herlinda Stone     |   1021   |      1       |
|     Lavina Dejesus     |   1425   |      1       |
|    Erlinda Nielsen     |   197    |      1       |
|     Terrance Lynn      |   1284   |      1       |
|     Walton Dejesus     |   938    |      1       |
|      Wes Stanton       |   626    |      1       |
|    Tanesha Hampton     |   618    |      1       |
|       Boyd Irwin       |   372    |      1       |
|    Delbert Wilkins     |   287    |      1       |
|      Brianna Moss      |   184    |      1       |
|    Dorthey Jackson     |   770    |      2       |
|    Dorthey Jackson     |   1614   |      2       |
|      Sarita Parks      |   1615   |      2       |
|      Sarita Parks      |   1346   |      2       |
|     Shonta Mercer      |   743    |      1       |
|      Jone Bernard      |   1590   |      2       |
|      Jone Bernard      |   944    |      2       |
|    Wanita Davenport    |   1461   |      1       |
|     Cleopatra Tate     |   1055   |      1       |
|      Ramiro Byers      |   766    |      1       |
|    Nicholas Vazquez    |   950    |      1       |
|      Janae Doyle       |   1121   |      1       |
|       Hans Price       |   395    |      1       |
|      Miquel Neal       |   249    |      1       |
|     Stefany Potter     |   1399   |      1       |
|    Bernetta Marquez    |   732    |      1       |
|     Julee Woodard      |   500    |      1       |
|     Meredith Bryan     |   439    |      1       |
|     Weldon Michael     |   250    |      1       |
|    Joesph Delacruz     |    60    |      2       |
|    Joesph Delacruz     |   1500   |      2       |
|     Katherina Odom     |   1467   |      1       |
|    Laraine Robbins     |   810    |      2       |
|    Laraine Robbins     |   429    |      2       |
|     Jenise Preston     |   796    |      1       |
|       Lory Page        |   513    |      1       |
|    Charlyn Cantrell    |   308    |      1       |
|    Carola Rodriquez    |   1585   |      2       |
|    Carola Rodriquez    |   224    |      2       |
|     Alane Kennedy      |   291    |      1       |
|      Regina Burns      |   282    |      1       |
|      Omer Estrada      |   579    |      1       |
|    Crystle Gilliam     |   1030   |      1       |
|       Kam Wilder       |   858    |      1       |
|    Margert Stevens     |   632    |      1       |
|     Tomika Larson      |    37    |      1       |
|      Jeromy Burch      |   1591   |      2       |
|      Jeromy Burch      |   1275   |      2       |
|       Lena Mills       |   744    |      1       |
|    Loreta Johnston     |   945    |      1       |
|    Nettie Mcdaniel     |   1017   |      1       |
|       Karla Kirk       |   1547   |      2       |
|       Karla Kirk       |   432    |      2       |
|    Regine Gonzales     |   1548   |      2       |
|    Regine Gonzales     |   142    |      2       |
|      Miriam Baker      |   890    |      1       |
|    Jeanie Kirkland     |   1554   |      2       |
|    Jeanie Kirkland     |   987    |      2       |
|   Marquerite Dawson    |   712    |      1       |
|      Babara Ochoa      |   1013   |      1       |
|       Nova Hess        |   1518   |      2       |
|       Nova Hess        |    4     |      2       |
|    Carley Reynolds     |   1586   |      2       |
|    Carley Reynolds     |   392    |      2       |
|    Carissa Foreman     |   854    |      1       |
|     Genoveva Tyler     |   572    |      1       |
|      Deane Sears       |   903    |      1       |
|      Karey Steele      |   1477   |      1       |
|      Olevia Pitts      |   283    |      2       |
|      Olevia Pitts      |   1488   |      2       |
|   Jenniffer Bullock    |   1060   |      1       |
|    Jeniffer Ratliff    |   187    |      1       |
|     Klara Stanley      |   736    |      1       |
|       Morton Lee       |   1045   |      1       |
|      Ken Charles       |   1191   |      1       |
|      Hedwig Paul       |   1540   |      2       |
|      Hedwig Paul       |   362    |      2       |
|      Sharla Flynn      |   909    |      2       |
|      Sharla Flynn      |   1581   |      2       |
|     Damian Dawson      |   1054   |      1       |
|       Toya Pratt       |   651    |      1       |
|    Graciela Barber     |   492    |      2       |
|    Graciela Barber     |   1580   |      2       |
|      Bong Hebert       |   1568   |      2       |
|      Bong Hebert       |   1194   |      2       |
|     Ayanna Rhodes      |   496    |      1       |
|    Dorine Roberson     |   1489   |      2       |
|    Dorine Roberson     |   1049   |      2       |
|       Addie Hahn       |   1428   |      1       |
|    Edythe Valencia     |   882    |      1       |
|      Andy O'neill      |   458    |      1       |
|       Luis Tyler       |   1063   |      1       |
|     Clelia Workman     |   382    |      1       |
|     Ashely Holmes      |   719    |      1       |
|     Candis Harding     |   1201   |      1       |
|      Marni Bolton      |   290    |      1       |
|     Minerva Decker     |   1333   |      1       |
|       Alpha King       |    97    |      1       |
|     Harris Pittman     |   160    |      1       |
|    Stephaine Riddle    |   236    |      1       |
|   Michel Blankenship   |   713    |      1       |
|      Denis Logan       |   1503   |      2       |
|      Denis Logan       |    62    |      2       |
|     Jutta Everett      |   1051   |      1       |
|   Priscilla Wilkins    |   1235   |      1       |
|     Gilma Dejesus      |   309    |      1       |

### Task 5: Retrieve products with stock quantities less than 50.

In [58]:
%%sql
SELECT p.product_name, s.quantity
FROM products p
JOIN stocks s ON p.product_id = s.product_id
WHERE s.quantity < 50;

Running query in 'mysql+pymysql://root:***@localhost/bike_zeyad'

939 rows affected.

+-------------------------------------------------------+----------+
|                      product_name                     | quantity |
+-------------------------------------------------------+----------+
|                    Trek 820 - 2016                    |    27    |
|                    Trek 820 - 2016                    |    14    |
|                    Trek 820 - 2016                    |    14    |
|           Ritchey Timberwolf Frameset - 2016          |    5     |
|           Ritchey Timberwolf Frameset - 2016          |    16    |
|           Ritchey Timberwolf Frameset - 2016          |    24    |
|            Surly Wednesday Frameset - 2016            |    6     |
|            Surly Wednesday Frameset - 2016            |    28    |
|            Surly Wednesday Frameset - 2016            |    0     |
|                Trek Fuel EX 8 29 - 2016               |    23    |
|                Trek Fuel EX 8 29 - 2016               |    2     |
|                Trek Fuel EX 8 29 - 2016               |    11    |
|              Heller Shagamaw Frame - 2016             |    22    |
|              Heller Shagamaw Frame - 2016             |    1     |
|              Heller Shagamaw Frame - 2016             |    3     |
|         Surly Ice Cream Truck Frameset - 2016         |    0     |
|         Surly Ice Cream Truck Frameset - 2016         |    11    |
|         Surly Ice Cream Truck Frameset - 2016         |    27    |
|                Trek Slash 8 27.5 - 2016               |    8     |
|                Trek Slash 8 27.5 - 2016               |    8     |
|                Trek Slash 8 27.5 - 2016               |    12    |
|         Trek Remedy 29 Carbon Frameset - 2016         |    0     |
|         Trek Remedy 29 Carbon Frameset - 2016         |    1     |
|         Trek Remedy 29 Carbon Frameset - 2016         |    12    |
|                  Trek Conduit+ - 2016                 |    11    |
|                  Trek Conduit+ - 2016                 |    17    |
|                  Trek Conduit+ - 2016                 |    23    |
|                 Surly Straggler - 2016                |    15    |
|                 Surly Straggler - 2016                |    13    |
|                 Surly Straggler - 2016                |    21    |
|              Surly Straggler 650b - 2016              |    8     |
|              Surly Straggler 650b - 2016              |    21    |
|              Surly Straggler 650b - 2016              |    30    |
|           Electra Townie Original 21D - 2016          |    16    |
|           Electra Townie Original 21D - 2016          |    2     |
|           Electra Townie Original 21D - 2016          |    30    |
|           Electra Cruiser 1 (24-Inch) - 2016          |    13    |
|           Electra Cruiser 1 (24-Inch) - 2016          |    1     |
|           Electra Cruiser 1 (24-Inch) - 2016          |    19    |
|     Electra Girl's Hawaii 1 (16-inch) - 2015/2016     |    8     |
|     Electra Girl's Hawaii 1 (16-inch) - 2015/2016     |    18    |
|     Electra Girl's Hawaii 1 (16-inch) - 2015/2016     |    4     |
|                 Electra Moto 1 - 2016                 |    3     |
|                 Electra Moto 1 - 2016                 |    6     |
|                 Electra Moto 1 - 2016                 |    22    |
|          Electra Townie Original 7D EQ - 2016         |    4     |
|          Electra Townie Original 7D EQ - 2016         |    20    |
|          Electra Townie Original 7D EQ - 2016         |    19    |
|            Pure Cycles Vine 8-Speed - 2016            |    2     |
|            Pure Cycles Vine 8-Speed - 2016            |    3     |
|            Pure Cycles Vine 8-Speed - 2016            |    22    |
|   Pure Cycles Western 3-Speed - Women's - 2015/2016   |    16    |
|   Pure Cycles Western 3-Speed - Women's - 2015/2016   |    13    |
|   Pure Cycles Western 3-Speed - Women's - 2015/2016   |    5     |
|           Pure Cycles William 3-Speed - 2016          |    4     |
|           Pure Cycles William 3-Speed - 2016          |    15    |
|           Pure Cycles William 3-Speed - 2016          |    24    |
|     Electra Townie Original 7D EQ - Women's - 2016    |    26    |
|     Electra Townie Original 7D EQ - Women's - 2016    |    20    |
|     Electra Townie Original 7D EQ - Women's - 2016    |    19    |
|           Electra Cruiser 1 (24-Inch) - 2016          |    24    |
|           Electra Cruiser 1 (24-Inch) - 2016          |    16    |
|           Electra Cruiser 1 (24-Inch) - 2016          |    8     |
|     Electra Girl's Hawaii 1 (16-inch) - 2015/2016     |    29    |
|     Electra Girl's Hawaii 1 (16-inch) - 2015/2016     |    0     |
|     Electra Girl's Hawaii 1 (16-inch) - 2015/2016     |    20    |
|     Electra Girl's Hawaii 1 (20-inch) - 2015/2016     |    9     |
|     Electra Girl's Hawaii 1 (20-inch) - 2015/2016     |    12    |
|     Electra Girl's Hawaii 1 (20-inch) - 2015/2016     |    8     |
|           Electra Townie Original 21D - 2016          |    10    |
|           Electra Townie Original 21D - 2016          |    16    |
|           Electra Townie Original 21D - 2016          |    18    |
|         Electra Townie Original 7D - 2015/2016        |    10    |
|         Electra Townie Original 7D - 2015/2016        |    18    |
|         Electra Townie Original 7D - 2015/2016        |    15    |
|          Electra Townie Original 7D EQ - 2016         |    16    |
|          Electra Townie Original 7D EQ - 2016         |    2     |
|          Electra Townie Original 7D EQ - 2016         |    27    |
|            Surly Big Dummy Frameset - 2017            |    21    |
|            Surly Big Dummy Frameset - 2017            |    10    |
|            Surly Big Dummy Frameset - 2017            |    21    |
|       Surly Karate Monkey 27.5+ Frameset - 2017       |    20    |
|       Surly Karate Monkey 27.5+ Frameset - 2017       |    25    |
|       Surly Karate Monkey 27.5+ Frameset - 2017       |    20    |
|                Trek X-Caliber 8 - 2017                |    13    |
|                Trek X-Caliber 8 - 2017                |    29    |
|                Trek X-Caliber 8 - 2017                |    11    |
|         Surly Ice Cream Truck Frameset - 2017         |    30    |
|         Surly Ice Cream Truck Frameset - 2017         |    17    |
|         Surly Ice Cream Truck Frameset - 2017         |    23    |
|                 Surly Wednesday - 2017                |    2     |
|                 Surly Wednesday - 2017                |    10    |
|                 Surly Wednesday - 2017                |    10    |
|           Trek Farley Alloy Frameset - 2017           |    0     |
|           Trek Farley Alloy Frameset - 2017           |    13    |
|           Trek Farley Alloy Frameset - 2017           |    14    |
|            Surly Wednesday Frameset - 2017            |    10    |
|            Surly Wednesday Frameset - 2017            |    8     |
|            Surly Wednesday Frameset - 2017            |    14    |
|      Trek Session DH 27.5 Carbon Frameset - 2017      |    2     |
|      Trek Session DH 27.5 Carbon Frameset - 2017      |    24    |
|      Trek Session DH 27.5 Carbon Frameset - 2017      |    6     |
|             Sun Bicycles Spider 3i - 2017             |    18    |
|             Sun Bicycles Spider 3i - 2017             |    25    |
|             Sun Bicycles Spider 3i - 2017             |    3     |
|              Surly Troll Frameset - 2017              |    26    |
|              Surly Troll Frameset - 2017              |    15    |
|              Surly Troll Frameset - 2017              |    28    |
|             Haro Flightline One ST - 2017             |    12    |
|             Haro Flightline One ST - 2017             |    5     |
|             Haro Flightline One ST - 2017             |    30    |
|           Haro Flightline Two 26 Plus - 2017          |    13    |
|           Haro Flightline Two 26 Plus - 2017          |    18    |
|           Haro Flightline Two 26 Plus - 2017          |    23    |
|                  Trek Stache 5 - 2017                 |    2     |
|                  Trek Stache 5 - 2017                 |    28    |
|                  Trek Stache 5 - 2017                 |    22    |
|               Trek Fuel EX 9.8 29 - 2017              |    24    |
|               Trek Fuel EX 9.8 29 - 2017              |    15    |
|               Trek Fuel EX 9.8 29 - 2017              |    2     |
|                  Haro Shift R3 - 2017                 |    10    |
|                  Haro Shift R3 - 2017                 |    6     |
|                  Haro Shift R3 - 2017                 |    25    |
|            Trek Fuel EX 5 27.5 Plus - 2017            |    0     |
|            Trek Fuel EX 5 27.5 Plus - 2017            |    16    |
|            Trek Fuel EX 5 27.5 Plus - 2017            |    9     |
|           Trek Fuel EX 9.8 27.5 Plus - 2017           |    2     |
|           Trek Fuel EX 9.8 27.5 Plus - 2017           |    2     |
|           Trek Fuel EX 9.8 27.5 Plus - 2017           |    26    |
|                   Haro SR 1.1 - 2017                  |    1     |
|                   Haro SR 1.1 - 2017                  |    24    |
|                   Haro SR 1.1 - 2017                  |    26    |
|                   Haro SR 1.2 - 2017                  |    15    |
|                   Haro SR 1.2 - 2017                  |    13    |
|                   Haro SR 1.2 - 2017                  |    1     |
|                   Haro SR 1.3 - 2017                  |    19    |
|                   Haro SR 1.3 - 2017                  |    18    |
|                   Haro SR 1.3 - 2017                  |    16    |
|                 Trek Remedy 9.8 - 2017                |    21    |
|                 Trek Remedy 9.8 - 2017                |    0     |
|                 Trek Remedy 9.8 - 2017                |    14    |
|                 Trek Emonda S 4 - 2017                |    5     |
|                 Trek Emonda S 4 - 2017                |    20    |
|                 Trek Emonda S 4 - 2017                |    2     |
|                Trek Domane SL 6 - 2017                |    8     |
|                Trek Domane SL 6 - 2017                |    4     |
|                Trek Domane SL 6 - 2017                |    4     |
|            Trek Silque SLR 7 Women's - 2017           |    29    |
|            Trek Silque SLR 7 Women's - 2017           |    7     |
|            Trek Silque SLR 7 Women's - 2017           |    25    |
|            Trek Silque SLR 8 Women's - 2017           |    2     |
|            Trek Silque SLR 8 Women's - 2017           |    8     |
|            Trek Silque SLR 8 Women's - 2017           |    2     |
|                Surly Steamroller - 2017               |    18    |
|                Surly Steamroller - 2017               |    23    |
|                Surly Steamroller - 2017               |    8     |
|               Surly Ogre Frameset - 2017              |    17    |
|               Surly Ogre Frameset - 2017              |    19    |
|               Surly Ogre Frameset - 2017              |    6     |
|          Trek Domane SL Disc Frameset - 2017          |    11    |
|          Trek Domane SL Disc Frameset - 2017          |    6     |
|          Trek Domane SL Disc Frameset - 2017          |    13    |
|                 Trek Domane S 6 - 2017                |    11    |
|                 Trek Domane S 6 - 2017                |    5     |
|                 Trek Domane S 6 - 2017                |    5     |
|             Trek Domane SLR 6 Disc - 2017             |    15    |
|             Trek Domane SLR 6 Disc - 2017             |    20    |
|             Trek Domane SLR 6 Disc - 2017             |    19    |
|                 Trek Emonda S 5 - 2017                |    1     |
|                 Trek Emonda S 5 - 2017                |    27    |
|                 Trek Emonda S 5 - 2017                |    9     |
|                 Trek Madone 9.2 - 2017                |    1     |
|                 Trek Madone 9.2 - 2017                |    15    |
|                 Trek Madone 9.2 - 2017                |    27    |
|              Trek Domane S 5 Disc - 2017              |    22    |
|              Trek Domane S 5 Disc - 2017              |    17    |
|              Trek Domane S 5 Disc - 2017              |    0     |
|            Sun Bicycles ElectroLite - 2017            |    19    |
|            Sun Bicycles ElectroLite - 2017            |    1     |
|            Sun Bicycles ElectroLite - 2017            |    7     |
|             Trek Powerfly 8 FS Plus - 2017            |    30    |
|             Trek Powerfly 8 FS Plus - 2017            |    20    |
|             Trek Powerfly 8 FS Plus - 2017            |    28    |
|                  Trek Boone 7 - 2017                  |    21    |
|                  Trek Boone 7 - 2017                  |    4     |
|                  Trek Boone 7 - 2017                  |    4     |
|          Trek Boone Race Shop Limited - 2017          |    4     |
|          Trek Boone Race Shop Limited - 2017          |    5     |
|          Trek Boone Race Shop Limited - 2017          |    8     |
|           Electra Townie Original 7D - 2017           |    30    |
|           Electra Townie Original 7D - 2017           |    30    |
|           Electra Townie Original 7D - 2017           |    22    |
|          Sun Bicycles Lil Bolt Type-R - 2017          |    10    |
|          Sun Bicycles Lil Bolt Type-R - 2017          |    16    |
|          Sun Bicycles Lil Bolt Type-R - 2017          |    1     |
|           Sun Bicycles Revolutions 24 - 2017          |    12    |
|           Sun Bicycles Revolutions 24 - 2017          |    22    |
|           Sun Bicycles Revolutions 24 - 2017          |    3     |
|      Sun Bicycles Revolutions 24 - Girl's - 2017      |    19    |
|      Sun Bicycles Revolutions 24 - Girl's - 2017      |    8     |
|      Sun Bicycles Revolutions 24 - Girl's - 2017      |    6     |
|               Sun Bicycles Cruz 3 - 2017              |    30    |
|               Sun Bicycles Cruz 3 - 2017              |    23    |
|               Sun Bicycles Cruz 3 - 2017              |    18    |
|               Sun Bicycles Cruz 7 - 2017              |    4     |
|               Sun Bicycles Cruz 7 - 2017              |    22    |
|               Sun Bicycles Cruz 7 - 2017              |    29    |
|       Electra Amsterdam Original 3i - 2015/2017       |    3     |
|       Electra Amsterdam Original 3i - 2015/2017       |    6     |
|       Electra Amsterdam Original 3i - 2015/2017       |    2     |
|            Sun Bicycles Atlas X-Type - 2017           |    25    |
|            Sun Bicycles Atlas X-Type - 2017           |    30    |
|            Sun Bicycles Atlas X-Type - 2017           |    13    |
|         Sun Bicycles Biscayne Tandem 7 - 2017         |    9     |
|         Sun Bicycles Biscayne Tandem 7 - 2017         |    1     |
|         Sun Bicycles Biscayne Tandem 7 - 2017         |    6     |
|         Sun Bicycles Brickell Tandem 7 - 2017         |    7     |
|         Sun Bicycles Brickell Tandem 7 - 2017         |    20    |
|         Sun Bicycles Brickell Tandem 7 - 2017         |    3     |
|              Electra Cruiser Lux 1 - 2017             |    9     |
|              Electra Cruiser Lux 1 - 2017             |    23    |
|              Electra Cruiser Lux 1 - 2017             |    17    |
|      Electra Cruiser Lux Fat Tire 1 Ladies - 2017     |    23    |
|      Electra Cruiser Lux Fat Tire 1 Ladies - 2017     |    11    |
|      Electra Cruiser Lux Fat Tire 1 Ladies - 2017     |    29    |
|           Electra Girl's Hawaii 1 16" - 2017          |    15    |
|           Electra Girl's Hawaii 1 16" - 2017          |    20    |
|           Electra Girl's Hawaii 1 16" - 2017          |    23    |
|          Electra Glam Punk 3i Ladies' - 2017          |    16    |
|          Electra Glam Punk 3i Ladies' - 2017          |    25    |
|          Electra Glam Punk 3i Ladies' - 2017          |    23    |
|         Sun Bicycles Biscayne Tandem CB - 2017        |    13    |
|         Sun Bicycles Biscayne Tandem CB - 2017        |    4     |
|         Sun Bicycles Biscayne Tandem CB - 2017        |    19    |
|     Sun Bicycles Boardwalk (24-inch Wheels) - 2017    |    13    |
|     Sun Bicycles Boardwalk (24-inch Wheels) - 2017    |    29    |
|     Sun Bicycles Boardwalk (24-inch Wheels) - 2017    |    29    |
|         Sun Bicycles Brickell Tandem CB - 2017        |    11    |
|         Sun Bicycles Brickell Tandem CB - 2017        |    27    |
|         Sun Bicycles Brickell Tandem CB - 2017        |    22    |
|      Electra Amsterdam Fashion 7i Ladies' - 2017      |    25    |
|      Electra Amsterdam Fashion 7i Ladies' - 2017      |    19    |
|      Electra Amsterdam Fashion 7i Ladies' - 2017      |    18    |
|      Electra Amsterdam Original 3i Ladies' - 2017     |    1     |
|      Electra Amsterdam Original 3i Ladies' - 2017     |    4     |
|      Electra Amsterdam Original 3i Ladies' - 2017     |    7     |
|            Trek Boy's Kickster - 2015/2017            |    13    |
|            Trek Boy's Kickster - 2015/2017            |    21    |
|            Trek Boy's Kickster - 2015/2017            |    23    |
|             Sun Bicycles Lil Kitt'n - 2017            |    11    |
|             Sun Bicycles Lil Kitt'n - 2017            |    22    |
|             Sun Bicycles Lil Kitt'n - 2017            |    15    |
|                Haro Downtown 16 - 2017                |    23    |
|                Haro Downtown 16 - 2017                |    6     |
|                Haro Downtown 16 - 2017                |    15    |
|              Trek Girl's Kickster - 2017              |    19    |
|              Trek Girl's Kickster - 2017              |    24    |
|              Trek Girl's Kickster - 2017              |    27    |
|             Trek Precaliber 12 Boys - 2017            |    27    |
|             Trek Precaliber 12 Boys - 2017            |    14    |
|             Trek Precaliber 12 Boys - 2017            |    16    |
|            Trek Precaliber 12 Girls - 2017            |    7     |
|            Trek Precaliber 12 Girls - 2017            |    8     |
|            Trek Precaliber 12 Girls - 2017            |    28    |
|             Trek Precaliber 16 Boys - 2017            |    9     |
|             Trek Precaliber 16 Boys - 2017            |    8     |
|             Trek Precaliber 16 Boys - 2017            |    22    |
|            Trek Precaliber 16 Girls - 2017            |    4     |
|            Trek Precaliber 16 Girls - 2017            |    26    |
|            Trek Precaliber 16 Girls - 2017            |    9     |
|      Trek Precaliber 24 (21-Speed) - Girls - 2017     |    8     |
|      Trek Precaliber 24 (21-Speed) - Girls - 2017     |    0     |
|      Trek Precaliber 24 (21-Speed) - Girls - 2017     |    8     |
|                Haro Shredder 20 - 2017                |    0     |
|                Haro Shredder 20 - 2017                |    22    |
|                Haro Shredder 20 - 2017                |    28    |
|             Haro Shredder 20 Girls - 2017             |    22    |
|             Haro Shredder 20 Girls - 2017             |    22    |
|             Haro Shredder 20 Girls - 2017             |    18    |
|              Haro Shredder Pro 20 - 2017              |    6     |
|              Haro Shredder Pro 20 - 2017              |    2     |
|              Haro Shredder Pro 20 - 2017              |    15    |
|           Electra Girl's Hawaii 1 16" - 2017          |    25    |
|           Electra Girl's Hawaii 1 16" - 2017          |    10    |
|           Electra Girl's Hawaii 1 16" - 2017          |    14    |
|        Electra Moto 3i (20-inch) - Boy's - 2017       |    20    |

---

## Level 3: Advanced â€“ Complex Joins and Subqueries
(using Pandas read_sql)

### Task 1: Retrieve the Top 5 Products with the Highest Total Sales Revenue

In [60]:
%%sql
SELECT p.product_name, 
       SUM(oi.quantity * oi.list_price) AS total_revenue
FROM products p
JOIN order_items oi ON p.product_id = oi.product_id
GROUP BY p.product_id, p.product_name
ORDER BY total_revenue DESC
LIMIT 5;

Running query in 'mysql+pymysql://root:***@localhost/bike_zeyad'

5 rows affected.

+-------------------------------+---------------+
|          product_name         | total_revenue |
+-------------------------------+---------------+
|    Trek Slash 8 27.5 - 2016   |   615998.46   |
|      Trek Conduit+ - 2016     |   434998.55   |
|    Trek Fuel EX 8 29 - 2016   |   414698.57   |
|  Surly Straggler 650b - 2016  |   253829.49   |
| Trek Domane SLR 6 Disc - 2017 |   236499.57   |
+-------------------------------+---------------+

### Task 2: Find the Customers Who Placed the Most Orders in June, November 2018

In [62]:
%%sql
SELECT c.first_name, c.last_name, 
       COUNT(o.order_id) AS order_count
FROM customers c
JOIN orders o ON c.customer_id = o.customer_id
WHERE (MONTH(o.order_date) = 6 AND YEAR(o.order_date) = 2018)
   OR (MONTH(o.order_date) = 11 AND YEAR(o.order_date) = 2018)
GROUP BY c.customer_id, c.first_name, c.last_name
ORDER BY order_count DESC;

Running query in 'mysql+pymysql://root:***@localhost/bike_zeyad'

3 rows affected.

+------------+-----------+-------------+
| first_name | last_name | order_count |
+------------+-----------+-------------+
|  Latasha   |    Hays   |      1      |
|  Dorthey   |  Jackson  |      1      |
|   Debra    |   Burks   |      1      |
+------------+-----------+-------------+

### Task 3: List All Stores with Their Total Stock Quantities for All Products

In [64]:
%%sql
SELECT s.store_name, 
       SUM(st.quantity) AS total_stock
FROM stores s
JOIN stocks st ON s.store_id = st.store_id
GROUP BY s.store_name
ORDER BY s.store_name;

Running query in 'mysql+pymysql://root:***@localhost/bike_zeyad'

3 rows affected.

+------------------+-------------+
|    store_name    | total_stock |
+------------------+-------------+
|  Baldwin Bikes   |     4359    |
|  Rowlett Bikes   |     4620    |
| Santa Cruz Bikes |     4532    |
+------------------+-------------+

### Task 4: Retrieve Staff Members Who Work at Stores Located in a Specific State
California (CA) , New York (NY) , Texas (TX)

In [66]:
%%sql
SELECT s.staff_id, s.first_name, s.last_name, st.store_name, st.state
FROM staffs s
JOIN stores st ON s.store_id = st.store_id
WHERE st.state IN ('CA', 'NY', 'TX');

Running query in 'mysql+pymysql://root:***@localhost/bike_zeyad'

10 rows affected.

+----------+------------+-----------+------------------+-------+
| staff_id | first_name | last_name |    store_name    | state |
+----------+------------+-----------+------------------+-------+
|    1     |  Fabiola   |  Jackson  | Santa Cruz Bikes |   CA  |
|    2     |   Mireya   |  Copeland | Santa Cruz Bikes |   CA  |
|    3     |   Genna    |  Serrano  | Santa Cruz Bikes |   CA  |
|    4     |   Virgie   |  Wiggins  | Santa Cruz Bikes |   CA  |
|    5     |  Jannette  |   David   |  Baldwin Bikes   |   NY  |
|    6     | Marcelene  |   Boyer   |  Baldwin Bikes   |   NY  |
|    7     |   Venita   |   Daniel  |  Baldwin Bikes   |   NY  |
|    8     |    Kali    |   Vargas  |  Rowlett Bikes   |   TX  |
|    9     |   Layla    |  Terrell  |  Rowlett Bikes   |   TX  |
|    10    | Bernardine |  Houston  |  Rowlett Bikes   |   TX  |
+----------+------------+-----------+------------------+-------+

### Task 5: Identify the Categories of Products with the Highest Total Revenue

In [68]:
%%sql
SELECT c.category_name, 
       SUM(oi.quantity * oi.list_price) AS total_revenue
FROM categories c
JOIN products p ON c.category_id = p.category_id
JOIN order_items oi ON p.product_id = oi.product_id
GROUP BY c.category_name
ORDER BY total_revenue DESC
LIMIT 1;

Running query in 'mysql+pymysql://root:***@localhost/bike_zeyad'

1 rows affected.

+----------------+---------------+
| category_name  | total_revenue |
+----------------+---------------+
| Mountain Bikes |   3030775.71  |
+----------------+---------------+

---
## Level 4: Expert â€“ Advanced Analytical Queries
(using Pandas read_sql)

### Task 1: Find the Store with the Highest Total Revenue
Retrieve the store name and total revenue (sum of list_price * quantity) across all orders.

In [70]:
%%sql
SELECT st.store_name, SUM(oi.quantity * oi.list_price) AS total_revenue
FROM stores st
JOIN orders o ON st.store_id = o.store_id
JOIN order_items oi ON o.order_id = oi.order_id
GROUP BY st.store_name
ORDER BY total_revenue DESC
LIMIT 1;

Running query in 'mysql+pymysql://root:***@localhost/bike_zeyad'

1 rows affected.

+---------------+---------------+
|   store_name  | total_revenue |
+---------------+---------------+
| Baldwin Bikes |   5826242.21  |
+---------------+---------------+

### Task 2: Find all products that have never been ordered.

In [72]:
%%sql
SELECT p.product_id, p.product_name
FROM products p
LEFT JOIN order_items oi ON p.product_id = oi.product_id
WHERE oi.product_id IS NULL;

Running query in 'mysql+pymysql://root:***@localhost/bike_zeyad'

14 rows affected.

+------------+------------------------------------------------+
| product_id |                  product_name                  |
+------------+------------------------------------------------+
|     1      |                Trek 820 - 2016                 |
|    121     |         Surly Krampus Frameset - 2018          |
|    125     |          Trek Kids' Dual Sport - 2018          |
|    154     |     Trek Domane SLR 6 Disc Women's - 2018      |
|    195     |      Electra Townie Go! 8i Ladies' - 2018      |
|    267     |        Trek Precaliber 12 Girl's - 2018        |
|    284     |  Electra Savannah 1 (20-inch) - Girl's - 2018  |
|    291     | Electra Sweet Ride 1 (20-inch) - Girl's - 2018 |
|    316     |      Trek Checkpoint ALR 4 Women's - 2019      |
|    317     |          Trek Checkpoint ALR 5 - 2019          |
|    318     |      Trek Checkpoint ALR 5 Women's - 2019      |
|    319     |      Trek Checkpoint SL 5 Women's - 2019       |
|    320     |          Trek Checkpoint SL 6 - 2019           |
|    321     |      Trek Checkpoint ALR Frameset - 2019       |
+------------+------------------------------------------------+

### Task 3: Identify the Customers Who Placed the Fewest Orders
Retrieve customer names and their total order counts, ordered in ascending order of order count.

In [74]:
%%sql
SELECT c.customer_id, c.first_name, c.last_name ,
       COUNT(o.order_id) AS total_orders
FROM customers c
JOIN orders o ON c.customer_id = o.customer_id
GROUP BY c.customer_id, c.first_name, c.last_name
ORDER BY total_orders, c.customer_id ASC
LIMIT 5;

Running query in 'mysql+pymysql://root:***@localhost/bike_zeyad'

5 rows affected.

+-------------+------------+------------+--------------+
| customer_id | first_name | last_name  | total_orders |
+-------------+------------+------------+--------------+
|      95     |  Letitia   |   Franco   |      1       |
|      96     |  Floretta  |  Higgins   |      1       |
|      98     |   Violet   | Valenzuela |      1       |
|      99     |   Carie    |    Kidd    |      1       |
|     100     |   Kellie   |   Franco   |      1       |
+-------------+------------+------------+--------------+

### Task 4: Analyze Monthly Revenue for the Last Year (Specific to 2017)

In [76]:
%%sql
SELECT MONTH(o.order_date) AS month, 
       SUM(oi.quantity * oi.list_price) AS total_revenue
FROM orders o
JOIN order_items oi ON o.order_id = oi.order_id
WHERE YEAR(o.order_date) = 2017
GROUP BY MONTH(o.order_date)
ORDER BY month;

Running query in 'mysql+pymysql://root:***@localhost/bike_zeyad'

12 rows affected.

+-------+---------------+
| month | total_revenue |
+-------+---------------+
|   1   |   316954.77   |
|   2   |   348740.47   |
|   3   |   348177.13   |
|   4   |   254105.57   |
|   5   |   297754.66   |
|   6   |   419892.07   |
|   7   |   255727.63   |
|   8   |   322553.32   |
|   9   |   329388.68   |
|   10  |   345316.18   |
|   11  |   315881.67   |
|   12  |   291022.87   |
+-------+---------------+

### Task 5: Find Products That Are Low in Stock Across All Stores
Identify products where the total stock quantity (across all stores) is less than 100.

In [78]:
%%sql
SELECT p.product_id, p.product_name, 
       SUM(s.quantity) AS all_stores_stock
FROM products p
JOIN stocks s ON p.product_id = s.product_id
GROUP BY p.product_id, p.product_name
HAVING all_stores_stock < 100;

Running query in 'mysql+pymysql://root:***@localhost/bike_zeyad'

313 rows affected.

+------------+-------------------------------------------------------+------------------+
| product_id |                      product_name                     | all_stores_stock |
+------------+-------------------------------------------------------+------------------+
|     1      |                    Trek 820 - 2016                    |        55        |
|     2      |           Ritchey Timberwolf Frameset - 2016          |        45        |
|     3      |            Surly Wednesday Frameset - 2016            |        34        |
|     4      |                Trek Fuel EX 8 29 - 2016               |        36        |
|     5      |              Heller Shagamaw Frame - 2016             |        26        |
|     6      |         Surly Ice Cream Truck Frameset - 2016         |        38        |
|     7      |                Trek Slash 8 27.5 - 2016               |        28        |
|     8      |         Trek Remedy 29 Carbon Frameset - 2016         |        13        |
|     9      |                  Trek Conduit+ - 2016                 |        51        |
|     10     |                 Surly Straggler - 2016                |        49        |
|     11     |              Surly Straggler 650b - 2016              |        59        |
|     12     |           Electra Townie Original 21D - 2016          |        48        |
|     13     |           Electra Cruiser 1 (24-Inch) - 2016          |        33        |
|     14     |     Electra Girl's Hawaii 1 (16-inch) - 2015/2016     |        30        |
|     15     |                 Electra Moto 1 - 2016                 |        31        |
|     16     |          Electra Townie Original 7D EQ - 2016         |        43        |
|     17     |            Pure Cycles Vine 8-Speed - 2016            |        27        |
|     18     |   Pure Cycles Western 3-Speed - Women's - 2015/2016   |        34        |
|     19     |           Pure Cycles William 3-Speed - 2016          |        43        |
|     20     |     Electra Townie Original 7D EQ - Women's - 2016    |        65        |
|     21     |           Electra Cruiser 1 (24-Inch) - 2016          |        48        |
|     22     |     Electra Girl's Hawaii 1 (16-inch) - 2015/2016     |        49        |
|     23     |     Electra Girl's Hawaii 1 (20-inch) - 2015/2016     |        29        |
|     24     |           Electra Townie Original 21D - 2016          |        44        |
|     25     |         Electra Townie Original 7D - 2015/2016        |        43        |
|     26     |          Electra Townie Original 7D EQ - 2016         |        45        |
|     27     |            Surly Big Dummy Frameset - 2017            |        52        |
|     28     |       Surly Karate Monkey 27.5+ Frameset - 2017       |        65        |
|     29     |                Trek X-Caliber 8 - 2017                |        53        |
|     30     |         Surly Ice Cream Truck Frameset - 2017         |        70        |
|     31     |                 Surly Wednesday - 2017                |        22        |
|     32     |           Trek Farley Alloy Frameset - 2017           |        27        |
|     33     |            Surly Wednesday Frameset - 2017            |        32        |
|     34     |      Trek Session DH 27.5 Carbon Frameset - 2017      |        32        |
|     35     |             Sun Bicycles Spider 3i - 2017             |        46        |
|     36     |              Surly Troll Frameset - 2017              |        69        |
|     37     |             Haro Flightline One ST - 2017             |        47        |
|     38     |           Haro Flightline Two 26 Plus - 2017          |        54        |
|     39     |                  Trek Stache 5 - 2017                 |        52        |
|     40     |               Trek Fuel EX 9.8 29 - 2017              |        41        |
|     41     |                  Haro Shift R3 - 2017                 |        41        |
|     42     |            Trek Fuel EX 5 27.5 Plus - 2017            |        25        |
|     43     |           Trek Fuel EX 9.8 27.5 Plus - 2017           |        30        |
|     44     |                   Haro SR 1.1 - 2017                  |        51        |
|     45     |                   Haro SR 1.2 - 2017                  |        29        |
|     46     |                   Haro SR 1.3 - 2017                  |        53        |
|     47     |                 Trek Remedy 9.8 - 2017                |        35        |
|     48     |                 Trek Emonda S 4 - 2017                |        27        |
|     49     |                Trek Domane SL 6 - 2017                |        16        |
|     50     |            Trek Silque SLR 7 Women's - 2017           |        61        |
|     51     |            Trek Silque SLR 8 Women's - 2017           |        12        |
|     52     |                Surly Steamroller - 2017               |        49        |
|     53     |               Surly Ogre Frameset - 2017              |        42        |
|     54     |          Trek Domane SL Disc Frameset - 2017          |        30        |
|     55     |                 Trek Domane S 6 - 2017                |        21        |
|     56     |             Trek Domane SLR 6 Disc - 2017             |        54        |
|     57     |                 Trek Emonda S 5 - 2017                |        37        |
|     58     |                 Trek Madone 9.2 - 2017                |        43        |
|     59     |              Trek Domane S 5 Disc - 2017              |        39        |
|     60     |            Sun Bicycles ElectroLite - 2017            |        27        |
|     61     |             Trek Powerfly 8 FS Plus - 2017            |        78        |
|     62     |                  Trek Boone 7 - 2017                  |        29        |
|     63     |          Trek Boone Race Shop Limited - 2017          |        17        |
|     64     |           Electra Townie Original 7D - 2017           |        82        |
|     65     |          Sun Bicycles Lil Bolt Type-R - 2017          |        27        |
|     66     |           Sun Bicycles Revolutions 24 - 2017          |        37        |
|     67     |      Sun Bicycles Revolutions 24 - Girl's - 2017      |        33        |
|     68     |               Sun Bicycles Cruz 3 - 2017              |        71        |
|     69     |               Sun Bicycles Cruz 7 - 2017              |        55        |
|     70     |       Electra Amsterdam Original 3i - 2015/2017       |        11        |
|     71     |            Sun Bicycles Atlas X-Type - 2017           |        68        |
|     72     |         Sun Bicycles Biscayne Tandem 7 - 2017         |        16        |
|     73     |         Sun Bicycles Brickell Tandem 7 - 2017         |        30        |
|     74     |              Electra Cruiser Lux 1 - 2017             |        49        |
|     75     |      Electra Cruiser Lux Fat Tire 1 Ladies - 2017     |        63        |
|     76     |           Electra Girl's Hawaii 1 16" - 2017          |        58        |
|     77     |          Electra Glam Punk 3i Ladies' - 2017          |        64        |
|     78     |         Sun Bicycles Biscayne Tandem CB - 2017        |        36        |
|     79     |     Sun Bicycles Boardwalk (24-inch Wheels) - 2017    |        71        |
|     80     |         Sun Bicycles Brickell Tandem CB - 2017        |        60        |
|     81     |      Electra Amsterdam Fashion 7i Ladies' - 2017      |        62        |
|     82     |      Electra Amsterdam Original 3i Ladies' - 2017     |        12        |
|     83     |            Trek Boy's Kickster - 2015/2017            |        57        |
|     84     |             Sun Bicycles Lil Kitt'n - 2017            |        48        |
|     85     |                Haro Downtown 16 - 2017                |        44        |
|     86     |              Trek Girl's Kickster - 2017              |        70        |
|     87     |             Trek Precaliber 12 Boys - 2017            |        57        |
|     88     |            Trek Precaliber 12 Girls - 2017            |        43        |
|     89     |             Trek Precaliber 16 Boys - 2017            |        39        |
|     90     |            Trek Precaliber 16 Girls - 2017            |        39        |
|     91     |      Trek Precaliber 24 (21-Speed) - Girls - 2017     |        16        |
|     92     |                Haro Shredder 20 - 2017                |        50        |
|     93     |             Haro Shredder 20 Girls - 2017             |        62        |
|     94     |              Haro Shredder Pro 20 - 2017              |        23        |
|     95     |           Electra Girl's Hawaii 1 16" - 2017          |        49        |
|     96     |        Electra Moto 3i (20-inch) - Boy's - 2017       |        43        |
|     97     |     Electra Savannah 3i (20-inch) - Girl's - 2017     |        63        |
|     98     |     Electra Straight 8 3i (20-inch) - Boy's - 2017    |        47        |
|     99     |    Electra Sugar Skulls 1 (20-inch) - Girl's - 2017   |        71        |
|    100     |     Electra Townie 3i EQ (20-inch) - Boys' - 2017     |        55        |
|    101     |       Electra Townie 7D (20-inch) - Boys' - 2017      |        38        |
|    102     |           Electra Townie Original 7D - 2017           |        43        |
|    103     |            Sun Bicycles Streamway 3 - 2017            |        24        |
|    104     |             Sun Bicycles Streamway - 2017             |        73        |
|    105     |            Sun Bicycles Streamway 7 - 2017            |        11        |
|    106     |               Sun Bicycles Cruz 3 - 2017              |        38        |
|    107     |               Sun Bicycles Cruz 7 - 2017              |        60        |
|    108     |          Sun Bicycles Cruz 3 - Women's - 2017         |        67        |
|    109     |          Sun Bicycles Cruz 7 - Women's - 2017         |        79        |
|    110     |             Sun Bicycles Drifter 7 - 2017             |        19        |
|    111     |        Sun Bicycles Drifter 7 - Women's - 2017        |        46        |
|    112     |                    Trek 820 - 2018                    |        42        |
|    113     |                  Trek Marlin 5 - 2018                 |        54        |
|    114     |                  Trek Marlin 6 - 2018                 |        27        |
|    115     |                Trek Fuel EX 8 29 - 2018               |        54        |
|    116     |               Trek Marlin 7 - 2017/2018               |        71        |
|    117     |               Trek Ticket S Frame - 2018              |        56        |
|    118     |                Trek X-Caliber 8 - 2018                |        46        |
|    119     |                 Trek Kids' Neko - 2018                |        69        |
|    120     |                Trek Fuel EX 7 29 - 2018               |        64        |
|    121     |             Surly Krampus Frameset - 2018             |        26        |
|    122     |              Surly Troll Frameset - 2018              |        41        |
|    123     |           Trek Farley Carbon Frameset - 2018          |        41        |
|    124     |                  Surly Krampus - 2018                 |        38        |
|    125     |              Trek Kids' Dual Sport - 2018             |        34        |
|    126     |          Surly Big Fat Dummy Frameset - 2018          |        46        |
|    127     |             Surly Pack Rat Frameset - 2018            |        28        |
|    128     |                 Surly ECR 27.5 - 2018                 |        59        |
|    129     |                Trek X-Caliber 7 - 2018                |        52        |
|    130     |           Trek Stache Carbon Frameset - 2018          |        59        |
|    131     |             Heller Bloodhound Trail - 2018            |        52        |
|    132     |             Trek Procal AL Frameset - 2018            |        23        |
|    133     |            Trek Procaliber Frameset - 2018            |        53        |
|    134     |           Trek Remedy 27.5 C Frameset - 2018          |        56        |
|    135     |             Trek X-Caliber Frameset - 2018            |        60        |
|    136     |                Trek Procaliber 6 - 2018               |        24        |
|    137     |               Heller Shagamaw GX1 - 2018              |        30        |
|    138     |               Trek Fuel EX 5 Plus - 2018              |        39        |
|    139     |               Trek Remedy 7 27.5 - 2018               |        62        |
|    140     |              Trek Remedy 9.8 27.5 - 2018              |        19        |
|    141     |                  Trek Stache 5 - 2018                 |        53        |
|    142     |              Trek Fuel EX 8 29 XT - 2018              |        75        |
|    143     |                Trek Domane ALR 3 - 2018               |        40        |
|    144     |             Trek Domane ALR 4 Disc - 2018             |        20        |
|    145     |             Trek Domane ALR 5 Disc - 2018             |        39        |
|    146     |                Trek Domane SLR 6 - 2018               |        18        |
|    147     |            Trek Domane ALR 5 Gravel - 2018            |        24        |
|    148     |              Trek Domane SL 8 Disc - 2018             |        39        |
|    149     |             Trek Domane SLR 8 Disc - 2018             |        24        |
|    150     |                Trek Emonda SL 7 - 2018                |        50        |
|    151     |         Trek Domane ALR 4 Disc Women's - 2018         |        27        |
|    152     |          Trek Domane SL 5 Disc Women's - 2018         |        34        |
|    153     |            Trek Domane SL 7 Women's - 2018            |        53        |
|    154     |         Trek Domane SLR 6 Disc Women's - 2018         |        44        |
|    155     |             Trek Domane SLR 9 Disc - 2018             |        54        |
|    156     |             Trek Domane SL Frameset - 2018            |        35        |
|    157     |         Trek Domane SL Frameset Women's - 2018        |        65        |
|    158     |                 Trek CrossRip 1 - 2018                |        28        |
|    159     |                Trek Emonda ALR 6 - 2018               |        54        |
|    160     |                Trek Emonda SLR 6 - 2018               |        31        |
|    161     |                    Surly ECR - 2018                   |        37        |
|    162     |              Trek Emonda SL 6 Disc - 2018             |        43        |
|    163     |                 Surly Pack Rat - 2018                 |        41        |
|    164     |              Surly Straggler 650b - 2018              |        42        |
|    165     |                    Trek 1120 - 2018                   |        41        |
|    166     |            Trek Domane AL 2 Women's - 2018            |        77        |
|    167     |               Surly ECR Frameset - 2018               |        37        |
|    168     |                 Surly Straggler - 2018                |        52        |
|    169     |                Trek Emonda SLR 8 - 2018               |        29        |
|    170     |                 Trek CrossRip 2 - 2018                |        29        |
|    171     |                Trek Domane SL 6 - 2018                |        42        |
|    172     |          Trek Domane ALR Disc Frameset - 2018         |        41        |
|    173     |            Trek Domane ALR Frameset - 2018            |        34        |
|    174     |          Trek Domane SLR Disc Frameset - 2018         |        35        |
|    175     |            Trek Domane SLR Frameset - 2018            |        5         |
|    176     |             Trek Madone 9 Frameset - 2018             |        43        |
|    177     |             Trek Domane SLR 6 Disc - 2018             |        30        |
|    178     |                Trek Domane AL 2 - 2018                |        36        |
|    179     |                Trek Domane AL 3 - 2018                |        52        |
|    180     |            Trek Domane AL 3 Women's - 2018            |        14        |
|    181     |                Trek Domane SL 5 - 2018                |        56        |
|    182     |              Trek Domane SL 5 Disc - 2018             |        77        |
|    183     |            Trek Domane SL 5 Women's - 2018            |        63        |
|    184     |              Trek Domane SL 6 Disc - 2018             |        25        |
|    185     |                  Trek Conduit+ - 2018                 |        22        |
|    186     |                 Trek CrossRip+ - 2018                 |        47        |
|    187     |                   Trek Neko+ - 2018                   |        28        |
|    188     |               Trek XM700+ Lowstep - 2018              |        86        |
|    189     |               Trek Lift+ Lowstep - 2018               |        39        |
|    190     |                Trek Dual Sport+ - 2018                |        59        |
|    191     |               Electra Loft Go! 8i - 2018              |        59        |
|    192     |           Electra Townie Go! 8i - 2017/2018           |        30        |
|    193     |                   Trek Lift+ - 2018                   |        56        |
|    194     |                   Trek XM700+ - 2018                  |        59        |
|    195     |          Electra Townie Go! 8i Ladies' - 2018         |        40        |
|    196     |                   Trek Verve+ - 2018                  |        79        |
|    197     |               Trek Verve+ Lowstep - 2018              |        40        |
|    198     |           Electra Townie Commute Go! - 2018           |        28        |
|    199     |       Electra Townie Commute Go! Ladies' - 2018       |        20        |
|    200     |                 Trek Powerfly 5 - 2018                |        67        |
|    201     |               Trek Powerfly 5 FS - 2018               |        70        |
|    202     |             Trek Powerfly 5 Women's - 2018            |        17        |
|    203     |               Trek Powerfly 7 FS - 2018               |        17        |
|    204     |             Trek Super Commuter+ 7 - 2018             |        64        |
|    205     |             Trek Super Commuter+ 8S - 2018            |        25        |
|    206     |                Trek Boone 5 Disc - 2018               |        48        |
|    207     |                Trek Boone 7 Disc - 2018               |        64        |
|    208     |              Trek Crockett 5 Disc - 2018              |        37        |
|    209     |              Trek Crockett 7 Disc - 2018              |        34        |
|    210     |                 Surly Straggler - 2018                |        57        |
|    211     |              Surly Straggler 650b - 2018              |        20        |
|    212     |           Electra Townie Original 21D - 2018          |        62        |
|    213     |           Electra Cruiser 1 - 2016/2017/2018          |        34        |
|    214     |             Electra Tiger Shark 3i - 2018             |        41        |
|    215     |           Electra Queen of Hearts 3i - 2018           |        24        |
|    216     |              Electra Super Moto 8i - 2018             |        35        |
|    217     |              Electra Straight 8 3i - 2018             |        37        |
|    218     |          Electra Cruiser 7D - 2016/2017/2018          |        74        |
|    219     |                 Electra Moto 3i - 2018                |        75        |


---

## Level 5: Additional Advanced SQL
(using Pandas read_sql)

### Task 1: Aggregate Sales by City and State
Write a query to calculate the total sales, average order value, and maximum order value for customers in each city and state.

In [80]:
%%sql
SELECT c.city, c.state,
       SUM(oi.quantity * oi.list_price) AS total_sales,
       AVG(oi.quantity * oi.list_price) AS average_order_value,
       MAX(oi.quantity * oi.list_price) AS maximum_order_value
FROM customers c
JOIN orders o ON c.customer_id = o.customer_id
JOIN order_items oi ON o.order_id = oi.order_id
GROUP BY c.city, c.state
ORDER BY total_sales DESC;

Running query in 'mysql+pymysql://root:***@localhost/bike_zeyad'

195 rows affected.

+------------------------+-------+-------------+---------------------+---------------------+
|          city          | state | total_sales | average_order_value | maximum_order_value |
+------------------------+-------+-------------+---------------------+---------------------+
|      Mount Vernon      |   NY  |  117010.21  |     1950.170167     |       9999.98       |
|      Ballston Spa      |   NY  |  110065.34  |     2116.641154     |       11999.98      |
|       San Angelo       |   TX  |  109729.26  |     2070.363396     |       10999.98      |
|     Baldwinsville      |   NY  |  105893.45  |     2861.985135     |       12999.98      |
|      Howard Beach      |   NY  |  104250.51  |     2895.847500     |       23999.98      |
|      Orchard Park      |   NY  |  101189.27  |     2108.109792     |       10999.98      |
|     Canyon Country     |   CA  |   96243.47  |     2187.351591     |       7999.98       |
|         Monroe         |   NY  |   93938.34  |     2134.962273     |       23999.98      |
|        Houston         |   TX  |   90449.47  |     2055.669773     |       9999.98       |
|        Astoria         |   NY  |   89650.56  |     2801.580000     |       12999.98      |
|     Central Islip      |   NY  |   86516.50  |     2059.916667     |       10599.98      |
|       Smithtown        |   NY  |   85423.52  |     2372.875556     |       10999.98      |
|       Harlingen        |   TX  |   85284.58  |     3280.176154     |       12999.98      |
|       Amityville       |   NY  |   84748.55  |     2492.604412     |       14999.98      |
|          Troy          |   NY  |   84367.62  |     3013.129286     |       10999.98      |
|    Port Washington     |   NY  |   82867.34  |     1973.031905     |       12999.98      |
| Palos Verdes Peninsula |   CA  |   82439.51  |     2355.414571     |       10599.98      |
|        Webster         |   NY  |   80738.50  |     2242.736111     |       10999.98      |
|        Merrick         |   NY  |   80471.38  |     1828.895000     |       7999.98       |
|        Ossining        |   NY  |   79873.39  |     1699.433830     |       6999.98       |
|     South El Monte     |   CA  |   77312.40  |     1718.053333     |       9999.98       |
|       Uniondale        |   NY  |   74941.48  |     2081.707778     |       10599.98      |
|        San Jose        |   CA  |   74585.60  |     2571.917241     |       7999.98       |
|   Huntington Station   |   NY  |   74302.57  |     2476.752333     |       12999.98      |
|      Canandaigua       |   NY  |   73946.33  |     1478.926600     |       6999.98       |
|       Liverpool        |   NY  |   73780.48  |     2170.014118     |       12999.98      |
|      Floral Park       |   NY  |   73527.53  |     2297.735313     |       12999.98      |
|       Scarsdale        |   NY  |   71930.18  |     1179.183279     |       5799.98       |
|      San Lorenzo       |   CA  |   71133.44  |     2032.384000     |       9999.98       |
|    North Tonawanda     |   NY  |   70570.50  |     2075.602941     |       10599.98      |
|     East Elmhurst      |   NY  |   69816.49  |     2053.426176     |       10599.98      |
|         Duarte         |   CA  |   69143.49  |     2160.734063     |       9999.98       |
|       Bay Shore        |   NY  |   69064.51  |     2227.887419     |       10999.98      |
|        Campbell        |   CA  |   67848.40  |     1739.702564     |       10999.98      |
|        Garland         |   TX  |   65123.55  |     2170.785000     |       7999.98       |
|    Franklin Square     |   NY  |   63133.58  |     1618.809744     |       6999.98       |
|        Longview        |   TX  |   62873.46  |     1654.564737     |       7999.98       |
|      Santa Clara       |   CA  |   62289.70  |     2831.350000     |       12999.98      |
|         Forney         |   TX  |   62067.56  |     1724.098889     |       10999.98      |
|        New York        |   NY  |   61890.58  |     2134.157931     |       9999.98       |
|      New Rochelle      |   NY  |   60026.57  |     2223.206296     |       10999.98      |
|     Spring Valley      |   NY  |   59073.46  |     1846.045625     |       11999.98      |
|      Garden City       |   NY  |   58458.67  |     2541.681304     |       9999.98       |
|       Ronkonkoma       |   NY  |   58162.57  |     1817.580313     |       10999.98      |
|       Hempstead        |   NY  |   57995.70  |     2416.487500     |       9999.98       |
|     East Northport     |   NY  |   57804.56  |     1864.663226     |       10599.98      |
|         Upland         |   CA  |   57693.50  |     1748.287879     |       9999.98       |
|        Maspeth         |   NY  |   57629.61  |     2058.200357     |       7999.98       |
|       Sunnyside        |   NY  |   57513.49  |     1554.418649     |       5799.98       |
|        Bellmore        |   NY  |   57340.55  |     1911.351667     |       7999.98       |
|        Jamaica         |   NY  |   57231.54  |     1635.186857     |       5999.99       |
|        Baldwin         |   NY  |   56987.56  |     1726.895758     |       9999.98       |
|        Fairport        |   NY  |   56825.66  |     2470.680870     |       9999.98       |
|        Newburgh        |   NY  |   56198.57  |     1812.857097     |       10599.98      |
|         Encino         |   CA  |   55750.57  |     1798.405484     |       7999.98       |
|         Euless         |   TX  |   55562.48  |     1462.170526     |       6999.98       |
|       Plainview        |   NY  |   54819.61  |     2108.446538     |       7499.99       |
|       Sacramento       |   CA  |   54760.58  |     1955.735000     |       7999.98       |
|         Utica          |   NY  |   54702.73  |     2026.027037     |       11999.99      |
|        Glendora        |   CA  |   54647.56  |     1707.736250     |       9999.98       |
|       Long Beach       |   NY  |   54236.60  |     1749.567742     |       7999.98       |
|     Corpus Christi     |   TX  |   53917.53  |     1797.251000     |       12999.98      |
|       Coachella        |   CA  |   53605.69  |     2680.284500     |       10599.98      |
|       San Carlos       |   CA  |   53410.54  |     1907.519286     |       12999.98      |
|     Richmond Hill      |   NY  |   53348.37  |     1301.179756     |       7999.98       |
|         Monsey         |   NY  |   53280.65  |     1776.021667     |       9999.98       |
| Port Jefferson Station |   NY  |   53205.62  |     1970.578519     |       9999.98       |
|     Redondo Beach      |   CA  |   52223.63  |     2008.601154     |       11999.98      |
|       Patchogue        |   NY  |   51797.70  |     2466.557143     |       11999.98      |
|         Ithaca         |   NY  |   51568.68  |     2455.651429     |       9999.98       |
|         Desoto         |   TX  |   51543.50  |     1393.067568     |       7999.98       |
|       Sugar Land       |   TX  |   51423.61  |     1836.557500     |       11999.98      |
|         Oxnard         |   CA  |   51314.51  |     1509.250294     |       6999.98       |
|    South Ozone Park    |   NY  |   50825.56  |     1540.168485     |       5399.98       |
|       Lancaster        |   NY  |   50798.60  |     1881.429630     |       6999.98       |
|        Anaheim         |   CA  |   50406.49  |     1440.185429     |       6999.98       |
|      New Windsor       |   NY  |   50254.68  |     1932.872308     |       9999.98       |
|        Elmhurst        |   NY  |   49959.55  |     1561.235938     |       7999.98       |
|      Apple Valley      |   CA  |   49916.55  |     1721.260345     |       10999.98      |
|       Whitestone       |   NY  |   49895.66  |     2169.376522     |       10599.98      |
|        Torrance        |   CA  |   49844.64  |     1661.488000     |       7999.98       |
|       Brentwood        |   NY  |   49376.57  |     1763.448929     |       9999.98       |
|    Wappingers Falls    |   NY  |   49115.65  |     1964.626000     |       11999.98      |
|        Kingston        |   NY  |   48255.59  |     1462.290606     |       4999.99       |
|        El Paso         |   TX  |   48124.67  |     2005.194583     |       9999.98       |
|        Banning         |   CA  |   47268.57  |     1477.142813     |       7999.98       |
|        Buffalo         |   NY  |   46293.61  |     1402.836667     |       11999.98      |
|       Woodhaven        |   NY  |   45095.68  |     1878.986667     |       7999.98       |
|      Plattsburgh       |   NY  |   44952.71  |     2140.605238     |       9999.98       |
|          Rome          |   NY  |   44952.65  |     1605.451786     |       5599.98       |
|         Oswego         |   NY  |   44590.65  |     1715.025000     |       5799.98       |
|        Woodside        |   NY  |   44233.57  |     1474.452333     |       5999.98       |
|        Victoria        |   TX  |   43284.70  |     1881.943478     |       6999.98       |
|    Jackson Heights     |   NY  |   43005.60  |     1654.061538     |       9999.98       |
|       Massapequa       |   NY  |   42934.67  |     1717.386800     |       6999.98       |
|        Brooklyn        |   NY  |   42597.64  |     1638.370769     |       9999.98       |
|       San Pablo        |   CA  |   42234.66  |     1508.380714     |       5999.98       |
|    Massapequa Park     |   NY  |   41418.70  |     1882.668182     |       5999.98       |
|        Rowlett         |   TX  |   40941.69  |     1705.903750     |       7999.98       |
|         Nanuet         |   NY  |   40620.84  |     4062.084000     |       9999.98       |
|       West Islip       |   NY  |   40206.77  |     2116.145789     |       6499.99       |
|         Vista          |   CA  |   39987.72  |     1904.177143     |       9999.98       |
|    Saratoga Springs    |   NY  |   39446.67  |     1793.030455     |       11999.98      |
|        Oakland         |   CA  |   39043.63  |     1626.817917     |       7199.98       |
|        Mahopac         |   NY  |   38839.70  |     1618.320833     |       4999.99       |
|       Pleasanton       |   CA  |   38815.67  |     1617.319583     |       5499.99       |
|        Bethpage        |   NY  |   38490.70  |     1924.535000     |       7999.98       |
|       Ridgecrest       |   CA  |   38442.67  |     1671.420435     |       5499.99       |
|         Depew          |   NY  |   38137.73  |     1906.886500     |       9999.98       |
|     Staten Island      |   NY  |   38035.74  |     1728.897273     |       7999.98       |
|        Lawndale        |   CA  |   38025.61  |     1267.520333     |       7999.98       |
|       Pittsford        |   NY  |   37960.66  |     1518.426400     |       7999.98       |
|      Schenectady       |   NY  |   37828.73  |     1891.436500     |       6999.98       |
|       Fullerton        |   CA  |   37669.76  |     2092.764444     |       9999.98       |
|         Hollis         |   NY  |   36560.71  |     1589.596087     |       6399.98       |
|       Richardson       |   TX  |   36478.77  |     2026.598333     |       9999.98       |
|     Niagara Falls      |   NY  |   36358.71  |     1913.616316     |       12999.98      |
|        Lockport        |   NY  |   36209.81  |     2785.370000     |       12999.98      |
|      Santa Monica      |   CA  |   33921.73  |     1615.320476     |       5999.98       |
|    Rockville Centre    |   NY  |   33730.67  |     1405.444583     |       5499.99       |
|       Oceanside        |   NY  |   32341.85  |     2940.168182     |       11999.98      |
|        Bayside         |   NY  |   32286.73  |     1614.336500     |       5999.98       |
|     New Hyde Park      |   NY  |   32030.72  |     1779.484444     |       5999.98       |
|    Oakland Gardens     |   NY  |   31865.84  |     2451.218462     |       10999.98      |
|      Port Chester      |   NY  |   31770.79  |     1985.674375     |       9999.98       |
|       San Diego        |   CA  |   31256.76  |     1645.092632     |       6499.99       |
|         Bronx          |   NY  |   31140.74  |     1482.892381     |       10599.98      |
|      Lindenhurst       |   NY  |   31011.63  |     1107.558214     |       6999.98       |
|       Santa Cruz       |   CA  |   30489.79  |     1793.517059     |       4999.99       |
|      Lake Jackson      |   TX  |   30254.78  |     2521.231667     |       9999.98       |
|         Carmel         |   NY  |   30075.69  |     1156.757308     |       7999.98       |
|       Los Banos        |   CA  |   30059.73  |     1582.091053     |       5799.98       |
|        Rocklin         |   CA  |   28606.68  |     1300.303636     |       6399.98       |
|       Fort Worth       |   TX  |   28581.78  |     1681.281176     |       9999.98       |
|        Atwater         |   CA  |   27959.69  |     1270.895000     |       3265.98       |
|       Rochester        |   NY  |   27709.73  |     1259.533182     |       4999.99       |
|     Valley Stream      |   NY  |   27342.75  |     1608.397059     |       5999.98       |
|        Shirley         |   NY  |   27184.82  |     1510.267778     |       5799.98       |
|       Centereach       |   NY  |   27048.75  |     1423.618421     |       7999.98       |
|       Jamestown        |   NY  |   26919.73  |     1345.986500     |       7999.98       |
|        Wantagh         |   NY  |   26763.81  |     2058.754615     |       10599.98      |
|       Hicksville       |   NY  |   26509.71  |     1325.485500     |       5799.98       |
|       Levittown        |   NY  |   26105.83  |     1864.702143     |       6499.99       |
|      West Babylon      |   NY  |   25676.79  |     1283.839500     |       4499.98       |
|       Queensbury       |   NY  |   25561.75  |     1503.632353     |       5999.98       |
|        Endicott        |   NY  |   25508.77  |     1700.584667     |       5399.98       |
|        Rosedale        |   NY  |   25441.75  |     1413.430556     |       6399.98       |
|      Farmingdale       |   NY  |   24961.73  |     1134.624091     |       3499.99       |
|        Flushing        |   NY  |   24234.77  |     1425.574706     |       5999.99       |
|   Hopewell Junction    |   NY  |   24198.81  |     1512.425625     |       5999.98       |
|     West Hempstead     |   NY  |   23867.80  |     1704.842857     |       5499.99       |
|         Fresno         |   CA  |   23000.71  |     1150.035500     |       6399.98       |
|       Amsterdam        |   NY  |   22833.81  |     1522.254000     |       10599.98      |
|        Syosset         |   NY  |   22775.80  |     1265.322222     |       5999.98       |
|         Pomona         |   CA  |   22636.75  |     1191.407895     |       4999.98       |
|      Poughkeepsie      |   NY  |   21910.81  |     1685.446923     |       10999.98      |
|        Hamburg         |   NY  |   20927.77  |     1231.045294     |       6999.98       |
|     Fresh Meadows      |   NY  |   20894.83  |     1741.235833     |       5299.99       |
|       Glen Cove        |   NY  |   20825.73  |     1041.286500     |       3265.98       |
|      Forest Hills      |   NY  |   20723.77  |     1295.235625     |       3098.00       |
|        New City        |   NY  |   20265.79  |     1192.105294     |       3999.99       |
|         Coram          |   NY  |   19138.83  |     1125.813529     |       3098.00       |
|        Helotes         |   TX  |   18958.84  |     1579.903333     |       9999.98       |
|        Yonkers         |   NY  |   18399.72  |      876.177143     |       5799.98       |
|      East Meadow       |   NY  |   18258.81  |     1521.567500     |       3199.99       |
|       Ozone Park       |   NY  |   18209.87  |     1655.442727     |       5299.99       |
|  South Richmond Hill   |   NY  |   18179.84  |     1817.984000     |       5999.98       |
|       Huntington       |   NY  |   17977.81  |     1198.520667     |       3599.98       |
|        Ontario         |   CA  |   17944.87  |     1631.351818     |       3999.99       |
|         Albany         |   NY  |   17539.91  |     2923.318333     |       5999.99       |
|        Holbrook        |   NY  |   17498.89  |     2187.361250     |       5999.99       |
|      Saint Albans      |   NY  |   17277.74  |     1079.858750     |       2299.99       |
|         Selden         |   NY  |   16849.83  |     1123.322000     |       3999.99       |
|       Deer Park        |   NY  |   16564.84  |     1380.403333     |       7999.98       |
|         Corona         |   NY  |   15576.85  |     1416.077273     |       7999.98       |
|     Middle Village     |   NY  |   14999.94  |     4999.980000     |       7199.98       |
|        Freeport        |   NY  |   13570.86  |     1233.714545     |       4999.98       |
|      Bakersfield       |   CA  |   13403.87  |     1116.989167     |       2999.99       |
|        Amarillo        |   TX  |   13165.78  |     1012.752308     |       1839.98       |
|       Rego Park        |   NY  |   12318.83  |      947.602308     |       1999.98       |
|         Elmont         |   NY  |   12127.80  |      932.907692     |       3599.98       |
|      Los Angeles       |   CA  |   11711.89  |     1463.986250     |       3199.99       |
|         Auburn         |   NY  |   11607.86  |     1160.786000     |       3798.00       |
|    Yorktown Heights    |   NY  |   10844.86  |     1084.486000     |       1799.99       |
|        Commack         |   NY  |   10487.90  |     1498.271429     |       5999.98       |
|      Clifton Park      |   NY  |   9063.80   |      755.316667     |       2641.98       |
|       Yuba City        |   CA  |   6899.95   |     2299.983333     |       5199.98       |
|        Mcallen         |   TX  |   6874.92   |      982.131429     |       3499.99       |
|     Mountain View      |   CA  |   6194.93   |     1032.488333     |       2939.98       |
|      San Antonio       |   TX  |   4621.89   |      660.270000     |       1319.98       |
|     Copperas Cove      |   TX  |   3337.94   |      834.485000     |       1319.98       |
|      Far Rockaway      |   NY  |   3249.94   |      649.988000     |        899.98       |
|  Springfield Gardens   |   NY  |   1889.95   |      629.983333     |        879.98       |
|        Westbury        |   NY  |   1437.98   |      718.990000     |        898.00       |
|       Tonawanda        |   NY  |   1347.99   |      673.995000     |        858.00       |
+------------------------+-------+-------------+---------------------+---------------------+

### Task 2: Find Top-Selling Products in 2018
Write a query to identify the products with the highest sales volume in the year 2018.

In [82]:
%%sql
SELECT p.product_id, p.product_name, 
       SUM(oi.quantity) AS sold_units
FROM products p
JOIN order_items oi ON p.product_id = oi.product_id
JOIN orders o ON oi.order_id = o.order_id
WHERE YEAR(o.order_date) = 2018
GROUP BY p.product_name
ORDER BY sold_units DESC;

Running query in 'mysql+pymysql://root:***@localhost/bike_zeyad'

273 rows affected.

+------------+-------------------------------------------------------+------------+
| product_id |                      product_name                     | sold_units |
+------------+-------------------------------------------------------+------------+
|    304     |       Electra Townie Original 21D EQ - 2017/2018      |     16     |
|     12     |           Electra Townie Original 21D - 2016          |     15     |
|    300     |      Electra Townie Balloon 3i EQ Ladies' - 2018      |     14     |
|    199     |       Electra Townie Commute Go! Ladies' - 2018       |     13     |
|    251     |           Electra Townie Commute Go! - 2018           |     12     |
|     86     |              Trek Girl's Kickster - 2017              |     12     |
|    240     |        Electra Townie Commute 27D Ladies - 2018       |     11     |
|     92     |                Haro Shredder 20 - 2017                |     11     |
|    235     |             Electra Koa 3i Ladies' - 2018             |     11     |
|    263     |         Strider Classic 12 Balance Bike - 2018        |     11     |
|    242     |        Electra Townie Commute 8D Ladies' - 2018       |     11     |
|    295     |             Electra Treasure 1 20" - 2018             |     10     |
|     78     |         Sun Bicycles Biscayne Tandem CB - 2017        |     10     |
|    142     |              Trek Fuel EX 8 29 XT - 2018              |     10     |
|    230     |          Electra Cruiser Lux 1 Ladies' - 2018         |     10     |
|    168     |                 Surly Straggler - 2018                |     9      |
|    255     |    Electra Townie Balloon 7i EQ Ladies' - 2017/2018   |     9      |
|    107     |               Sun Bicycles Cruz 7 - 2017              |     9      |
|    265     |            Strider Strider 20 Sport - 2018            |     9      |
|    124     |                  Surly Krampus - 2018                 |     9      |
|    204     |             Trek Super Commuter+ 7 - 2018             |     8      |
|    205     |             Trek Super Commuter+ 8S - 2018            |     8      |
|     93     |             Haro Shredder 20 Girls - 2017             |     8      |
|    282     |     Electra Cyclosaurus 1 (16-inch) - Boy's - 2018    |     8      |
|    194     |                   Trek XM700+ - 2018                  |     8      |
|    243     |     Electra Townie Original 21D EQ Ladies' - 2018     |     8      |
|    297     |           Electra Under-The-Sea 1 16" - 2018          |     8      |
|    271     |            Trek Precaliber 16 Girl's - 2018           |     8      |
|    128     |                 Surly ECR 27.5 - 2018                 |     8      |
|    203     |               Trek Powerfly 7 FS - 2018               |     8      |
|    268     |                  Trek Kickster - 2018                 |     8      |
|     60     |            Sun Bicycles ElectroLite - 2017            |     8      |
|    109     |          Sun Bicycles Cruz 7 - Women's - 2017         |     8      |
|    123     |           Trek Farley Carbon Frameset - 2018          |     8      |
|    113     |                  Trek Marlin 5 - 2018                 |     8      |
|    171     |                Trek Domane SL 6 - 2018                |     8      |
|    301     |          Electra Townie Balloon 7i EQ - 2018          |     8      |
|    216     |              Electra Super Moto 8i - 2018             |     8      |
|    163     |                 Surly Pack Rat - 2018                 |     8      |
|     41     |                  Haro Shift R3 - 2017                 |     8      |
|    101     |       Electra Townie 7D (20-inch) - Boys' - 2017      |     8      |
|    207     |                Trek Boone 7 Disc - 2018               |     8      |
|    180     |            Trek Domane AL 3 Women's - 2018            |     8      |
|    248     |   Electra Townie Original 7D EQ Ladies' - 2017/2018   |     7      |
|    172     |          Trek Domane ALR Disc Frameset - 2018         |     7      |
|    307     |     Electra Townie Balloon 8D EQ - 2016/2017/2018     |     7      |
|     66     |           Sun Bicycles Revolutions 24 - 2017          |     7      |
|    145     |             Trek Domane ALR 5 Disc - 2018             |     7      |
|     65     |          Sun Bicycles Lil Bolt Type-R - 2017          |     7      |
|    283     |     Electra Heartchya 1 (20-inch) - Girl's - 2018     |     7      |
|    227     |    Electra Cruiser 7D (24-Inch) Ladies' - 2016/2018   |     7      |
|    153     |            Trek Domane SL 7 Women's - 2018            |     7      |
|     49     |                Trek Domane SL 6 - 2017                |     7      |
|     48     |                 Trek Emonda S 4 - 2017                |     7      |
|    141     |                  Trek Stache 5 - 2018                 |     7      |
|     43     |           Trek Fuel EX 9.8 27.5 Plus - 2017           |     7      |
|    126     |          Surly Big Fat Dummy Frameset - 2018          |     7      |
|    188     |               Trek XM700+ Lowstep - 2018              |     7      |
|    102     |           Electra Townie Original 7D - 2017           |     7      |
|    223     |             Electra Cruiser Lux 3i - 2018             |     7      |
|    159     |                Trek Emonda ALR 6 - 2018               |     7      |
|    185     |                  Trek Conduit+ - 2018                 |     7      |
|    151     |         Trek Domane ALR 4 Disc Women's - 2018         |     7      |
|     28     |       Surly Karate Monkey 27.5+ Frameset - 2017       |     7      |
|     61     |             Trek Powerfly 8 FS Plus - 2017            |     7      |
|    308     | Electra Townie Balloon 8D EQ Ladies' - 2016/2017/2018 |     7      |
|    213     |           Electra Cruiser 1 - 2016/2017/2018          |     7      |
|     37     |             Haro Flightline One ST - 2017             |     7      |
|    147     |            Trek Domane ALR 5 Gravel - 2018            |     7      |
|     97     |     Electra Savannah 3i (20-inch) - Girl's - 2017     |     7      |
|    269     |            Trek Precaliber 12 Boy's - 2018            |     6      |
|    225     |          Electra Delivery 3i - 2016/2017/2018         |     6      |
|     76     |           Electra Girl's Hawaii 1 16" - 2017          |     6      |
|     96     |        Electra Moto 3i (20-inch) - Boy's - 2017       |     6      |
|     52     |                Surly Steamroller - 2017               |     6      |
|     89     |             Trek Precaliber 16 Boys - 2017            |     6      |
|    305     |        Electra Townie Balloon 3i EQ - 2017/2018       |     6      |
|     58     |                 Trek Madone 9.2 - 2017                |     6      |
|    190     |                Trek Dual Sport+ - 2018                |     6      |
|     99     |    Electra Sugar Skulls 1 (20-inch) - Girl's - 2017   |     6      |
|     27     |            Surly Big Dummy Frameset - 2017            |     6      |
|    229     |           Electra Cruiser Lux 1 - 2016/2018           |     6      |
|     40     |               Trek Fuel EX 9.8 29 - 2017              |     6      |
|    184     |              Trek Domane SL 6 Disc - 2018             |     6      |
|    100     |     Electra Townie 3i EQ (20-inch) - Boys' - 2017     |     6      |
|    215     |           Electra Queen of Hearts 3i - 2018           |     6      |
|     7      |                Trek Slash 8 27.5 - 2016               |     6      |
|    293     |     Electra Tiger Shark 1 (20-inch) - Boys' - 2018    |     6      |
|    106     |               Sun Bicycles Cruz 3 - 2017              |     6      |
|    241     |            Electra Townie Commute 8D - 2018           |     6      |
|     39     |                  Trek Stache 5 - 2017                 |     6      |
|    220     |            Electra Cruiser 1 Ladies' - 2018           |     6      |
|    164     |              Surly Straggler 650b - 2018              |     6      |
|    253     |          Electra Townie Go! 8i Ladies' - 2018         |     6      |
|    234     |          Electra Daydreamer 3i Ladies' - 2018         |     6      |
|     13     |           Electra Cruiser 1 (24-Inch) - 2016          |     6      |
|    237     |                Electra Relic 3i - 2018                |     6      |
|    138     |               Trek Fuel EX 5 Plus - 2018              |     6      |
|    160     |                Trek Emonda SLR 6 - 2018               |     5      |
|    249     |             Electra White Water 3i - 2018             |     5      |
|    209     |              Trek Crockett 7 Disc - 2018              |     5      |
|    119     |                 Trek Kids' Neko - 2018                |     5      |
|    302     |            Electra Townie Original 1 - 2018           |     5      |
|    130     |           Trek Stache Carbon Frameset - 2018          |     5      |
|    197     |               Trek Verve+ Lowstep - 2018              |     5      |
|    182     |              Trek Domane SL 5 Disc - 2018             |     5      |
|     14     |     Electra Girl's Hawaii 1 (16-inch) - 2015/2016     |     5      |
|    129     |                Trek X-Caliber 7 - 2018                |     5      |
|    292     |    Electra Sweet Ride 3i (20-inch) - Girls' - 2018    |     5      |
|    193     |                   Trek Lift+ - 2018                   |     5      |
|     18     |   Pure Cycles Western 3-Speed - Women's - 2015/2016   |     5      |
|    155     |             Trek Domane SLR 9 Disc - 2018             |     5      |
|    257     |    Electra Amsterdam Fashion 3i Ladies' - 2017/2018   |     5      |
|     2      |           Ritchey Timberwolf Frameset - 2016          |     5      |
|    275     |            Trek Precaliber 20 Girl's - 2018           |     5      |
|    298     |     Electra Water Lily 1 (16-inch) - Girl's - 2018    |     5      |
|     54     |          Trek Domane SL Disc Frameset - 2017          |     5      |
|     15     |                 Electra Moto 1 - 2016                 |     5      |
|    127     |             Surly Pack Rat Frameset - 2018            |     5      |
|     71     |            Sun Bicycles Atlas X-Type - 2017           |     5      |
|    219     |                 Electra Moto 3i - 2018                |     5      |
|    158     |                 Trek CrossRip 1 - 2018                |     5      |
|    181     |                Trek Domane SL 5 - 2018                |     5      |
|    173     |            Trek Domane ALR Frameset - 2018            |     5      |
|     46     |                   Haro SR 1.3 - 2017                  |     5      |
|    196     |                   Trek Verve+ - 2018                  |     5      |
|     29     |                Trek X-Caliber 8 - 2017                |     5      |
|    115     |                Trek Fuel EX 8 29 - 2018               |     5      |
|     36     |              Surly Troll Frameset - 2017              |     5      |
|     84     |             Sun Bicycles Lil Kitt'n - 2017            |     5      |
|    286     |             Electra Starship 1 16" - 2018             |     5      |
|    110     |             Sun Bicycles Drifter 7 - 2017             |     5      |
|    214     |             Electra Tiger Shark 3i - 2018             |     5      |
|    139     |               Trek Remedy 7 27.5 - 2018               |     5      |
|     82     |      Electra Amsterdam Original 3i Ladies' - 2017     |     5      |
|    244     |       Electra Townie Original 21D Ladies' - 2018      |     5      |
|    166     |            Trek Domane AL 2 Women's - 2018            |     5      |
|    202     |             Trek Powerfly 5 Women's - 2018            |     5      |
|    264     |                Strider Sport 16 - 2018                |     5      |
|    137     |               Heller Shagamaw GX1 - 2018              |     5      |
|    122     |              Surly Troll Frameset - 2018              |     5      |
|     53     |               Surly Ogre Frameset - 2017              |     5      |
|    162     |              Trek Emonda SL 6 Disc - 2018             |     4      |
|     50     |            Trek Silque SLR 7 Women's - 2017           |     4      |
|    274     |            Trek Precaliber 20 Boy's - 2018            |     4      |
|     20     |     Electra Townie Original 7D EQ - Women's - 2016    |     4      |
|    224     |             Electra Cruiser Lux 7D - 2018             |     4      |
|    165     |                    Trek 1120 - 2018                   |     4      |
|    105     |            Sun Bicycles Streamway 7 - 2017            |     4      |
|    313     |        Electra Townie Original 1 Ladies' - 2018       |     4      |
|     17     |            Pure Cycles Vine 8-Speed - 2016            |     4      |
|    231     |         Electra Cruiser Lux 3i Ladies' - 2018         |     4      |
|    186     |                 Trek CrossRip+ - 2018                 |     4      |
|    131     |             Heller Bloodhound Trail - 2018            |     4      |
|     81     |      Electra Amsterdam Fashion 7i Ladies' - 2017      |     4      |
|     77     |          Electra Glam Punk 3i Ladies' - 2017          |     4      |
|    276     |       Trek Precaliber 24 (7-Speed) - Boys - 2018      |     4      |
|    149     |             Trek Domane SLR 8 Disc - 2018             |     4      |
|    104     |             Sun Bicycles Streamway - 2017             |     4      |
|     23     |     Electra Girl's Hawaii 1 (20-inch) - 2015/2016     |     4      |
|    178     |                Trek Domane AL 2 - 2018                |     4      |
|    135     |             Trek X-Caliber Frameset - 2018            |     4      |
|     70     |       Electra Amsterdam Original 3i - 2015/2017       |     4      |
|    112     |                    Trek 820 - 2018                    |     4      |
|    120     |                Trek Fuel EX 7 29 - 2018               |     4      |
|    217     |              Electra Straight 8 3i - 2018             |     4      |
|     57     |                 Trek Emonda S 5 - 2017                |     4      |
|    117     |               Trek Ticket S Frame - 2018              |     4      |
|    169     |                Trek Emonda SLR 8 - 2018               |     4      |
|    250     |           Electra Townie Go! 8i - 2017/2018           |     4      |
|     85     |                Haro Downtown 16 - 2017                |     4      |
|    161     |                    Surly ECR - 2018                   |     3      |
|    152     |          Trek Domane SL 5 Disc Women's - 2018         |     3      |
|    187     |                   Trek Neko+ - 2018                   |     3      |
|    134     |           Trek Remedy 27.5 C Frameset - 2018          |     3      |
|    118     |                Trek X-Caliber 8 - 2018                |     3      |
|    103     |            Sun Bicycles Streamway 3 - 2017            |     3      |
|    156     |             Trek Domane SL Frameset - 2018            |     3      |
|    246     |      Electra Townie Original 3i EQ Ladies' - 2018     |     3      |
|    233     |         Electra Cruiser Lux Fat Tire 7D - 2018        |     3      |
|     56     |             Trek Domane SLR 6 Disc - 2017             |     3      |
|     9      |                  Trek Conduit+ - 2016                 |     3      |
|    114     |                  Trek Marlin 6 - 2018                 |     3      |
|     67     |      Sun Bicycles Revolutions 24 - Girl's - 2017      |     3      |
|     42     |            Trek Fuel EX 5 27.5 Plus - 2017            |     3      |
|    191     |               Electra Loft Go! 8i - 2018              |     3      |
|    144     |             Trek Domane ALR 4 Disc - 2018             |     3      |
|     59     |              Trek Domane S 5 Disc - 2017              |     3      |
|     31     |                 Surly Wednesday - 2017                |     3      |
|     79     |     Sun Bicycles Boardwalk (24-inch Wheels) - 2017    |     3      |
|     75     |      Electra Cruiser Lux Fat Tire 1 Ladies - 2017     |     3      |
|    111     |        Sun Bicycles Drifter 7 - Women's - 2017        |     3      |
|    245     |       Electra Townie Original 3i EQ - 2017/2018       |     3      |
|    136     |                Trek Procaliber 6 - 2018               |     3      |
|     55     |                 Trek Domane S 6 - 2017                |     3      |
|    175     |            Trek Domane SLR Frameset - 2018            |     3      |
|    132     |             Trek Procal AL Frameset - 2018            |     3      |
|    148     |              Trek Domane SL 8 Disc - 2018             |     3      |
|     91     |      Trek Precaliber 24 (21-Speed) - Girls - 2017     |     3      |
|    150     |                Trek Emonda SL 7 - 2018                |     3      |
|     4      |                Trek Fuel EX 8 29 - 2016               |     3      |
|     51     |            Trek Silque SLR 8 Women's - 2017           |     3      |
|     45     |                   Haro SR 1.2 - 2017                  |     3      |
|    179     |                Trek Domane AL 3 - 2018                |     3      |
|    140     |              Trek Remedy 9.8 27.5 - 2018              |     3      |
|     63     |          Trek Boone Race Shop Limited - 2017          |     3      |
|    259     |        Electra Amsterdam Royal 8i Ladies - 2018       |     3      |
|    208     |              Trek Crockett 5 Disc - 2018              |     3      |
|    133     |            Trek Procaliber Frameset - 2018            |     3      |
|    228     |          Electra Cruiser 7D Tall - 2016/2018          |     3      |
|     6      |         Surly Ice Cream Truck Frameset - 2016         |     3      |
|     35     |             Sun Bicycles Spider 3i - 2017             |     3      |
|    116     |               Trek Marlin 7 - 2017/2018               |     3      |
|    236     |         Electra Morningstar 3i Ladies' - 2018         |     3      |
|     3      |            Surly Wednesday Frameset - 2016            |     2      |
|     90     |            Trek Precaliber 16 Girls - 2017            |     2      |
|    108     |          Sun Bicycles Cruz 3 - Women's - 2017         |     2      |
|     8      |         Trek Remedy 29 Carbon Frameset - 2016         |     2      |
|    299     |           Electra Townie Original 21D - 2018          |     2      |
|     11     |              Surly Straggler 650b - 2016              |     2      |
|     32     |           Trek Farley Alloy Frameset - 2017           |     2      |
|    221     |         Electra Cruiser 7D Ladies' - 2016/2018        |     2      |
|    189     |               Trek Lift+ Lowstep - 2018               |     2      |
|    278     |       Trek Precaliber 24 21-speed Girl's - 2018       |     2      |
|     62     |                  Trek Boone 7 - 2017                  |     2      |
|     25     |         Electra Townie Original 7D - 2015/2016        |     2      |
|     87     |             Trek Precaliber 12 Boys - 2017            |     2      |
|     38     |           Haro Flightline Two 26 Plus - 2017          |     2      |
|     88     |            Trek Precaliber 12 Girls - 2017            |     2      |
|    232     |         Electra Cruiser Lux 7D Ladies' - 2018         |     2      |
|     26     |          Electra Townie Original 7D EQ - 2016         |     2      |
|    247     |          Electra Townie Original 7D EQ - 2018         |     2      |
|    289     |             Electra Superbolt 1 20" - 2018            |     2      |
|    146     |                Trek Domane SLR 6 - 2018               |     2      |
|    177     |             Trek Domane SLR 6 Disc - 2018             |     2      |

### Task 3: Calculate Month-over-Month Sales Growth
Write a query to calculate the month-over-month sales growth for the past years.

In [84]:
%%sql
WITH MonthlySales AS (
    SELECT DATE_FORMAT(o.order_date, '%Y-%m') AS month,
           SUM(oi.quantity * oi.list_price) AS total_sales
    FROM orders o
    JOIN order_items oi ON o.order_id = oi.order_id
    GROUP BY DATE_FORMAT(o.order_date, '%Y-%m')
)
SELECT month,
       total_sales,
       LAG(total_sales) OVER (ORDER BY month) AS month_sales
FROM MonthlySales
ORDER BY month;

Running query in 'mysql+pymysql://root:***@localhost/bike_zeyad'

35 rows affected.

+---------+-------------+-------------+
|  month  | total_sales | month_sales |
+---------+-------------+-------------+
| 2016-01 |  241184.15  |     None    |
| 2016-02 |  175768.10  |  241184.15  |
| 2016-03 |  202157.14  |  175768.10  |
| 2016-04 |  187223.55  |  202157.14  |
| 2016-05 |  228701.13  |  187223.55  |
| 2016-06 |  231120.29  |  228701.13  |
| 2016-07 |  222854.21  |  231120.29  |
| 2016-08 |  253130.83  |  222854.21  |
| 2016-09 |  303282.61  |  253130.83  |
| 2016-10 |  235051.79  |  303282.61  |
| 2016-11 |  205315.47  |  235051.79  |
| 2016-12 |  223695.20  |  205315.47  |
| 2017-01 |  316954.77  |  223695.20  |
| 2017-02 |  348740.47  |  316954.77  |
| 2017-03 |  348177.13  |  348740.47  |
| 2017-04 |  254105.57  |  348177.13  |
| 2017-05 |  297754.66  |  254105.57  |
| 2017-06 |  419892.07  |  297754.66  |
| 2017-07 |  255727.63  |  419892.07  |
| 2017-08 |  322553.32  |  255727.63  |
| 2017-09 |  329388.68  |  322553.32  |
| 2017-10 |  345316.18  |  329388.68  |
| 2017-11 |  315881.67  |  345316.18  |
| 2017-12 |  291022.87  |  315881.67  |
| 2018-01 |  426301.72  |  291022.87  |
| 2018-02 |  223941.44  |  426301.72  |
| 2018-03 |  406701.20  |  223941.44  |
| 2018-04 |  909179.47  |  406701.20  |
| 2018-06 |    209.99   |  909179.47  |
| 2018-07 |   12949.89  |    209.99   |
| 2018-08 |   10256.91  |   12949.89  |
| 2018-09 |   9949.96   |   10256.91  |
| 2018-10 |   4219.92   |   9949.96   |
| 2018-11 |   12278.93  |   4219.92   |
| 2018-12 |   7999.96   |   12278.93  |
+---------+-------------+-------------+